import ContentScopePicker from './ContentScopePicker.jsx';
import {rowYccd} from '../utils/curriculumLabel.js';
import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {api} from '../api/client.js';
import CurriculumPicker,{useCurriculum} from './CurriculumPicker.jsx';
import '../styles/matrix-v63.css';
const labels={mcq4:'TN',true_false:'ĐS',short:'TLN',matching:'GN',essay:'TL'},levels=['NB','TH','VD','VDC'];
const initial={name:'',subject_id:'',grade:7,total_score:10,duration_minutes:45,purpose:'Giữa kỳ',ratio_m1:30,ratio_m2:30,ratio_m3:20,ratio_m4:20};
export function CoveragePanel({coverage,onRefresh}){
 const [perspective,setPerspective]=useState('yccd');
 return <section className="matrix-section coverage-panel"><div className="section-heading"><h3>6. Độ phủ chính xác</h3><button className="btn" onClick={onRefresh}>Kiểm tra lại độ phủ</button></div>
 {!coverage?<p>Lưu ma trận để kiểm tra kho hiện tại.</p>:<><p className={coverage.summary.can_generate?'ok-box':'warn-box'}>{coverage.summary.can_generate?'Đủ câu khớp chính xác — có thể sinh đề.':'Chưa thể sinh đề. Bổ sung đúng tiêu chí rồi kiểm tra lại.'}</p>{coverage.issue&&<p role="alert">{coverage.issue.message}</p>}<div className="practice-actions"><button className="btn" aria-pressed={perspective==='topic'} onClick={()=>setPerspective('topic')}>Độ phủ theo bài × mức</button><button className="btn" aria-pressed={perspective==='yccd'} onClick={()=>setPerspective('yccd')}>Độ phủ theo YCCĐ × mức</button></div><div className="table-scroll"><table aria-label={perspective==='topic'?'Bản đồ độ phủ bài theo mức':'Bản đồ độ phủ YCCĐ theo mức'}><thead><tr><th>{perspective==='topic'?'Bài học':'YCCĐ'} · cần / khớp</th>{levels.map(l=><th key={l}>{l}</th>)}</tr></thead><tbody>{[...new Set(coverage.cells.map(c=>(perspective==='topic'?c.topic_id:c.yccd_id)||0))].map(id=><tr key={id}><td>{coverage.cells.find(c=>((perspective==='topic'?c.topic_id:c.yccd_id)||0)===id)?.[perspective==='topic'?'topic_name':'yccd_label']||(perspective==='topic'?'Phạm vi nhiều bài':'Chưa gán')}</td>{levels.map((l,i)=><td key={l}>{coverage.cells.filter(c=>((perspective==='topic'?c.topic_id:c.yccd_id)||0)===id&&c.cognitive_level==='M'+(i+1)).map((c,j)=><div key={j} className={c.status==='EXACT_READY'?'ok-box':'warn-box'}>{labels[c.q_type]}: {c.need} / {c.exact_available}</div>)}</td>)}</tr>)}</tbody></table></div><small>Từng ô hiển thị theo dạng câu; không cộng trùng các tập câu giao nhau. Kiểm tra sinh đề xét đồng thời tất cả ô.</small><div className="table-scroll"><table><thead><tr><th>YCCĐ</th><th>Mức · Dạng</th><th>Cần</th><th>Khớp</th><th>Sau tránh lặp</th><th>Trạng thái · Hành động</th></tr></thead><tbody>{coverage.cells.map((c,i)=><tr key={c.cell_id||i}><td title={c.yccd_text}>{rowYccd(c)||'Chưa gán'}</td><td>{levels[Number(c.cognitive_level?.slice(1))-1]} · {labels[c.q_type]}</td><td>{c.need}</td><td>{c.exact_available}</td><td>{c.available_after_anti_repeat}</td><td><span className={'status-pill '+(c.status==='EXACT_READY'?'enabled':'disabled')}>{{EXACT_READY:'Đủ chính xác',SHORTAGE:'Thiếu câu',BLOCKED:'Chưa chuẩn hóa'}[c.status]}</span>{c.reason&&<small>{c.reason}</small>}{c.status!=='EXACT_READY'&&<Link to={'/practice/banks?'+new URLSearchParams({subject_id:c.subject_id,grade:c.grade,branch_id:c.branch_id||'',topic_id:c.topic_id||'',yccd_id:c.yccd_id||'',outcome_id:c.outcome_id||'',cognitive_level:c.cognitive_level,q_type:c.q_type})}>Bổ sung câu đúng ô →</Link>}</td></tr>)}</tbody></table></div></>}
 </section>;
}
export default function MatrixBuilder({subjects,matrix=null,onClose,onSaved}){
 const [form,setForm]=useState({...initial,subject_id:subjects.find(s=>s.code==='KHTN')?.id||subjects[0]?.id||''}),[selected,setSelected]=useState([]),[cells,setCells]=useState([]),[configs,setConfigs]=useState([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[id,setId]=useState(matrix?.id||null),[coverage,setCoverage]=useState(null),[accepted,setAccepted]=useState(false),[reason,setReason]=useState(''),[dirty,setDirty]=useState(true);
 const [contentScope,setContentScope]=useState(null),[resolvedScope,setResolvedScope]=useState(null),[mappingChange,setMappingChange]=useState(null),[scopeDecision,setScopeDecision]=useState(null);
 const {rows,error:catalogError,loading}=useCurriculum(form.subject_id,form.grade);
 useEffect(()=>{if(!matrix)return;api.get('/api/matrix/'+matrix.id).then(m=>{setForm({...initial,...m,total_score:Number(m.total_score)});setSelected(m.yccd_scope||[]);setContentScope(m.content_scope_v2||null);setResolvedScope(m.scope_snapshot||null);setMappingChange(m.mapping_change);setCells(m.cells.map(c=>({...c,score_per_question:Number(c.score_per_question)})));setConfigs(m.branch_config||[]);setAccepted(m.deviation_accepted);setReason(m.deviation_reason);setDirty(false);}).catch(e=>setError(e.message));},[matrix?.id]);
 useEffect(()=>{if(!form.subject_id&&subjects.length)setForm(f=>({...f,subject_id:subjects.find(s=>s.code==='KHTN')?.id||subjects[0].id}));},[subjects,form.subject_id]);
 const ratios=[1,2,3,4].map(n=>Number(form['ratio_m'+n])),actual=[1,2,3,4].map(n=>cells.filter(c=>c.cognitive_level==='M'+n).reduce((s,c)=>s+c.question_count*c.score_per_question,0)),total=actual.reduce((a,b)=>a+b,0);
 const ratioOk=ratios.reduce((a,b)=>a+b,0)===100,balanced=ratioOk&&actual.every((s,i)=>Math.abs(s-form.total_score*ratios[i]/100)<.00001),totalOk=Math.abs(total-form.total_score)<.00001;
 const invalidate=()=>{setDirty(true);setCoverage(null);setAccepted(false);};
 const change=(key,value)=>{setForm(f=>({...f,[key]:value}));invalidate();if(['subject_id','grade'].includes(key)){setSelected([]);setContentScope(null);setCells([]);setConfigs([]);}};
 const setScope=ids=>{setSelected(ids);setCells(cs=>cs.filter(c=>ids.includes(c.yccd_id)));setConfigs([]);invalidate();};
 const makeConfigs=()=>{
  const branches=[...new Map(rows.filter(y=>selected.includes(y.id)).map(y=>[y.branch_id||0,{branch_id:y.branch_id,branch_code:y.domain_code||'_all'}])).values()];
  const slots=Math.round(form.total_score*4),counts=branches.map((_,i)=>Math.floor(slots/branches.length)+(i<slots%branches.length?1:0));
  setConfigs(branches.map((b,i)=>({...b,score:counts[i]/4,tn:counts[i],ds:0,tln:0,gn:0,tl:0})));invalidate();
 };
 const updateCell=(i,patch)=>{setCells(cs=>cs.map((c,j)=>i===j?{...c,...patch}:c));invalidate();};
 async function distribute(keep=false){
  setBusy(true);setError('');try{
   if(!selected.length||!configs.length)throw Error('Chọn YCCĐ và thiết lập số câu theo phân môn trước');
   const result=await api.post('/api/matrix-balance/'+(keep?'redistribute':'auto'),{total_score:form.total_score,ratios,branch_configs:configs,cells:keep?cells.filter(c=>c.is_locked):[]});
   const counters={},out=[];
   for(const c of result.cells){
    if(c.is_locked&&c.yccd_id){out.push(c);continue;}
    const ys=rows.filter(y=>selected.includes(y.id)&&(y.branch_id||null)===(c.branch_id||null)).flatMap(y=>contentScope&&resolvedScope?resolvedScope.clauses.filter(cl=>cl.yccd_ids.includes(y.id)).map(cl=>({...y,topic_id:cl.topic_id})):y);if(!ys.length)throw Error('Phân môn chưa có YCCĐ đã chọn');
    for(let n=0;n<c.question_count;n++){const key=c.branch_id||0,index=counters[key]||0,y=ys[index%ys.length];counters[key]=index+1;const same=out.find(x=>!x.is_locked&&x.yccd_id===y.id&&(x.topic_id||null)===(y.topic_id||null)&&x.q_type===c.q_type&&x.cognitive_level===c.cognitive_level&&x.score_per_question===c.score_per_question&&c.q_type!=='essay');if(same)same.question_count++;else out.push({...c,topic_id:y.topic_id||null,outcome_id:y.outcome_id,yccd_id:y.id,question_count:1});}
   }
   setCells(out);invalidate();
  }catch(e){setError(e.message);}finally{setBusy(false);}
 }
 async function check(savedId=id){if(!savedId)return;try{setCoverage(await api.get('/api/matrix/'+savedId+'/coverage'));}catch(e){setError(e.message);}}
 async function save(){
  setBusy(true);setError('');try{
   const data={...form,subject_id:Number(form.subject_id),matrix_type:'BGD_2025',yccd_scope:selected,...(contentScope?.clauses.length?{content_scope_v2:contentScope,scope_decision:scopeDecision||undefined}:{}),branch_config:configs.length?configs:null,deviation_accepted:accepted,deviation_reason:reason,cells:cells.map((c,i)=>({...c,part_name:labels[c.q_type],order_index:i}))};
   const result=await(id?api.put('/api/matrix/'+id,data):api.post('/api/matrix',data));setId(result.id);setDirty(false);await check(result.id);onSaved?.(false);
  }catch(e){setError(e.message);}finally{setBusy(false);}
 }
 return <article className="matrix-v63"><header className="matrix-hero"><div><span className="eyebrow">MA TRẬN THEO CHUẨN ĐẦU RA</span><h2>{matrix?'Chỉnh sửa ma trận':'Xây dựng ma trận'}</h2><p>Chọn yêu cầu cần đạt → phân bổ điểm → kiểm tra câu khớp → sinh đề.</p></div><button className="btn" onClick={onClose}>Đóng</button></header>
 {(error||catalogError)&&<p role="alert" className="warn-box">{error||catalogError}</p>}
 <section className="matrix-section"><h3>1. Thông tin đề</h3><div className="matrix-fields"><label>Tên ma trận<input value={form.name} onChange={e=>change('name',e.target.value)} placeholder="Giữa kỳ I · KHTN 7"/></label><label>Môn học<select aria-label="Môn học" value={form.subject_id} onChange={e=>change('subject_id',Number(e.target.value))}>{subjects.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Khối<select aria-label="Khối" value={form.grade} onChange={e=>change('grade',Number(e.target.value))}>{[6,7,8,9,10,11,12].map(g=><option key={g}>{g}</option>)}</select></label><label>Thời gian (phút)<input type="number" min="5" value={form.duration_minutes} onChange={e=>change('duration_minutes',Number(e.target.value))}/></label></div></section>
 <section className="matrix-section"><h3>2. Nội dung theo bài học</h3><ContentScopePicker showCounts={false} value={contentScope||{version:2,subject_id:Number(form.subject_id),grade:Number(form.grade),clauses:[]}} onChange={scope=>{setContentScope(scope);setScopeDecision('refresh');setScope([]);}}/><button className="btn" disabled={!contentScope?.clauses.length} onClick={async()=>{try{const r=await api.post('/api/practice/content-scope/resolve-matrix',contentScope);setScope(r.yccd_ids);setResolvedScope(r);setScopeDecision('refresh');}catch(e){setError(e.message);}}}>Xác nhận phạm vi bài → YCCĐ</button>{mappingChange&&<div className="warn-box"><p>Liên kết Bài ↔ YCCĐ trong chương trình đã thay đổi kể từ lúc lưu ma trận này. Đề đã sinh trước đó không bị sửa.</p><button className="btn" aria-pressed={scopeDecision==='keep'} onClick={()=>setScopeDecision('keep')}>Giữ phạm vi như lúc lưu</button><button className="btn" aria-pressed={scopeDecision==='refresh'} onClick={()=>setScopeDecision('refresh')}>Cập nhật theo chương trình hiện tại</button><p>{scopeDecision==='keep'?'Sẽ giữ nguyên phạm vi YCCĐ như lúc lưu.':scopeDecision==='refresh'?'Khi lưu, phạm vi sẽ lấy theo liên kết hiện tại.':'Chưa chọn cách xử lý.'}</p></div>}<details><summary>Xem / chọn YCCĐ trực tiếp (nâng cao)</summary>{loading?<p>Đang tải chương trình…</p>:<CurriculumPicker rows={rows} selected={selected} onChange={ids=>{setContentScope(null);setScope(ids);}}/>}</details></section>
 <section className="matrix-section"><h3>3. Điểm và tỷ lệ mức độ</h3><div className="matrix-fields"><label>Tổng điểm<input type="number" min=".25" step=".25" value={form.total_score} onChange={e=>change('total_score',Number(e.target.value))}/></label>{ratios.map((v,i)=><label key={i}>{levels[i]} (%)<input type="number" min="0" max="100" value={v} onChange={e=>change('ratio_m'+(i+1),Number(e.target.value))}/></label>)}</div><p>Tổng tỷ lệ: {ratios.reduce((a,b)=>a+b,0)}% · Tỷ lệ tính theo điểm, không tính theo số câu.</p></section>
 <section className="matrix-section"><div className="section-heading"><h3>4. Số câu theo dạng</h3><button className="btn" disabled={!selected.length} onClick={makeConfigs}>Thiết lập từ phạm vi đã chọn</button></div><p>Gợi ý chia đều điểm giữa các phân môn đã chọn; anh có thể sửa. YCCĐ được chia đều số câu, không ưu tiên nơi có nhiều câu trong kho.</p><div className="table-scroll"><table><thead><tr><th>Phân môn</th>{['score','tn','ds','tln','gn','tl'].map(k=><th key={k}>{{score:'Điểm',tn:'TN × 0.25',ds:'ĐS × 0.5',tln:'TLN × 0.5',gn:'GN × 0.5',tl:'Số câu TL'}[k]}</th>)}</tr></thead><tbody>{configs.map((c,i)=><tr key={i}><td>{c.branch_code==='_all'?'Toàn môn':c.branch_code}</td>{['score','tn','ds','tln','gn','tl'].map(k=><td key={k}><input aria-label={c.branch_code+' '+k} type="number" min="0" step={k==='score'?'.25':'1'} value={c[k]||0} onChange={e=>{setConfigs(cs=>cs.map((x,j)=>j===i?{...x,[k]:Number(e.target.value)}:x));invalidate();}}/></td>)}</tr>)}</tbody></table></div><div className="practice-actions"><button className="btn primary" disabled={busy||!ratioOk||!configs.length} onClick={()=>distribute()}>Tự động phân bổ</button><button className="btn" disabled={busy||!cells.some(c=>c.is_locked)} onClick={()=>distribute(true)}>Tái phân bổ · giữ ô khóa</button></div></section>
 <section className="matrix-section"><h3>5. Ô ma trận và sai lệch</h3><div className="ratio-cards">{actual.map((v,i)=><div key={i}><strong>{levels[i]}</strong><span>{v.toFixed(2)} / {(form.total_score*ratios[i]/100).toFixed(2)} đ</span><small>Chênh {(v-form.total_score*ratios[i]/100).toFixed(2)} đ</small></div>)}</div><p className={totalOk&&balanced?'ok-box':'warn-box'}>Tổng {total.toFixed(2)} / {form.total_score} điểm · {balanced?'Khớp tỷ lệ':'Chưa khớp tỷ lệ'}</p>
 <div className="table-scroll"><table><thead><tr><th>Khóa</th><th>YCCĐ</th><th>Dạng</th><th>Mức</th><th>Số câu</th><th>Điểm/câu</th><th></th></tr></thead><tbody>{cells.map((c,i)=><tr key={i}><td><input aria-label={'Khóa ô '+(i+1)} type="checkbox" checked={!!c.is_locked} onChange={e=>updateCell(i,{is_locked:e.target.checked})}/></td><td><select aria-label={'YCCĐ ô '+(i+1)} value={c.yccd_id||''} onChange={e=>{const y=rows.find(y=>y.id===Number(e.target.value));updateCell(i,{yccd_id:y?.id,outcome_id:y?.outcome_id,branch_id:y?.branch_id});}}><option value="">Chọn YCCĐ</option>{rows.filter(y=>selected.includes(y.id)).map(y=><option key={y.id} value={y.id}>{rowYccd(y)} · {y.yccd_text.slice(0,75)}</option>)}</select></td><td><select value={c.q_type} onChange={e=>updateCell(i,{q_type:e.target.value})}>{Object.entries(labels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></td><td><select value={c.cognitive_level} onChange={e=>updateCell(i,{cognitive_level:e.target.value})}>{levels.map((l,j)=><option key={l} value={'M'+(j+1)}>{l}</option>)}</select></td>{['question_count','score_per_question'].map(k=><td key={k}><input aria-label={k+' '+(i+1)} type="number" min={k==='question_count'?1:.01} step={k==='question_count'?1:.25} value={c[k]} onChange={e=>updateCell(i,{[k]:Number(e.target.value)})}/></td>)}<td><button className="btn" onClick={()=>{setCells(cs=>cs.filter((_,j)=>j!==i));invalidate();}}>Bỏ</button></td></tr>)}</tbody></table></div>
 {cells.length>0&&!balanced&&totalOk&&<div className="deviation-box"><label><input type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)}/> Tôi đã xem mục tiêu/thực tế và chấp nhận sai lệch tỷ lệ này</label>{accepted&&<label>Lý do (được ghi nhật ký)<input value={reason} onChange={e=>setReason(e.target.value)} placeholder="Do số câu và bước điểm rời rạc…"/></label>}</div>}
 <button className="btn primary" disabled={busy||!form.name.trim()||!totalOk||!cells.length||cells.some(c=>!c.yccd_id)||!balanced&&(!accepted||reason.trim().length<5)} onClick={save}>{busy?'Đang xử lý…':'Lưu và kiểm tra độ phủ'}</button>{!dirty&&id&&<span role="status"> Đã lưu ma trận #{id}</span>}</section>
 <CoveragePanel coverage={coverage} onRefresh={()=>check()}/><section className="matrix-section"><h3>7. Kiểm tra trước khi sinh</h3>{selected.some(id=>!cells.some(c=>c.yccd_id===id))&&<p className="warn-box">Có YCCĐ đã tick nhưng chưa có câu trong ma trận. Tăng số câu hoặc điều chỉnh ô để phủ các YCCĐ cần kiểm tra.</p>}<p>{dirty?'Có thay đổi chưa lưu.':coverage?.summary.can_generate?'Phiên bản và điểm từng ô sẽ được khóa vào đề.':'Cần đủ câu chính xác ở mọi ô.'}</p><Link className={'btn '+(!dirty&&coverage?.summary.can_generate?'primary':'secondary')} aria-disabled={dirty||!coverage?.summary.can_generate} onClick={e=>{if(dirty||!coverage?.summary.can_generate)e.preventDefault();}} to={'/exams?matrix='+id}>Sinh đề từ ma trận này →</Link></section>
 </article>;
}
