import {useState} from 'react';
import {api} from '../../api/client.js';
import {base,useLoad,ErrorBox} from './shared.jsx';
export default function Configuration({section='curriculum'}){
 const staffCatalog=useLoad('/api/staff/catalog');
 const catalog=useLoad(base+'/catalog'),taxonomy=useLoad(base+'/taxonomy'),users=useLoad('/api/users'),banks=useLoad(base+'/banks'),permissions=useLoad(base+'/class-permissions');
 const[subject,setSubject]=useState(''),[profile,setProfile]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState(''),[version,setVersion]=useState({subject_id:'',name:''}),[node,setNode]=useState({version_id:'',parent_id:null,node_type:'topic',name:''}),[bank,setBank]=useState({name:'',kind:'school',department_id:null}),[member,setMember]=useState({bank_id:'',user_id:'',permission:'read'});
 let parsedProfile={};try{parsedProfile=JSON.parse(profile);}catch{/* Giữ văn bản JSON đang nhập. */}
 const patchProfile=patch=>{try{setProfile(JSON.stringify({...JSON.parse(profile),...patch},null,2));}catch{setError('Sửa JSON hợp lệ trước khi dùng tùy chọn');}};
 async function run(fn){setError('');setMessage('');try{await fn();setMessage('Đã lưu');}catch(e){setError(e.message);}}
 return <><ErrorBox error={error}/>{message&&<p role="status">{message}</p>}{section==='curriculum'&&<article className="practice-card"><h2>Cấu hình môn học</h2><p>Các nhãn mức độ và trường bắt buộc thay đổi theo môn. Nội dung GDPT 2018/Outcome/YCCĐ phải lấy từ nguồn nhà trường đã duyệt.</p><label>Môn<select value={subject} onChange={e=>{setSubject(e.target.value);setProfile(JSON.stringify(catalog.data.subjects.find(s=>s.id===Number(e.target.value))?.profile||{},null,2));}}><option value="">Chọn môn</option>{catalog.data?.subjects.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>{subject&&<><fieldset><legend>Quy trình duyệt câu hỏi</legend>{Object.entries({require_second_reviewer_for_content_change:'Cần người duyệt độc lập',allow_author_self_approve:'Cho tác giả tự duyệt (ngoại lệ)',allow_admin_self_approve:'Cho quản trị tự duyệt và ghi nhật ký ngoại lệ',require_review_for_curriculum_remap:'Thay đổi chuẩn cần rà soát',wrong_key_auto_quarantine:'Tạm loại câu bị báo sai đáp án khỏi bài mới'}).map(([key,label])=><label className="check-label" key={key}><input type="checkbox" checked={parsedProfile.question_review?.[key]??!['allow_author_self_approve'].includes(key)} onChange={e=>patchProfile({question_review:{...parsedProfile.question_review,[key]:e.target.checked}})}/>{label}</label>)}</fieldset><p>Bản nháp chỉ cần nội dung câu. Khi duyệt, hệ thống kiểm tra chuẩn đang hiệu lực và liên kết bài–YCCĐ; không thể bỏ các kiểm tra này bằng cấu hình.</p><details><summary>Nâng cao · Hồ sơ môn (JSON)</summary><label>Hồ sơ môn (JSON)<textarea rows={12} value={profile} onChange={e=>setProfile(e.target.value)}/></label></details><button className="btn" onClick={()=>run(()=>api.put(base+'/profiles/'+subject,JSON.parse(profile)))}>Lưu hồ sơ môn</button></>}
 <h3>Phiên bản chương trình</h3><label>Môn<select value={version.subject_id} onChange={e=>setVersion({...version,subject_id:Number(e.target.value)})}><option value="">Chọn môn</option>{catalog.data?.subjects.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Tên phiên bản<input value={version.name} onChange={e=>setVersion({...version,name:e.target.value})}/></label><button className="btn" onClick={()=>run(async()=>{await api.post(base+'/taxonomy/versions',version);taxonomy.reload();})}>Tạo phiên bản mới</button>
 <h3>Thêm chủ đề / chuyên đề bổ trợ</h3><p>Outcome và YCCĐ chuẩn được quản lý riêng tại <a href="/practice/curriculum">Chuẩn đầu ra</a>; các nút chuẩn cũ chỉ được đọc để giữ lịch sử.</p><label>Phiên bản<select value={node.version_id} onChange={e=>setNode({...node,version_id:Number(e.target.value),parent_id:null})}><option value="">Chọn phiên bản</option>{taxonomy.data?.versions.map(v=><option key={v.id} value={v.id}>{catalog.data?.subjects.find(s=>s.id===v.subject_id)?.name} · {v.name}</option>)}</select></label><label>Nút cha<select value={node.parent_id||''} onChange={e=>setNode({...node,parent_id:Number(e.target.value)||null})}><option value="">Nút gốc</option>{taxonomy.data?.nodes.filter(n=>n.version_id===node.version_id).map(n=><option key={n.id} value={n.id}>{n.node_type} · {n.name}</option>)}</select></label><label>Loại<select value={node.node_type} onChange={e=>setNode({...node,node_type:e.target.value})}>{Object.entries({topic:'Chủ đề',specialty:'Chuyên đề'}).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>Tên / nội dung<textarea value={node.name} onChange={e=>setNode({...node,name:e.target.value})}/></label><button className="btn" onClick={()=>run(async()=>{await api.post(base+'/taxonomy/nodes',node);taxonomy.reload();setNode({...node,name:''});})}>Thêm vào cấu trúc</button><p>Không sửa đè phiên bản đã dùng; tạo phiên bản mới để giữ lịch sử.</p></article>}
 {section==='banks'&&<article className="practice-card"><h2>Kho chung và phân quyền</h2><label>Tên kho<input value={bank.name} onChange={e=>setBank({...bank,name:e.target.value})}/></label><label>Loại kho<select value={bank.kind} onChange={e=>setBank({...bank,kind:e.target.value})}><option value="school">Kho trường</option><option value="department">Kho tổ</option></select></label>{bank.kind==='department'&&<label>Tổ chuyên môn<select value={bank.department_id||''} onChange={e=>setBank({...bank,department_id:Number(e.target.value)})}><option value="">Chọn tổ</option>{staffCatalog.data?.departments.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label>}<button className="btn" onClick={()=>run(async()=>{await api.post(base+'/banks',bank);banks.reload();})}>Tạo kho</button><p>Để cấp quyền kho có thời hạn và ghi lý do, mở tab Kho trong <a href="/admin/staff">hồ sơ nhân sự</a>.</p></article>}</>;
}
