import {useState} from 'react';
import {api} from '../../api/client.js';
import {base,useLoad,ErrorBox} from './shared.jsx';
export default function CurriculumAdmin(){
 const catalog=useLoad(base+'/catalog'),[subject,setSubject]=useState(''),[grade,setGrade]=useState(7),[data,setData]=useState(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[topic,setTopic]=useState(''),[selected,setSelected]=useState([]),[reason,setReason]=useState(''),[impact,setImpact]=useState(null),[change,setChange]=useState({action:'minor'}),[draft,setDraft]=useState({type:'outcome',code:'',title:'',text:'',outcome_id:'',domain_code:'',source_document:'',curriculum_version:'GDPT2018'});
 async function refresh(){setError('');try{setData(await api.get(base+'/curriculum/manage?'+new URLSearchParams({subject_id:subject,grade})));}catch(e){setError(e.message);}}
 async function run(fn){setError('');setMessage('');try{await fn();await refresh();setMessage('Đã lưu và ghi nhật ký.');}catch(e){setError(e.message);}}
 async function preview(type,id){try{const d=await api.get(base+'/curriculum/'+type+'/'+id+'/impact');setImpact({...d,type});setChange({action:'minor',code:d.entity.code||'',name:d.entity.name,title:d.entity.title,text:d.entity.text,source_document:d.entity.source_document||'',source_locator:d.entity.source_locator||'',reason:''});}catch(e){setError(e.message);}}
 const topics=catalog.data?.topics.filter(t=>t.subject_id===Number(subject)&&t.grade===grade)||[];
 return <section className="practice-page"><h1>Chuẩn đầu ra · Bài học — YCCĐ</h1><p>GDPT 2018: dùng chuẩn có nguồn. Quan hệ gợi ý chưa được sử dụng cho học sinh cho đến khi quản trị công bố.</p><ErrorBox error={error}/>{message&&<p role="status">{message}</p>}<div className="practice-grid"><label>Môn<select aria-label="Môn" value={subject} onChange={e=>{setSubject(e.target.value);setData(null);setTopic('');setSelected([]);}}><option value="">Chọn môn</option>{catalog.data?.subjects.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Khối<select aria-label="Khối" value={grade} onChange={e=>{setGrade(Number(e.target.value));setData(null);setTopic('');setSelected([]);}}>{[6,7,8,9,10,11,12].map(g=><option key={g}>{g}</option>)}</select></label></div><button className="btn primary" disabled={!subject} onClick={refresh}>Mở chương trình</button>
 {data&&<><section className="practice-card"><h2>Liên kết bài học với YCCĐ</h2><label>Bài học<select aria-label="Bài học" value={topic} onChange={e=>{setTopic(e.target.value);setSelected(data.maps.filter(m=>m.topic_id===Number(e.target.value)&&m.status==='ACTIVE').map(m=>m.yccd_id));}}><option value="">Chọn bài</option>{topics.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label>{topic&&<button className="btn" onClick={()=>preview('topic',Number(topic))}>Xem tác động / lưu trữ bài</button>}<p>Đang hoạt động: {data.maps.filter(m=>m.topic_id===Number(topic)&&m.status==='ACTIVE').length} · Ứng viên: {data.maps.filter(m=>m.topic_id===Number(topic)&&m.status==='CANDIDATE').length}</p>
 {data.outcomes.map(o=><details key={o.id}><summary>{o.code} · {o.title} — {o.status}</summary>{data.yccds.filter(y=>y.outcome_id===o.id).map(y=><label key={y.id} className="scope-v2-tick"><input type="checkbox" checked={selected.includes(y.id)} onChange={e=>setSelected(e.target.checked?[...selected,y.id]:selected.filter(id=>id!==y.id))}/><span>{y.code} — {y.text}<small>{y.status} · {y.source_locator||'Chưa có vị trí nguồn'}</small></span></label>)}</details>)}{data.can_propose&&<><label>Căn cứ / lý do<textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="Tài liệu chương trình, vị trí nguồn và căn cứ ghép bài…"/></label><div className="practice-actions">{['CANDIDATE',...(data.can_publish?['ACTIVE','RETIRED']:[])].map(status=><button key={status} className="btn" disabled={!topic||!selected.length||!reason.trim()} onClick={()=>run(()=>api.put(base+'/curriculum/topics/'+topic+'/mappings',{yccd_ids:selected,status,reason}))}>{{CANDIDATE:'Gửi đề xuất',ACTIVE:'Công bố liên kết đã tick',RETIRED:'Ngừng liên kết đã tick'}[status]}</button>)}</div></>}</section>
 <section className="practice-card"><h2>Quản lý chuẩn và tác động lịch sử</h2>{data.outcomes.map(o=><details key={o.id}><summary>{o.code} · {o.title} — {o.status}</summary><button className="btn" onClick={()=>preview('outcome',o.id)}>Xem tác động / sửa Outcome</button>{data.yccds.filter(y=>y.outcome_id===o.id).map(y=><p key={y.id}>{y.code} · {y.text} — {y.status} <button className="btn" onClick={()=>preview('yccd',y.id)}>Xem tác động / sửa YCCĐ</button></p>)}</details>)}</section>
 {data.can_propose&&<details className="practice-card"><summary>Thêm chuẩn dạng nháp</summary><label>Loại<select value={draft.type} onChange={e=>setDraft({...draft,type:e.target.value})}><option value="outcome">Outcome</option><option value="yccd">YCCĐ</option></select></label>{draft.type==='yccd'&&<label>Outcome cha<select value={draft.outcome_id} onChange={e=>setDraft({...draft,outcome_id:e.target.value})}><option value="">Chọn Outcome</option>{data.outcomes.map(o=><option key={o.id} value={o.id}>{o.code} · {o.title}</option>)}</select></label>}{['code',draft.type==='outcome'?'title':'text',...(draft.type==='outcome'?['domain_code','curriculum_version','source_document']:[]),'source_locator'].map(k=><label key={k}>{{code:'Mã chuẩn',title:'Nội dung Outcome',text:'Nội dung YCCĐ',domain_code:'Phân môn: L / H / S (để trống nếu toàn môn)',curriculum_version:'Phiên bản chương trình',source_document:'Tài liệu nguồn',source_locator:'Vị trí trong nguồn'}[k]}<input value={draft[k]||''} onChange={e=>setDraft({...draft,[k]:e.target.value})}/></label>)}<button className="btn" onClick={()=>run(()=>api.post(base+'/curriculum/'+draft.type,{...draft,subject_id:Number(subject),grade,outcome_id:Number(draft.outcome_id)}))}>Lưu nháp</button></details>}
 {impact&&<article className="practice-card curriculum-impact"><h2>Tác động trước thay đổi</h2><p>{impact.entity.code||impact.entity.name} — {impact.entity.text||impact.entity.title}</p><dl>{Object.entries(impact.counts).map(([k,n])=><div key={k}><dt>{{questions:'Câu hiện tại',versions:'Phiên bản lịch sử',mappings:'Liên kết bài học',draft_matrices:'Ma trận nháp',approved_matrices:'Ma trận duyệt / khóa',assignments:'Bài được giao',attempt_items:'Câu đã đưa vào lượt làm'}[k]}</dt><dd>{n}</dd></div>)}</dl><p>{impact.note}</p>{data.can_publish&&<><label>Thao tác<select value={change.action} onChange={e=>setChange({...change,action:e.target.value})}><option value="minor">Sửa nhãn / chính tả (không đổi nghĩa)</option><option value="activate">Kích hoạt</option><option value="retire">Ngừng sử dụng mới</option>{impact.type!=='topic'&&<option value="replace">Đổi nghĩa → tạo chuẩn thay thế dạng nháp</option>}{impact.type==='yccd'&&<option value="move">Chuyển sang Outcome khác bằng bản thay thế</option>}</select></label>{change.action==='move'&&<label>Outcome đích<select value={change.target_outcome_id||''} onChange={e=>setChange({...change,target_outcome_id:Number(e.target.value)})}><option value="">Chọn Outcome mới</option>{data.outcomes.filter(o=>o.id!==impact.entity.outcome_id).map(o=><option key={o.id} value={o.id}>{o.code} · {o.title}</option>)}</select></label>}{['minor','replace','move'].includes(change.action)&&<>{impact.type!=='topic'&&<label>Mã<input value={change.code||''} onChange={e=>setChange({...change,code:e.target.value})}/></label>}<label>Nội dung<textarea value={change[impact.type==='topic'?'name':impact.type==='outcome'?'title':'text']||''} onChange={e=>setChange({...change,[impact.type==='topic'?'name':impact.type==='outcome'?'title':'text']:e.target.value})}/></label></>}{impact.type!=='topic'&&<><label>Vị trí nguồn<input value={change.source_locator||''} onChange={e=>setChange({...change,source_locator:e.target.value})}/></label>{impact.type==='outcome'&&<label>Tài liệu nguồn<input value={change.source_document||''} onChange={e=>setChange({...change,source_document:e.target.value})}/></label>}</>}<label>Lý do<textarea value={change.reason||''} onChange={e=>setChange({...change,reason:e.target.value})}/></label><button className="btn primary" disabled={!change.reason?.trim()} onClick={()=>run(async()=>{await api.post(base+'/curriculum/'+impact.type+'/'+impact.entity.id+'/change',{...change,impact_fingerprint:impact.fingerprint});setImpact(null);})}>Xác nhận thay đổi đã xem tác động</button></>}<button className="btn" onClick={()=>setImpact(null)}>Đóng</button></article>}
 </>}
 </section>;
}
