import useAttemptFlags from './useAttemptFlags.js';
import {useAuth} from '../../hooks/useAuth.js';
import {useEffect,useLayoutEffect,useRef,useState} from 'react';import {Link,useNavigate,useParams} from 'react-router-dom';import {api} from '../../api/client.js';
import {base,useLoad,Pending,ErrorBox,types,masteryLabel,confidence,trends} from './shared.jsx';
function AnswerInput({q,value,onChange,disabled}){if(q.type==='multiple_choice')return <fieldset disabled={disabled}><legend>Chọn một đáp án</legend>{q.options.map(o=><label className={'answer-option '+(value===o.id?'selected':'')} key={o.id}><input type="radio" name="answer" checked={value===o.id} onChange={()=>onChange(o.id)}/><strong>{o.id}.</strong><Rich text={o.text}/></label>)}</fieldset>;
 if(q.type==='true_false')return <fieldset disabled={disabled}><legend>Chọn đúng hoặc sai cho từng ý</legend>{q.statements.map(s=><div className="statement" key={s.id}><Rich text={s.id+'. '+s.text}/>{[true,false].map(v=><label key={String(v)} className="check-label"><input type="radio" name={'statement-'+s.id} checked={value?.[s.id]===v} onChange={()=>onChange({...value,[s.id]:v})}/>{v?'Đúng':'Sai'}</label>)}</div>)}</fieldset>;
 if(q.type==='matching')return <fieldset disabled={disabled}><legend>Ghép mỗi ý với nội dung phù hợp</legend>{q.left?.map(l=><label key={l.id}><Rich text={l.id+'. '+l.text}/><select value={value?.[l.id]||''} onChange={e=>onChange({...value,[l.id]:e.target.value})}><option value="">Chọn nội dung</option>{q.right?.map(r=><option key={r.id} value={r.id}>{r.id}. {r.text}</option>)}</select></label>)}</fieldset>;
 if(q.type==='essay')return <label>Bài làm tự luận<textarea rows={6} disabled={disabled} value={value||''} onChange={e=>onChange(e.target.value)}/></label>;
 return <label>Câu trả lời<input disabled={disabled} value={typeof value==='object'?value?.value||'':value||''} onChange={e=>onChange(q.unit?{value:e.target.value,unit:q.unit}:e.target.value)}/>{q.unit&&<span>Đơn vị: {q.unit}</span>}</label>;
}
export default function Player(){const {id}=useParams(),nav=useNavigate(),load=useLoad(base+'/attempts/'+id);const[mapOpen,setMapOpen]=useState(()=>window.innerWidth>680),[index,setIndex]=useState(0),[value,setValue]=useState(null),[uncertain,setUncertain]=useState(false),[error,setError]=useState(''),[saving,setSaving]=useState(''),[busy,setBusy]=useState(false);const [reportNote,setReportNote]=useState(''),[reportState,setReportState]=useState('');const [confirmSubmit,setConfirmSubmit]=useState(false);const dialog=useRef(null);
 useEffect(()=>{if(confirmSubmit)dialog.current?.showModal();else dialog.current?.close();},[confirmSubmit]);
 const {user}=useAuth();const [navFilter,setNavFilter]=useState('all');const flags=useAttemptFlags(user.id,id,(itemId,flagged)=>load.setData(current=>current?{...current,items:current.items.map(q=>q.id===itemId?{...q,is_flagged:flagged}:q)}:current));
 const flagged=q=>flags.pending[q.id]?.flagged??q.is_flagged;
 useEffect(()=>{const itemId=new URLSearchParams(window.location.search).get('item');const found=load.data?.items.findIndex(q=>q.id===itemId);if(found>=0)setIndex(found);},[load.data?.id]);
 const timer=useRef(null),queue=useRef(Promise.resolve()),latest=useRef(null);const a=load.data,item=a?.items[index];
 useEffect(()=>{const media=window.matchMedia('(max-width:680px)'),update=()=>setMapOpen(!media.matches);media.addEventListener('change',update);return()=>media.removeEventListener('change',update);},[]);
 useLayoutEffect(()=>{if(item){setValue(item.response);setReportNote('');setReportState('');setUncertain(item.uncertain);latest.current={response:item.response,uncertain:item.uncertain,skipped:item.skipped,final:false};}return()=>clearTimeout(timer.current);},[item?.id,item?.is_final]);
 async function save(payload){const itemId=item.id;setSaving('Đang lưu…');const op=queue.current.catch(()=>{}).then(()=>api.put(`${base}/attempts/${id}/items/${itemId}`,payload));queue.current=op;try{const result=await op;load.setData(current=>current?.id===id?{...current,items:current.items.map(q=>q.id===itemId?{...q,response:payload.response,uncertain:payload.uncertain,skipped:payload.skipped,...(result.question?{is_final:true,question:result.question,result:result.result}:{})}:q)}:current);setSaving('Đã lưu');setError('');}catch(e){setSaving('Lưu chưa thành công');setError(e.message);throw e;}}
 function change(v,u=uncertain){setValue(v);setUncertain(u);latest.current={response:v,uncertain:u,skipped:false,final:false};clearTimeout(timer.current);timer.current=setTimeout(()=>save(latest.current).catch(()=>{}),400);}
 async function move(next){clearTimeout(timer.current);setBusy(true);try{if(!item.is_final&&a.status==='in_progress')await save(latest.current);await queue.current;setIndex(next);}catch{}finally{setBusy(false);}}
 async function finalize(){clearTimeout(timer.current);setBusy(true);try{await save({...latest.current,final:true});load.reload();}catch{}finally{setBusy(false);}}
 async function submit(){setConfirmSubmit(false);clearTimeout(timer.current);setBusy(true);try{if(!item.is_final)await save(latest.current);await queue.current;await api.post(`${base}/attempts/${id}/submit`,{});load.reload();}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function leave(e){e.preventDefault();clearTimeout(timer.current);setBusy(true);try{if(a.status==='in_progress'&&!item?.is_final)await save(latest.current);await queue.current;nav('/practice');}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function report(){setReportState('Đang gửi…');try{await api.post(`${base}/attempts/${id}/items/${item.id}/report`,{note:reportNote});setReportNote('');setReportState('Đã gửi giáo viên rà soát. Điểm bài này không thay đổi.');}catch(e){setReportState(e.message);}}
 async function retry(){try{const result=await api.post(`${base}/attempts/${id}/retry`,{});setIndex(0);nav('/practice/attempts/'+result.id);}catch(e){setError(e.message);}}
 if(!a)return <Pending data={a} error={load.error}/>;const completed=a.status==='completed';
 const hasAnswer=v=>v!==null&&v!==undefined&&(typeof v==='object'?Object.values(v).some(x=>x!==''&&x!==null):String(v).trim()!=='');
 const answered=a.items.filter(q=>hasAnswer(q.id===item?.id?value:q.response)).length;
 const marked=a.items.filter(q=>q.id===item?.id?uncertain:q.uncertain).length;const flagCount=a.items.filter(flagged).length;
 return <section className="practice-page player-page"><header className="learning-header"><div><Link className="back-link" to="/practice" onClick={leave}>← Trang học tập</Link><span className="eyebrow">MỖI CÂU HỎI, MỘT BƯỚC TIẾN</span><h1>{completed?'Kết quả lượt luyện':'Bài luyện của em'}</h1><p>{completed?'Nhìn lại kết quả và chọn nội dung em muốn củng cố.':'Cứ bình tĩnh suy nghĩ. Bài làm của em được lưu tự động.'}</p></div><span className="mode-badge">{a.mode==='practice'?'Luyện tập · phản hồi từng câu':'Thử sức · xem kết quả khi nộp'}</span></header><div className="practice-progress"><div><strong>{answered}/{a.items.length}</strong> câu đã trả lời <span>{flagCount} câu đánh dấu · {marked} câu chưa chắc</span></div><progress aria-label="Tiến độ trả lời" max={a.items.length} value={answered}/></div><ErrorBox error={error||load.error}/>{completed&&<div className="practice-card result-summary"><h2>{a.percentage==null?'Bài tự đối chiếu':`${Number(a.score).toFixed(2).replace(/\.00$/,'')}/${a.denominator} · ${Number(a.percentage).toFixed(0)}%`}</h2><p>{a.items.length-a.denominator} câu tự luận không tính vào điểm tự chấm · {Math.round(a.duration_seconds/60)} phút</p><p>Đây là kết quả tự luyện. Mức thành thạo và độ tin cậy đã cập nhật trong trang tiến độ.</p><div className="practice-actions"><Link className="btn" to={`/practice/new?subject=${a.config.subject_id}&topic=${a.config.topic_ids?.[0]||""}`}>Luyện tiếp chuyên đề</Link><button className="btn" onClick={retry}>Luyện lại câu sai/chưa chắc</button><Link to="/practice/portfolio?tab=mastery">Xem mức thành thạo</Link><Link to={`/practice/review/${id}`}>Xem lại toàn bộ bài</Link></div></div>}
 {completed&&a.mastery?.length>0&&<div className="practice-grid">{a.mastery.map(s=><article className="practice-card" key={s.topic_id+":"+s.cognitive_level}><h3>{s.topic_name} · M{s.cognitive_level}</h3><strong>{masteryLabel(s)}</strong><p>{s.unique_question_count} câu khác nhau · {s.completed_attempt_count} lượt hoàn thành</p>{s.confidence!=='LOW'&&<p>Mức thành thạo hiện tại: {s.mastery_score.toFixed(0)}%</p>}<p>Độ tin cậy: {confidence[s.confidence]} · {trends[s.trend]}</p><p>Lượt gần đây: {s.history.slice(-3).map(h=>h.score.toFixed(0)+"%").join(" → ")}</p></article>)}</div>}
 <div className="player-workspace"><details className="journey-panel" open={mapOpen} onToggle={e=>setMapOpen(e.currentTarget.open)}><summary>Hành trình bài luyện</summary><label>Lọc câu<select value={navFilter} onChange={e=>setNavFilter(e.target.value)}><option value="all">Tất cả</option><option value="unanswered">Chưa trả lời</option><option value="answered">Đã trả lời</option><option value="flagged">★ Đã đánh dấu</option></select></label><div className="question-navigation" aria-label="Danh sách câu">{a.items.map((q,i)=>(navFilter==='flagged'&&!flagged(q)||navFilter==='answered'&&!hasAnswer(q.response)||navFilter==='unanswered'&&hasAnswer(q.response))?null:<button key={q.id} disabled={busy} aria-current={i===index?'step':undefined} title={'Câu '+(i+1)+(flagged(q)?' · Đã đánh dấu':hasAnswer(q.response)?' · Đã trả lời':' · Chưa trả lời')} className={[i===index?'active':'',flagged(q)?'marked':hasAnswer(q.response)?'answered':''].join(' ')} onClick={()=>move(i)}>{i+1}{flagged(q)?' ★':hasAnswer(q.response)?' ✓':''}</button>)}</div><div className="journey-legend"><span>✓ Đã trả lời</span><span>★ Đã đánh dấu</span><span>○ Chưa trả lời</span></div><p>Em có thể chọn số câu để quay lại bất cứ lúc nào.</p><Link to="/practice" onClick={leave}>Lưu lại và về trang học tập</Link></details><div className="question-stage">
 {item&&<article className="practice-card question-card"><div className="question-kicker">Câu {index+1}/{a.items.length} · {types[item.question.type]} · M{item.question.cognitive_level}</div><button className="btn flag-toggle" style={{minHeight:44}} aria-pressed={!!flagged(item)} aria-label={flagged(item)?'Bỏ đánh dấu câu này':'Đánh dấu câu cần xem lại'} onClick={()=>flags.toggle(item.id,!flagged(item))}>{flagged(item)?'★ Đã đánh dấu':'☆ Đánh dấu xem lại'}</button><p role="status">{flags.status}{Object.keys(flags.pending).length>0&&<button className="btn" onClick={flags.retry}>Thử lưu lại cờ</button>}</p><div className="question-stem"><Rich text={item.question.stem}/></div>{item.question.image_url&&<img className="question-image" src={item.question.image_url} alt="Hình minh họa câu hỏi"/>}<AnswerInput key={item.id} q={item.question} value={value} onChange={change} disabled={item.is_final||completed||busy}/>
 {!completed&&!item.is_final&&<><label className="check-label"><input type="checkbox" checked={uncertain} onChange={e=>change(value,e.target.checked)}/>Em chưa chắc đáp án</label><div className="save-status" role="status" aria-live="polite">{saving||'Tự động lưu khi em chọn đáp án'}</div><div className="practice-actions">{a.mode==='practice'&&<button className="btn primary" onClick={finalize} disabled={busy}>Chốt đáp án</button>}<button className="btn" disabled={busy} onClick={async()=>{clearTimeout(timer.current);latest.current={response:null,uncertain:true,skipped:true,final:false};setValue(null);setUncertain(true);await save(latest.current).catch(()=>{});}}>Bỏ qua</button></div></>}
 {item.result&&<div className={'feedback '+(item.result.score===1?'correct':'review')}><h3>{item.result.score==null?'Tự đối chiếu':item.result.score===1?'Đúng':`Đạt ${Math.round(item.result.score*100)}% câu này`}</h3><p>Đáp án: {item.question.answer?.correct||item.question.answer?.aliases?.join(' / ')||(item.question.answer?.numeric!==undefined?String(item.question.answer.numeric):'')||item.question.answer?.reference||Object.entries(item.question.answer?.values||item.question.answer?.pairs||{}).map(([k,v])=>`${k}: ${typeof v==='boolean'?(v?'Đúng':'Sai'):v}`).join('; ')}</p>{item.result.details?.map(d=><p key={d.id}>{d.id}: {d.correct?'Đúng':'Chưa đúng'}</p>)}<details><summary>Xem lời giải</summary><Rich text={item.question.explanation||'Câu này chưa có lời giải bổ sung.'}/></details></div>}
 <details key={'report-'+item.id}><summary>Báo lỗi câu hỏi</summary><p>Nếu em thấy nội dung hoặc đáp án có vấn đề, hãy mô tả để giáo viên kiểm tra.</p><label>Nội dung phản ánh<textarea maxLength={2000} value={reportNote} onChange={e=>setReportNote(e.target.value)}/></label><button className="btn" disabled={!reportNote.trim()||reportState==='Đang gửi…'} onClick={report}>Gửi phản ánh</button><p role="status">{reportState}</p></details></article>}
 <div className="practice-actions player-footer"><button className="btn" disabled={busy||index===0} onClick={()=>move(index-1)}>Câu trước</button><button className="btn" disabled={busy||index===a.items.length-1} onClick={()=>move(index+1)}>Câu tiếp</button>{!completed&&<button className="btn primary" disabled={busy} onClick={()=>answered<a.items.length||marked||flagCount?setConfirmSubmit(true):submit()}>Nộp và xem kết quả</button>}</div></div></div><dialog ref={dialog} onCancel={()=>setConfirmSubmit(false)} aria-labelledby="submit-title" className="submit-dialog"><h2 id="submit-title">Em muốn nộp bài ngay?</h2><p>Còn {a.items.length-answered} câu chưa trả lời và {marked} câu chưa chắc; {flagCount} câu được đánh dấu xem lại. Em có thể quay lại xem trước khi nộp.</p><div className="practice-actions"><button className="btn" autoFocus onClick={()=>setConfirmSubmit(false)}>Quay lại xem</button><button className="btn primary" disabled={busy} onClick={submit}>Vẫn nộp bài</button></div></dialog></section>;
}
import {Rich} from './Rich.jsx';
