import {useState} from 'react';
import {api} from '../../api/client.js';
import {useAuth} from '../../hooks/useAuth.js';
import {base,useLoad,ErrorBox,types} from './shared.jsx';
import {Rich} from './Rich.jsx';
function Answer({answer={}}){return <div>{answer.correct&&<p>Đáp án: {answer.correct}</p>}{answer.aliases?.length>0&&<p>Chấp nhận: {answer.aliases.join(' / ')}</p>}{answer.numeric!==undefined&&<p>Giá trị: {answer.numeric} · Sai số: {answer.tolerance||0} ({answer.tolerance_mode||'tuyệt đối'})</p>}{answer.unit&&<p>Đơn vị: {answer.unit} {answer.unit_optional?'(không bắt buộc)':''}</p>}{Object.entries(answer.values||answer.pairs||{}).map(([k,v])=><p key={k}>{k} → {typeof v==='boolean'?(v?'Đúng':'Sai'):v}</p>)}{answer.reference&&<Rich text={answer.reference}/>}</div>;}
function VersionContent({version}){
 if(!version)return <p>Chưa có bản trước để so sánh.</p>;const q=version.content,c=q.curriculum_snapshot||{};
 return <div className="review-version"><h3>v{version.version_number} · {version.review_status}</h3><small>{new Date(version.created_at).toLocaleString('vi-VN')}</small><h4>Nội dung · {types[q.type||version.question_type]}</h4><Rich text={q.stem||q.stem_text}/>{q.image_url&&<img style={{maxWidth:'100%'}} src={q.image_url} alt="Hình của câu hỏi"/>}{(q.type==='true_false'?q.statements:q.options)?.map(o=><div key={o.id}><strong>{o.id}</strong><Rich text={o.text}/></div>)}{q.left&&<div className="practice-grid">{[q.left,q.right].map((col,i)=><div key={i}>{col?.map(o=><p key={o.id}>{o.id} · {o.text}</p>)}</div>)}</div>}<h4>Đáp án / quy tắc chấm</h4><Answer answer={q.answer}/><h4>Giải thích</h4><Rich text={q.explanation||'Chưa có lời giải'}/><h4>Phân loại tại phiên bản</h4><p>{c.topic_name||'Bài #'+(version.topic_id||'chưa gán')} · {c.outcome_code||''} · {c.yccd_code||''} · M{version.cognitive_level}</p><p>{c.yccd_text||'Phiên bản cũ chưa lưu nhãn curriculum tại thời điểm tạo'}</p></div>;
}
export default function QuestionReviewPanel({id,onClose,onChanged}){
 const {user}=useAuth(),load=useLoad(base+'/questions/'+id+'/compare'),quality=useLoad(base+'/questions/'+id+'/version-quality'),[error,setError]=useState(''),[reason,setReason]=useState(''),[checked,setChecked]=useState([]),[busy,setBusy]=useState(false),[report,setReport]=useState('MANUAL_REVIEW');
 async function act(fn){setBusy(true);setError('');try{await fn();load.reload();quality.reload();onChanged?.();setChecked([]);}catch(e){setError(e.message);}finally{setBusy(false);}}
 const d=load.data,canReview=user.capabilities?.['content.review'],canApprove=user.capabilities?.['content.approve'],canWrite=user.capabilities?.['content.write'];
 const checklist=['Nội dung / dữ kiện đúng, không mơ hồ','Đáp án và quy tắc chấm khớp dạng câu','Bài, YCCĐ và mức nhận thức phù hợp','Hình, công thức, bảng và lời giải hiển thị đủ'];
 return <article className="practice-card question-review-panel"><header className="section-heading"><h2>So sánh và duyệt phiên bản</h2><button className="btn" onClick={onClose}>Đóng</button></header><ErrorBox error={error||load.error}/>{d&&<>
 <p>{d.question.question_code} · Bản đang dùng: {d.versions.find(v=>v.id===d.question.active_version_id)?.version_number||'chưa có'} · {d.question.quarantined?'Đang cách ly khỏi lượt mới':'Không cách ly'}</p><p>Nhóm thay đổi: {{ASSESSMENT_CONTENT:'Nội dung đánh giá',CURRICULUM_METADATA:'Phân loại chương trình',NON_SEMANTIC:'Vận hành / không đổi nghĩa'}[d.diff.classification]} — {d.diff.reasons.join('; ')}</p>
 <label>Bản trước để đối chiếu<select value={d.before?.id||''} onChange={async e=>{try{load.setData(await api.get(base+'/questions/'+id+'/compare?before='+e.target.value));}catch(e){setError(e.message);}}}><option value="">Mặc định theo bản gốc</option>{d.versions.map(v=><option key={v.id} value={v.id}>v{v.version_number} · {v.review_status}</option>)}</select></label>
 <div className="review-diff-grid"><section><h3>Trước</h3><VersionContent version={d.before}/></section><section><h3>Sau / bản đang làm việc</h3><VersionContent version={d.after}/></section></div>
 <section><h3>Bằng chứng theo phiên bản</h3><p>Không cộng kết quả bản lỗi cũ vào bản đang dùng để kết luận chất lượng. Ít dữ liệu chỉ là tín hiệu, chưa phải kết luận.</p><div className="table-scroll"><table><thead><tr><th>Bản</th><th>Lượt câu</th><th>Học sinh</th><th>Điểm trung bình câu</th><th>Bỏ qua</th></tr></thead><tbody>{quality.data?.map(v=><tr key={v.id}><td>v{v.version_number}{v.is_active?' · đang dùng':''}</td><td>{v.responses}</td><td>{v.students}</td><td>{v.mean_score==null?'Chưa có':(100*Number(v.mean_score)).toFixed(0)+'%'}</td><td>{v.skipped}</td></tr>)}</tbody></table></div></section>
 {(canWrite||canReview||canApprove)&&<><label>Lý do / ghi chú thao tác<textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="Nêu căn cứ sửa, trả sửa hoặc kết luận…"/></label>{(canReview||canApprove)&&d.after.review_status==='PENDING_REVIEW'&&<fieldset><legend>Kiểm tra trước khi duyệt</legend>{checklist.map((c,i)=><label className="scope-v2-tick" key={c}><input type="checkbox" checked={checked.includes(i)} onChange={e=>setChecked(e.target.checked?[...checked,i]:checked.filter(n=>n!==i))}/>{c}</label>)}</fieldset>}<div className="practice-actions">
 {canWrite&&d.after.review_status==='DRAFT'&&<button className="btn" disabled={busy} onClick={()=>act(()=>api.post(base+'/questions/'+id+'/version-workflow',{action:'submit',reason}))}>Gửi bản nháp duyệt</button>}
 {(canReview||canApprove)&&d.after.review_status==='PENDING_REVIEW'&&<>{canApprove&&<button className="btn primary" disabled={busy||checked.length!==checklist.length} onClick={()=>act(()=>api.post(base+'/questions/'+id+'/version-workflow',{action:'approve',reason}))}>Duyệt phiên bản này</button>}{canReview&&[['request_changes','Yêu cầu sửa'],['reject','Từ chối bản này']].map(([action,label])=><button key={action} className="btn" disabled={busy||!reason.trim()} onClick={()=>act(()=>api.post(base+'/questions/'+id+'/version-workflow',{action,reason}))}>{label}</button>)}</>}
 {canWrite&&d.before&&<button className="btn" disabled={busy||!reason.trim()||d.after.review_status==='PENDING_REVIEW'} onClick={()=>act(()=>api.post(base+'/questions/'+id+'/restore',{version_id:d.before.id,reason}))}>Khôi phục nội dung bản trước thành nháp mới</button>}
 </div><details><summary>Gửi tín hiệu / mở hồ sơ rà soát</summary><label>Lý do<select value={report} onChange={e=>setReport(e.target.value)}>{Object.entries({MANUAL_REVIEW:'Rà soát thủ công',TEACHER_REPORT:'Giáo viên phản ánh',SUSPECTED_WRONG_KEY:'Nghi sai đáp án',AMBIGUOUS:'Câu mơ hồ',CURRICULUM_MISMATCH:'Sai bài / chuẩn',MEDIA_PROBLEM:'Lỗi hình / công thức',HIGH_SKIP_RATE:'Nhiều lượt bỏ qua',ABNORMAL_CORRECT_RATE:'Tỷ lệ đúng bất thường',DUPLICATE_SUSPECT:'Nghi trùng câu'}).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><button className="btn" disabled={busy||!reason.trim()} onClick={()=>act(()=>api.post(base+'/questions/'+id+'/review-cases',{reason_code:report,note:reason}))}>Mở / bổ sung bằng chứng rà soát</button></details></>}
 <details><summary>Lịch sử phiên bản · không đổi bài làm cũ</summary>{d.versions.map(v=><p key={v.id}>v{v.version_number} · {v.review_status} · {new Date(v.created_at).toLocaleString('vi-VN')}{v.based_on_version_id?' · có bản gốc':''}{v.restored_from_version_id?' · được khôi phục':''}</p>)}</details></>}
 </article>;
}
