import {useState} from 'react';
import {api} from '../../api/client.js';
import {base,useLoad,ErrorBox} from './shared.jsx';
import {useAuth} from '../../hooks/useAuth.js';
import QuestionReviewPanel from './QuestionReviewPanel.jsx';
export default function ReviewQueue(){
 const {user}=useAuth(),catalog=useLoad(base+'/catalog'),[filter,setFilter]=useState({status:'OPEN',subject_id:'',grade:'',severity:'',reason_code:''}),[selected,setSelected]=useState(null),[note,setNote]=useState(''),[resolution,setResolution]=useState('NO_ISSUE'),[assignee,setAssignee]=useState(''),[error,setError]=useState('');
 const [reviewers,setReviewers]=useState([]);
 const load=useLoad(base+'/review-cases?'+new URLSearchParams(filter));
 async function act(body){try{await api.post(base+'/review-cases/'+selected.id+'/resolve',body);load.reload();setSelected(null);}catch(e){setError(e.message);}}
 return <section className="review-cases"><h2>Hồ sơ rà soát câu hỏi</h2><p>Mỗi hồ sơ lưu nguyên nhân và bằng chứng. Duyệt/sửa không chấm lại bài cũ. Duyệt phiên bản không tự đóng hồ sơ — hồ sơ chỉ đóng qua kết luận bên dưới.</p><ErrorBox error={error||load.error}/><div className="practice-grid"><label>Môn<select value={filter.subject_id} onChange={e=>setFilter({...filter,subject_id:e.target.value})}><option value="">Môn được phân quyền</option>{catalog.data?.subjects.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>{[['grade','Khối',['','6','7','8','9','10','11','12']],['status','Trạng thái',['','OPEN','IN_REVIEW','RESOLVED','DISMISSED']],['severity','Ưu tiên',['','P0','P1','P2']],['reason_code','Nguyên nhân',['','STUDENT_REPORT','SUSPECTED_WRONG_KEY','CURRICULUM_MISMATCH','OUTCOME_RETIRED','YCCD_RETIRED','AMBIGUOUS','MEDIA_PROBLEM','HIGH_SKIP_RATE','ABNORMAL_CORRECT_RATE','DUPLICATE_SUSPECT','MANUAL_REVIEW','TEACHER_REPORT']]].map(([k,label,options])=><label key={k}>{label}<select value={filter[k]} onChange={e=>setFilter({...filter,[k]:e.target.value})}>{options.map(o=><option key={o} value={o}>{({STUDENT_REPORT:'Học sinh phản ánh',SUSPECTED_WRONG_KEY:'Nghi sai đáp án',CURRICULUM_MISMATCH:'Sai phân loại chương trình',OUTCOME_RETIRED:'Outcome ngừng sử dụng',YCCD_RETIRED:'YCCĐ ngừng sử dụng',AMBIGUOUS:'Câu mơ hồ',MEDIA_PROBLEM:'Lỗi hình / công thức',HIGH_SKIP_RATE:'Nhiều lượt bỏ qua',ABNORMAL_CORRECT_RATE:'Tỷ lệ đúng bất thường',DUPLICATE_SUSPECT:'Nghi trùng câu',MANUAL_REVIEW:'Rà soát thủ công',TEACHER_REPORT:'Giáo viên phản ánh',OPEN:'Mới mở',IN_REVIEW:'Đang rà soát',RESOLVED:'Đã xử lý',DISMISSED:'Không có lỗi'})[o]||o||'Tất cả'}</option>)}</select></label>)}</div>
 {!load.data?.length&&<p>Không có hồ sơ trong bộ lọc này.</p>}{load.data?.map(c=><article key={c.id} className="practice-card"><h2>{c.severity} · {c.question_code}</h2><p>{c.reason_code} · {c.status} · {Number(c.age_days).toFixed(1)} ngày · {c.opened_by_name}</p><p>{c.stem_text}</p><button className="btn" onClick={async()=>{setSelected(c);setNote('');setAssignee('');setReviewers([]);if(user.capabilities?.content_review)try{setReviewers(await api.get(base+'/questions/'+c.question_id+'/reviewers'));}catch(e){setError(e.message);}}}>Mở hồ sơ và so sánh</button></article>)}
 {selected&&<article className="practice-card"><h2>Hồ sơ #{selected.id}</h2>{selected.evidence_snapshot.map((e,i)=><blockquote key={i}>{e.note}<small>{new Date(e.at).toLocaleString('vi-VN')}</small></blockquote>)}<QuestionReviewPanel id={selected.question_id} onClose={()=>setSelected(null)} onChanged={load.reload}/>{user.capabilities?.content_review&&['OPEN','IN_REVIEW'].includes(selected.status)&&<><label>Người rà soát<select value={assignee} onChange={e=>setAssignee(e.target.value)}><option value="">Chọn nhân sự được phân quyền</option>{reviewers.map(u=><option key={u.id} value={u.id}>{u.full_name}</option>)}</select></label><button className="btn" disabled={!assignee} onClick={()=>act({action:'assign',assigned_to:Number(assignee)})}>Phân công rà soát</button><label>Kết luận<select value={resolution} onChange={e=>setResolution(e.target.value)}>{Object.entries({NO_ISSUE:'Không có lỗi — giữ phiên bản',METADATA_CORRECTED:'Đã sửa phân loại',NEW_VERSION_APPROVED:'Phiên bản mới đã duyệt',QUESTION_RETIRED:'Ngừng dùng câu mới',DEFERRED:'Tạm hoãn — giữ hồ sơ mở'}).map(([k,l])=><option key={k} value={k}>{l}</option>)}</select></label><label>Căn cứ kết luận<textarea value={note} onChange={e=>setNote(e.target.value)}/></label><button className="btn primary" disabled={!note.trim()} onClick={()=>act({resolution_type:resolution,note})}>Ghi kết luận</button></>}</article>}
 </section>;
}
