import {useState} from 'react';
import {api,uploadFile} from '../../api/client.js';
import {base,ErrorBox} from './shared.jsx';
const labels={NEW:'Thêm mới',UPDATE:'Cập nhật',UNCHANGED:'Không đổi',CONFLICT:'Xung đột',ERROR:'Lỗi'};
export default function RosterImport({onComplete}){
 const [file,setFile]=useState(null),[preview,setPreview]=useState(null),[result,setResult]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function run(confirm=false){setBusy(true);setError('');try{if(confirm){setResult(await api.post(base+'/roster/confirm',{token:preview.token}));setPreview(null);setFile(null);onComplete?.();}else{setPreview(await uploadFile(base+'/roster/preview',file));setResult(null);}}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <article className="practice-card roster-import"><h2>Nhập danh sách học sinh</h2><p>Excel gồm student_code, full_name, class_name, grade, school_year. Xem trước không thay đổi dữ liệu; chỉ lưu sau khi xác nhận.</p><ErrorBox error={error}/><label>Danh sách học sinh Excel<input type="file" accept=".xlsx" disabled={busy} onChange={e=>{setFile(e.target.files[0]);setPreview(null);setResult(null);}}/></label><button className="btn" disabled={!file||busy} onClick={()=>run()}>Phân tích và xem trước</button>
 {preview&&<><p>{Object.entries(labels).map(([key,label])=>label+': '+preview.rows.filter(r=>r.status===key).length).join(' · ')}</p><div className="table-scroll"><table><thead><tr><th>Dòng</th><th>Mã / Họ tên</th><th>Lớp · Năm học</th><th>Kết quả</th></tr></thead><tbody>{preview.rows.map(r=><tr key={r.row}><td>{r.row}</td><td>{r.student_code} · {r.full_name}</td><td>{r.class_name} · {r.school_year}</td><td>{labels[r.status]} — {r.message}</td></tr>)}</tbody></table></div><p>Bản xem trước có hiệu lực 15 phút. Cần sửa hết dòng lỗi/xung đột rồi tải lại.</p><button className="btn primary" disabled={busy||!preview.can_confirm} onClick={()=>run(true)}>{busy?'Đang lưu…':'Xác nhận nhập danh sách'}</button><button className="btn" disabled={busy} onClick={()=>setPreview(null)}>Hủy xem trước</button></>}
 {result&&<div role="status"><h3>Đã lưu {result.students.length} học sinh</h3><p>Giao mật khẩu tạm riêng cho từng học sinh, không chia sẻ công khai.</p>{result.students.map(s=><p key={s.student_code}>{s.student_code} · {s.full_name}: <code>{s.temporary_password||'Giữ nguyên mật khẩu'}</code></p>)}<button className="btn" onClick={()=>setResult(null)}>Ẩn thông tin mật khẩu</button></div>}</article>;
}
