import {useEffect,useRef,useState} from 'react';import {useNavigate,useSearchParams} from 'react-router-dom';
import {api} from '../../api/client.js';
import {base,useLoad,Pending,ErrorBox,initialConfig} from './shared.jsx';
// Chia số câu theo mức — bản sao đúng allocate() của máy chủ (services/practice/selection.js) để gợi ý sửa chắc chắn hợp lệ.
function allocate(count,percent){const raw=percent.map(x=>count*x/100),out=raw.map(Math.floor);const ranked=raw.map((v,i)=>({i,f:v-out[i]})).sort((a,b)=>b.f-a.f||a.i-b.i);const missing=count-out.reduce((a,b)=>a+b,0);for(let j=0;j<missing;j++)out[ranked[j].i]++;return out;}
const fits=(count,percent,avail)=>allocate(count,percent).every((n,i)=>n<=avail[i]);
// Số câu lớn nhất vẫn đủ với tỉ lệ hiện tại.
function fewerCount(config,avail){for(let n=config.count-1;n>0;n--)if(fits(n,config.percent,avail))return n;return 0;}
// Giữ số câu, chia lại mức: mức thiếu lấy tối đa số đang có, phần hụt dồn sang mức gần nhất còn dư.
function rebalance(config,avail){if(avail.reduce((a,b)=>a+b,0)<config.count)return null;const want=allocate(config.count,config.percent),got=want.map((n,i)=>Math.min(n,avail[i]));let left=config.count-got.reduce((a,b)=>a+b,0);const short=want.map((n,i)=>n>avail[i]?i:-1).filter(i=>i>=0);for(const s of short.length?short:[0])for(const i of [0,1,2,3].sort((a,b)=>Math.abs(a-s)-Math.abs(b-s)||a-b)){const add=Math.min(left,avail[i]-got[i]);got[i]+=add;left-=add;}if(left>0)return null;const percent=got.map(n=>n*100/config.count);return fits(config.count,percent,avail)?percent:null;}

export function PracticeBuilder(){const nav=useNavigate(),[params]=useSearchParams();const catalog=useLoad(base+'/catalog'),settings=useLoad(base+'/settings');const [config,setConfig]=useState({...initialConfig,grade:Number(params.get('grade'))||9,subject_id:Number(params.get('subject_id')||params.get('subject'))||0,selection_mode:params.get('yccd_id')?'yccd':'topic',yccd_keys:params.get('yccd_id')?[JSON.stringify(['master',Number(params.get('yccd_id'))])]:[],topic_ids:params.get('topic')?[Number(params.get('topic'))]:[],percent:params.get('level')?[1,2,3,4].map(n=>n===Number(params.get('level'))?100:0):[25,25,25,25]});const revision=useRef(0);const [preview,setPreview]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[checking,setChecking]=useState(false);
 const ready=!!((config.content_scope_v2?.clauses?.length||(config.selection_mode==='yccd'?config.yccd_keys?.length:config.topic_ids.length))&&config.types.length&&config.subject_id&&config.percent.reduce((a,b)=>a+b,0)===100);
 // Tự kiểm số câu sau khi học sinh ngừng chỉnh 0,4 giây; kết quả cũ bị bỏ nếu cấu hình đã đổi.
 useEffect(()=>{if(!ready){setPreview(null);setChecking(false);return;}let live=true;setChecking(true);const t=setTimeout(()=>{api.post(base+'/availability',config).then(r=>{if(live){setPreview(r);setError('');}}).catch(e=>{if(live)setError(e.message);}).finally(()=>{if(live)setChecking(false);});},400);return()=>{live=false;clearTimeout(t);};},[config,ready]);
 const change=v=>{revision.current++;setConfig(v);setPreview(null);};
 async function create(){setBusy(true);setError('');try{const a=await api.post(base+'/attempts',config);nav('/practice/attempts/'+a.id);}catch(e){setError(e.message);}finally{setBusy(false);}}
 const avail=preview?.availability.map(r=>r.available),short=preview?.shortages.length>0,fewer=short?fewerCount(config,avail):0,balanced=short?rebalance(config,avail):null,total=avail?avail.reduce((a,b)=>a+b,0):0,few=Math.min(total,config.count),combo=short&&!fewer&&!balanced&&few>0?rebalance({...config,count:few},avail):null;
 useEffect(()=>{const topic=catalog.data?.topics.find(t=>t.id===Number(params.get('topic')));if(topic)setConfig(c=>({...c,grade:topic.grade,subject_id:topic.subject_id}));},[catalog.data]);
 useEffect(()=>{const profile=catalog.data?.subjects.find(s=>s.id===config.subject_id)?.profile;if(profile)setConfig(c=>({...c,types:profile.allowed_types||initialConfig.types}));},[config.subject_id,catalog.data]);
 return <section className="practice-page"><h1>Tự chọn bài luyện</h1><p>Chọn nội dung em muốn củng cố. Tự luận chỉ dùng để tự đối chiếu.</p><Pending data={catalog.data} error={catalog.error}/><ErrorBox error={error}/><ConfigFields simple value={config} onChange={change} catalog={catalog.data} settings={settings.data}/><div className="practice-card availability-status" role="status" aria-live="polite">{!ready?<p>Chọn nội dung em muốn luyện để bắt đầu.</p>:checking||!preview?<p>Đang kiểm tra số câu phù hợp…</p>:!short?<p>✓ Có đủ câu phù hợp · {config.count} câu</p>:<><p><strong>Chưa đủ câu.</strong> {preview.shortages.map(r=>`M${r.level}: cần ${r.required}, hiện có ${r.available}`).join(' · ')}</p><p>Em có thể:</p><div className="practice-actions">{fewer>0&&<button type="button" className="btn" onClick={()=>change({...config,count:fewer})}>Giảm còn {fewer} câu</button>}{balanced&&<button type="button" className="btn" onClick={()=>change({...config,percent:balanced})}>Giữ {config.count} câu, tự chia lại mức</button>}{combo&&<button type="button" className="btn" onClick={()=>change({...config,count:few,percent:combo})}>Luyện {few} câu hiện có</button>}<button type="button" className="btn" onClick={()=>document.querySelector('[aria-label="Tìm bài / chuyên đề"]')?.focus()}>Chọn thêm nội dung</button></div></>}</div><div className="practice-actions"><button className="btn primary" disabled={busy||checking||!preview||short} onClick={create}>{busy?'Đang tạo bài…':'Bắt đầu luyện'}</button></div></section>;
}
import {ConfigFields} from './ConfigFields.jsx';
