import {useEffect,useRef,useState} from 'react';import {useNavigate,useSearchParams} from 'react-router-dom';
import {api} from '../../api/client.js';
import {base,useLoad,Pending,ErrorBox,initialConfig} from './shared.jsx';
export function PracticeBuilder(){const nav=useNavigate(),[params]=useSearchParams();const catalog=useLoad(base+'/catalog'),settings=useLoad(base+'/settings');const [config,setConfig]=useState({...initialConfig,grade:Number(params.get('grade'))||9,subject_id:Number(params.get('subject_id')||params.get('subject'))||0,selection_mode:params.get('yccd_id')?'yccd':'topic',yccd_keys:params.get('yccd_id')?[JSON.stringify(['master',Number(params.get('yccd_id'))])]:[],topic_ids:params.get('topic')?[Number(params.get('topic'))]:[],percent:params.get('level')?[1,2,3,4].map(n=>n===Number(params.get('level'))?100:0):[25,25,25,25]});const revision=useRef(0);const [preview,setPreview]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function run(create){const ticket=revision.current;setBusy(true);setError('');try{if(create){const a=await api.post(base+'/attempts',config);nav('/practice/attempts/'+a.id);}else {const result=await api.post(base+'/availability',config);if(ticket===revision.current)setPreview(result);}}catch(e){setError(e.message);}finally{setBusy(false);}}
 useEffect(()=>{const topic=catalog.data?.topics.find(t=>t.id===Number(params.get('topic')));if(topic)setConfig(c=>({...c,grade:topic.grade,subject_id:topic.subject_id}));},[catalog.data]);
 useEffect(()=>{const profile=catalog.data?.subjects.find(s=>s.id===config.subject_id)?.profile;if(profile)setConfig(c=>({...c,types:profile.allowed_types||initialConfig.types}));},[config.subject_id,catalog.data]);
 return <section className="practice-page"><h1>Tự chọn bài luyện</h1><p>Chọn nội dung em muốn củng cố. Tự luận chỉ dùng để tự đối chiếu.</p><Pending data={catalog.data} error={catalog.error}/><ErrorBox error={error}/><ConfigFields simple value={config} onChange={v=>{revision.current++;setConfig(v);setPreview(null);}} catalog={catalog.data} settings={settings.data}/><div className="practice-actions"><button className="btn" disabled={busy||!(config.content_scope_v2?.clauses?.length||(config.selection_mode==='yccd'?config.yccd_keys?.length:config.topic_ids.length))||!config.types.length||!config.subject_id||config.percent.reduce((a,b)=>a+b,0)!==100} onClick={()=>run(false)}>Kiểm tra số câu trong kho</button><button className="btn primary" disabled={busy||!preview||preview.shortages.length>0} onClick={()=>run(true)}>Tạo bài luyện</button></div>{preview&&<div className="practice-card">{preview.availability.map(r=><p key={r.level}>M{r.level}: cần {r.required} / có {r.available} câu {r.available<r.required?'— chưa đủ':''}</p>)}{preview.shortages.length>0&&<p>Hãy giảm số câu hoặc chủ động sửa tỉ lệ các mức rồi kiểm tra lại.</p>}</div>}</section>;
}
import {ConfigFields} from './ConfigFields.jsx';
