import {useEffect,useState} from 'react';import {Link} from 'react-router-dom';import {api,downloadFile} from '../../api/client.js';import {useAuth} from '../../hooks/useAuth.js';
import {CurriculumField} from '../../components/CurriculumPicker.jsx';
import {base,useLoad,ErrorBox,types} from './shared.jsx';import RosterImport from './RosterImport.jsx';
export function TeacherDashboard(){
 const {user}=useAuth(),classes=useLoad(base+'/classes'),catalog=useLoad(base+'/catalog');
 const[id,setId]=useState(''),[detail,setDetail]=useState(null),[error,setError]=useState(''),[filter,setFilter]=useState({subject_id:'',topic_id:'',level:'',from:'',to:''}),[status,setStatus]=useState('');
 useEffect(()=>{let active=true;setDetail(null);if(id)api.get(base+'/classes/'+id+'/dashboard?'+new URLSearchParams(filter)).then(d=>{if(active)setDetail(d);}).catch(e=>setError(e.message));return()=>{active=false;};},[id,filter]);
 const displayed=detail?.students.filter(s=>!status||status==='new'&&!s.completed_attempts||status==='low'&&s.low_levels>0||status==='confidence'&&s.confidence==='LOW'||status==='down'&&s.declining_levels>0||status==='inactive'&&s.inactive_7d||status==='pending'&&s.pending_assignments>0);
 return <section className="practice-page"><h1>Tiến độ lớp học</h1><ErrorBox error={error||classes.error}/><label>Năm học · Lớp<select value={id} onChange={e=>{setId(e.target.value);}}><option value="">Chọn lớp được phân quyền</option>{classes.data?.map(c=><option key={c.id} value={c.id}>{c.school_year} · {c.name}</option>)}</select></label>
 <details className="class-filters"><summary>Lọc môn, chuyên đề và thời gian</summary><div className="practice-grid"><label>Môn<select value={filter.subject_id} onChange={e=>setFilter({...filter,subject_id:e.target.value,topic_id:''})}><option value="">Các môn được giao</option>{catalog.data?.subjects.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Chuyên đề<select value={filter.topic_id} onChange={e=>setFilter({...filter,topic_id:e.target.value})}><option value="">Tất cả chuyên đề</option>{catalog.data?.topics.filter(t=>!filter.subject_id||t.subject_id===Number(filter.subject_id)).map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label>Mức<select value={filter.level} onChange={e=>setFilter({...filter,level:e.target.value})}><option value="">Tất cả mức</option>{[1,2,3,4].map(n=><option key={n} value={n}>M{n} · {catalog.data?.subjects.find(s=>s.id===Number(filter.subject_id))?.profile?.level_labels?.[n-1]||['Nhận biết','Thông hiểu','Vận dụng','Vận dụng cao'][n-1]}</option>)}</select></label>{['from','to'].map(key=><label key={key}>{key==='from'?'Từ ngày':'Đến ngày'}<input type="date" value={filter[key]} onChange={e=>setFilter({...filter,[key]:e.target.value})}/></label>)}<label>Nhóm cần theo dõi<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Tất cả</option><option value="new">Chưa bắt đầu trong khoảng chọn</option><option value="low">Cần củng cố · đủ bằng chứng</option><option value="inactive">Chưa luyện trong 7 ngày</option><option value="pending">Còn bài giao chưa hoàn thành</option><option value="confidence">Độ tin cậy thấp</option><option value="down">Đang giảm</option></select></label></div></details>
 {detail&&<><div className="portfolio-stats decision-stats">{[[detail.summary.inactive_7d,"Chưa luyện 7 ngày"],[detail.summary.reinforcement,"Cần củng cố"],[detail.summary.declining,"Xu hướng giảm"],[detail.summary.pending_assignments,"Chưa hoàn thành bài giao"]].map(([n,label])=><article key={label}><strong>{n}</strong><span>{label}</span></article>)}</div><p>{detail.summary.total_students} học sinh · Chưa luyện 7 ngày và bài giao xét hiện tại. Mastery là trạng thái tích lũy; bộ lọc ngày áp dụng lượt luyện. Chọn tên học sinh để xem hồ sơ.</p><div className="table-scroll teacher-class-table"><table><thead><tr><th>Học sinh</th><th>Lượt hoàn thành</th><th>Gần nhất</th><th>Mastery</th><th>Thay đổi</th><th>Độ tin cậy</th></tr></thead><tbody>{displayed.map(s=><tr key={s.id}><td><Link to={`/practice/students/${s.id}/portfolio`}>{s.full_name} · {s.student_code}</Link></td><td>{s.completed_attempts}</td><td>{s.last_practice?new Date(s.last_practice).toLocaleDateString('vi-VN'):'Chưa luyện'}</td><td>{s.mastery===null||s.confidence==='LOW'?'Chưa đủ dữ liệu':s.mastery.toFixed(0)+'%'}</td><td>{s.mastery_gain===null||s.confidence==='LOW'?'Cần thêm dữ liệu':s.mastery_gain.toFixed(1)+' điểm %'}</td><td>{{LOW:'Thấp',MEDIUM:'Trung bình',HIGH:'Cao'}[s.confidence]||'—'}</td></tr>)}</tbody></table></div></>}
 {user.capabilities?.student_accounts&&<RosterImport/>}
 </section>;
}
export function Metadata({q,onChange,catalog}){return <><div className="practice-grid"><label>Môn<select value={q.subject_id||''} onChange={e=>onChange({...q,subject_id:Number(e.target.value)||null,topic_id:null,yccd_id:null,outcome_id:null,branch_id:null})}><option value="">Chưa gán</option>{catalog?.subjects.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Khối<input type="number" min="6" max="12" value={q.grade??''} onChange={e=>onChange({...q,grade:Number(e.target.value)||null,topic_id:null,yccd_id:null,outcome_id:null,branch_id:null})}/></label><label>Bài (tùy theo hồ sơ môn)<select value={q.topic_id||''} onChange={e=>onChange({...q,topic_id:Number(e.target.value)||null,yccd_id:null,outcome_id:null})}><option value="">Chưa gán</option>{catalog?.topics.filter(t=>t.subject_id===q.subject_id&&t.grade===q.grade).map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label>Mức độ<select value={q.cognitive_level||''} onChange={e=>onChange({...q,cognitive_level:Number(e.target.value)||null})}><option value="">Chưa xác định</option>{[1,2,3,4].map(n=><option key={n} value={n}>{['NB','TH','VD','VDC'][n-1]}</option>)}</select></label></div><CurriculumField q={q} onChange={onChange}/></>;}
export function QuestionEditor({value,onChange,catalog}){const q=value;const set=(key,val)=>onChange({...q,[key]:val});return <><Metadata q={q} onChange={onChange} catalog={catalog}/><label>Mã hiển thị<input value={q.display_code||''} onChange={e=>set('display_code',e.target.value)}/></label><label>Dạng câu<select value={q.type||''} onChange={e=>onChange({...q,type:e.target.value,answer:undefined,answer_key:undefined})}><option value="">Chưa xác định — lưu bản nháp</option>{Object.entries(types).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>Nội dung<textarea rows={4} value={q.stem||''} onChange={e=>set('stem',e.target.value)}/></label><Rich text={q.stem}/>{!q.type&&<label>Đáp án gốc<input value={q.answer_key||''} onChange={e=>set('answer_key',e.target.value)}/></label>}<button className="btn" onClick={async()=>{try{onChange(await api.post(base+'/metadata/suggest',q));}catch(e){alert(e.message);}}}>Gợi ý phân loại trong phạm vi</button>{q.metadata_suggestions&&<div className="warn-box"><p>Gợi ý cần xác nhận, không tự thay metadata đã nhập.</p>{q.metadata_suggestions.type&&<p>Dạng: {types[q.metadata_suggestions.type.value]} · {q.metadata_suggestions.type.confidence}% · {q.metadata_suggestions.type.reason} <button className="btn" onClick={()=>onChange({...q,type:q.metadata_suggestions.type.value,answer:undefined})}>Áp dụng dạng</button></p>}{q.metadata_suggestions.yccds?.map(y=><p key={y.id}>{y.label||y.code} · {y.confidence}% — {y.text}<small>{y.reason}</small><button className="btn" onClick={()=>onChange({...q,yccd_id:y.id,outcome_id:y.outcome_id,branch_id:y.branch_id})}>Chọn YCCĐ này</button></p>)}<p>Mức nhận thức cần giáo viên xác nhận từ quá trình giải; không suy chỉ từ động từ.</p></div>}{q.type==='multiple_choice'&&[0,1,2,3].map(i=><label key={i}>Phương án {String.fromCharCode(65+i)}<input value={q.options?.[i]?.text||''} onChange={e=>set('options',[0,1,2,3].map(j=>({id:String.fromCharCode(65+j),text:j===i?e.target.value:q.options?.[j]?.text||''})))}/></label>)}{q.type==='multiple_choice'&&<label>Đáp án<select value={q.answer?.correct||''} onChange={e=>set('answer',{correct:e.target.value})}><option value="">Chọn đáp án</option>{['A','B','C','D'].map(k=><option key={k}>{k}</option>)}</select></label>}
 {q.type==='true_false'&&['a','b','c','d'].map((id,i)=><div key={id}><label>Nhận định {id}<textarea value={q.statements?.[i]?.text||''} onChange={e=>set('statements',['a','b','c','d'].map((k,j)=>({id:k,text:j===i?e.target.value:q.statements?.[j]?.text||''})))}/></label><label>Mức nhận thức ý {id}<select value={q.subitem_levels?.[id]||''} onChange={e=>set('subitem_levels',{...q.subitem_levels,[id]:Number(e.target.value)})}><option value="">Chưa phân loại</option>{[1,2,3,4].map(n=><option key={n} value={n}>{['NB','TH','VD','VDC'][n-1]}</option>)}</select></label><select aria-label={'Đáp án '+id} value={q.answer?.values?.[id]===undefined?'':String(q.answer.values[id])} onChange={e=>set('answer',{values:{...q.answer?.values,[id]:e.target.value==='true'}})}><option value="">Chọn Đ/S</option><option value="true">Đúng</option><option value="false">Sai</option></select></div>)}
 {q.type==='short_answer'&&<><label>Các đáp án chấp nhận (mỗi dòng một đáp án)<textarea value={q.answer?.aliases?.join('\n')||''} onChange={e=>set('answer',{...q.answer,aliases:e.target.value.split('\n')})}/></label><div className="practice-grid"><label>Đáp án số (tùy chọn)<input type="number" step="any" value={q.answer?.numeric??''} onChange={e=>{const a={...q.answer};if(e.target.value==='')delete a.numeric;else a.numeric=Number(e.target.value);set('answer',a);}}/></label><label>Sai số tuyệt đối<input type="number" min="0" step="any" value={q.answer?.tolerance||0} onChange={e=>set('answer',{...q.answer,tolerance:Number(e.target.value)})}/></label></div></>}
 {q.type==='matching'&&<><label>Cột A (mỗi dòng một ý)<textarea value={q.left?.map(x=>x.text).join('\n')||''} onChange={e=>set('left',e.target.value.split('\n').map((text,i)=>({id:String.fromCharCode(65+i),text})))}/></label><label>Cột B (mỗi dòng một ý)<textarea value={q.right?.map(x=>x.text).join('\n')||''} onChange={e=>set('right',e.target.value.split('\n').map((text,i)=>({id:String(i+1),text})))}/></label>{q.left?.map(l=><label key={l.id}>{l.id} ghép với<select value={q.answer?.pairs?.[l.id]||''} onChange={e=>set('answer',{pairs:{...q.answer?.pairs,[l.id]:e.target.value}})}><option value="">Chọn</option>{q.right?.map(r=><option key={r.id} value={r.id}>{r.id}. {r.text}</option>)}</select></label>)}</>}
 {q.type==='essay'&&<label>Đáp án tham khảo<textarea value={q.answer?.reference||''} onChange={e=>set('answer',{reference:e.target.value})}/></label>}<label>Lời giải (khuyến nghị)<textarea value={q.explanation||''} onChange={e=>set('explanation',e.target.value)}/></label></>;}
export function TemplateDownloads(){return <div className="practice-actions">{['question-import-khtn.docx','question-import.xlsx','question-import-images.zip','student-roster.xlsx','TEMPLATE_CHUAN_TOAN_TRUONG_OUTCOME_YCCD_QUESTION_METADATA_V1_1.xlsx'].map(name=><button className="btn" key={name} onClick={()=>downloadFile(base+'/templates/'+name,name).catch(e=>alert(e.message))}>Mẫu {name}</button>)}</div>;}
import {Rich} from './Rich.jsx';
