import {useState} from 'react';
import {api} from '../../api/client.js';
import {usePortfolio,LoadState} from '../practice/portfolio/common.jsx';

export default function CompetencyManager({subjects}){
 const load=usePortfolio('/api/competency/frameworks');
 const [selected,setSelected]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[reason,setReason]=useState(''),[confirmed,setConfirmed]=useState(false),[axis,setAxis]=useState(null),[form,setForm]=useState({subject_id:'',grade_from:6,grade_to:9,code:'',title:'',source:'',version:'',template:'KHTN'});
 async function run(fn){setBusy(true);setError('');try{await fn();load.reload();}catch(e){setError(e.message);}finally{setBusy(false);}}
 if(!load.data)return <LoadState load={load}/>;
 const f=load.data.frameworks.find(x=>x.id===Number(selected));
 return <section><h3>Khung năng lực theo môn</h3><p>Khung nháp cần rà soát nguồn trước khi công bố; không suy năng lực thực hành từ câu trắc nghiệm.</p>{error&&<p role="alert">{error}</p>}
 <details className="staff-card"><summary>Tạo khung năng lực nháp</summary><form onSubmit={e=>{e.preventDefault();run(async()=>{const n=await api.post('/api/competency/frameworks',{...form,subject_id:Number(form.subject_id),...(form.template?{}:{template:undefined})});setSelected(String(n.id));});}}><div className="staff-fields"><label>Môn<select required value={form.subject_id} onChange={e=>setForm({...form,subject_id:e.target.value})}><option value="">Chọn môn</option>{subjects.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Mẫu<select value={form.template} onChange={e=>setForm({...form,template:e.target.value})}><option>KHTN</option><option>MATH</option><option value="">Tùy chỉnh</option></select></label>{['grade_from','grade_to'].map(k=><label key={k}>{k==='grade_from'?'Từ khối':'Đến khối'}<input required type="number" min="1" max="12" value={form[k]} onChange={e=>setForm({...form,[k]:Number(e.target.value)})}/></label>)}{[['code','Mã khung'],['title','Tên khung'],['source','Nguồn'],['version','Phiên bản']].map(([k,l])=><label key={k}>{l}<input required value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}</div><button className="btn">Tạo khung nháp</button></form></details>
 <label>Khung năng lực<select value={selected} onChange={e=>{setSelected(e.target.value);setAxis(null);setConfirmed(false);}}><option value="">Chọn khung</option>{load.data.frameworks.map(x=><option key={x.id} value={x.id}>{x.subject_name} · {x.title} · {x.version} · {x.status}</option>)}</select></label>
 {f&&<><p>Nguồn: {f.source} · Khối {f.grade_from}–{f.grade_to}</p>{f.axes.map(a=><article className="staff-card" key={a.id}><h4>{a.code} · {a.name}</h4><p>{a.description}</p><p>Loại minh chứng: {a.allowed_evidence.join(', ')}</p>{f.status==='DRAFT'&&<button className="btn" onClick={()=>setAxis({id:a.id,code:a.code,name:a.name,description:a.description,order_index:a.order_index,status:a.status,allowed_evidence:a.allowed_evidence})}>Sửa trục</button>}</article>)}<MappingPanel key={f.id} f={f} busy={busy}/><CopyFramework key={'copy:'+f.id} f={f} onCopied={id=>{setSelected(String(id));setAxis(null);setConfirmed(false);load.reload();}}/>{f.status==='DRAFT'&&<button className="btn" onClick={()=>setAxis({code:'',name:'',description:'',order_index:f.axes.length,status:'ACTIVE',allowed_evidence:['TEACHER_RUBRIC']})}>Thêm trục năng lực</button>}
 {axis&&<form className="staff-card" onSubmit={e=>{e.preventDefault();run(async()=>{await api.put(`/api/competency/frameworks/${f.id}/axes`,{...axis,revision:f.revision,reason});setAxis(null);});}}>{[['code','Mã trục'],['name','Tên trục'],['description','Mô tả']].map(([k,l])=><label key={k}>{l}<input required={k!=='description'} value={axis[k]} onChange={e=>setAxis({...axis,[k]:e.target.value})}/></label>)}<fieldset><legend>Minh chứng được phép</legend>{load.data.evidence_types.map(t=><label className="staff-inline" key={t}><input type="checkbox" checked={axis.allowed_evidence.includes(t)} onChange={e=>setAxis({...axis,allowed_evidence:e.target.checked?[...axis.allowed_evidence,t]:axis.allowed_evidence.filter(v=>v!==t)})}/>{t}</label>)}</fieldset><button className="btn">Lưu trục</button></form>}
 <label>Lý do thay đổi / công bố<input value={reason} onChange={e=>setReason(e.target.value)}/></label>{f.status==='DRAFT'&&<><label className="staff-inline"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>Đã rà soát nguồn và minh chứng</label><button className="btn" disabled={!confirmed||!reason.trim()} onClick={()=>run(()=>api.post(`/api/competency/frameworks/${f.id}/publish`,{revision:f.revision,reason,confirmed}))}>Công bố khung</button></>}</>}
 </section>;
}
function MappingPanel({f,busy}){
 const [grade,setGrade]=useState(f.grade_from),[data,setData]=useState(null),[target,setTarget]=useState(''),[entries,setEntries]=useState([]),[reason,setReason]=useState(''),[confirmed,setConfirmed]=useState(false),[pending,setPending]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 async function run(fn){setPending(true);setError('');setMessage('');try{await fn();}catch(e){setError(e.message);}finally{setPending(false);}}
 async function loadMap(){setData(await api.get('/api/competency/mappings?subject_id='+f.subject_id+'&grade='+grade));}
 function choose(id){setTarget(id);setConfirmed(false);setReason('');const old=data?.mappings.find(x=>x.target_type==='yccd'&&String(x.target_id)===String(id));setEntries((old?.entries||[]).map(e=>({axis_id:e.axis_id,weight:e.weight})));}
 async function save(){await run(async()=>{await api.put('/api/competency/mappings/yccd/'+target,{entries,normalize:true,confirmed,reason});await loadMap();setConfirmed(false);setMessage('Đã lưu phiên bản ánh xạ. Bài làm cũ giữ nguyên.');});}
 const locked=busy||pending||f.status!=='PUBLISHED',unknown=entries.filter(e=>!f.axes.some(a=>a.id===e.axis_id));
 return <details className="staff-card"><summary>Gán trục năng lực cho YCCĐ</summary>
 <p>Chọn các trục phù hợp với minh chứng cá nhân. Trọng số được chuẩn hóa; không thay đổi lịch sử bài làm.</p>
 {f.status!=='PUBLISHED'&&<p>Công bố khung trước khi gán năng lực.</p>}
 {error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}
 <label>Khối ánh xạ<select aria-label="Khối ánh xạ" disabled={pending} value={grade} onChange={e=>{setGrade(Number(e.target.value));setData(null);setTarget('');setEntries([]);setConfirmed(false);}}>{Array.from({length:f.grade_to-f.grade_from+1},(_,i)=>f.grade_from+i).map(g=><option key={g}>{g}</option>)}</select></label>
 <button className="btn" disabled={locked} onClick={()=>run(loadMap)}>Tải danh mục YCCĐ</button>
 {data&&<><label>YCCĐ<select aria-label="YCCĐ ánh xạ" disabled={pending} value={target} onChange={e=>choose(e.target.value)}><option value="">Chọn YCCĐ</option>{data.yccds.map(y=><option key={y.id} value={y.id}>{y.label||y.code} · {y.text.slice(0,100)}</option>)}</select></label>
 {target&&<><fieldset disabled={locked}><legend>Trục được dùng</legend>
 {f.axes.filter(a=>a.status==='ACTIVE').map(a=>{const entry=entries.find(x=>x.axis_id===a.id);return <div key={a.id}><label className="staff-inline"><input type="checkbox" checked={!!entry} onChange={e=>{setConfirmed(false);setEntries(e.target.checked?[...entries,{axis_id:a.id,weight:1}]:entries.filter(x=>x.axis_id!==a.id));}}/>{a.code} · {a.name}</label>{entry&&<label>Trọng số {a.code}<input aria-label={'Trọng số '+a.code} type="number" min="0.01" max="1" step="0.01" value={entry.weight} onChange={e=>{setConfirmed(false);setEntries(entries.map(x=>x.axis_id===a.id?{...x,weight:Number(e.target.value)}:x));}}/></label>}</div>;})}
 </fieldset>{unknown.length>0&&<p>Đang giữ {unknown.length} trục thuộc khung khác trong ánh xạ hiện tại; không tự xóa.</p>}
 <label>Lý do mapping<input required value={reason} onChange={e=>setReason(e.target.value)}/></label>
 <label className="staff-inline"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>Xác nhận ánh xạ và trọng số đã được rà soát</label>
 <button className="btn" disabled={locked||!confirmed||!reason.trim()||entries.some(e=>!Number.isFinite(e.weight)||e.weight<=0||e.weight>1)} onClick={save}>Lưu mapping phiên bản</button></>}</>}
 </details>;
}
function CopyFramework({f,onCopied}){
 const [version,setVersion]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 return <form className="staff-card" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const n=await api.post('/api/competency/frameworks/'+f.id+'/copy',{version,title:f.title});onCopied(n.id);}catch(err){setError(err.message);}finally{setBusy(false);}}}>
 <h4>Sao chép để chỉnh sửa</h4><label>Mã phiên bản mới<input required value={version} onChange={e=>setVersion(e.target.value)}/></label><button className="btn" disabled={busy||!version.trim()}>Sao chép thành khung nháp</button>{error&&<p role="alert">{error}</p>}</form>;
}
