import {useState} from 'react';
import {api} from '../../api/client.js';
import {usePortfolio,LoadState} from '../practice/portfolio/common.jsx';
export default function CompetencyManager({subjects}){
 const load=usePortfolio('/api/competency/frameworks'),[selected,setSelected]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[reason,setReason]=useState(''),[confirmed,setConfirmed]=useState(false);
 const [form,setForm]=useState({subject_id:'',grade_from:6,grade_to:9,code:'',title:'',source:'',version:'',template:'KHTN'}),[axis,setAxis]=useState(null),[copyVersion,setCopyVersion]=useState('');
 async function run(fn){setBusy(true);setError('');try{await fn();load.reload();}catch(e){setError(e.message);}finally{setBusy(false);}}
 if(!load.data)return <LoadState load={load}/>;
 const f=load.data.frameworks.find(f=>f.id===Number(selected));
 return <section><h3>Khung năng lực theo môn</h3><p>Khung nháp cần được rà soát nguồn trước khi công bố. Không suy năng lực thực hành từ câu trắc nghiệm không phù hợp.</p>{error&&<p role="alert">{error}</p>}
 <details className="staff-card"><summary>Tạo khung năng lực nháp</summary><form onSubmit={e=>{e.preventDefault();run(async()=>{const result=await api.post('/api/competency/frameworks',{...form,subject_id:Number(form.subject_id),...(form.template?{}:{template:undefined})});setSelected(String(result.id));});}}><div className="staff-fields"><label>Môn<select required value={form.subject_id} onChange={e=>setForm({...form,subject_id:e.target.value})}><option value="">Chọn môn</option>{subjects.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Mẫu khởi tạo<select value={form.template} onChange={e=>setForm({...form,template:e.target.value})}><option value="KHTN">KHTN — 3 trục</option><option value="MATH">Toán — 5 trục</option><option value="">Tùy chỉnh</option></select></label>{['grade_from','grade_to'].map(k=><label key={k}>{k==='grade_from'?'Từ khối':'Đến khối'}<input required type="number" min="1" max="12" value={form[k]} onChange={e=>setForm({...form,[k]:Number(e.target.value)})}/></label>)}{[['code','Mã khung'],['title','Tên khung'],['source','Nguồn / căn cứ'],['version','Mã phiên bản']].map(([k,label])=><label key={k}>{label}<input required value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}</div><button className="btn" disabled={busy}>Tạo khung nháp</button></form></details>
 <label>Khung năng lực<select value={selected} onChange={e=>{setSelected(e.target.value);setAxis(null);setConfirmed(false);}}><option value="">Chọn khung</option>{load.data.frameworks.map(f=><option key={f.id} value={f.id}>{f.subject_name} · {f.title} · {f.version} · {f.status}</option>)}</select></label>
 {f&&<><p>Nguồn: {f.source} · Khối {f.grade_from}–{f.grade_to}</p>{f.axes.map(a=><article className="staff-card" key={a.id}><h4>{a.code} · {a.name}</h4><p>{a.description}</p><p>Loại minh chứng: {a.allowed_evidence.join(', ')}</p>{f.status==='DRAFT'&&<button className="btn" onClick={()=>setAxis({id:a.id,code:a.code,name:a.name,description:a.description,order_index:a.order_index,status:a.status,allowed_evidence:a.allowed_evidence})}>Sửa trục</button>}</article>)}
 {f.status==='DRAFT'&&<button className="btn" onClick={()=>setAxis({code:'',name:'',description:'',order_index:f.axes.length,status:'ACTIVE',allowed_evidence:['TEACHER_RUBRIC']})}>Thêm trục năng lực</button>}
 {axis&&<form className="staff-card" onSubmit={e=>{e.preventDefault();run(async()=>{await api.put(`/api/competency/frameworks/${f.id}/axes`,{...axis,revision:f.revision,reason});setAxis(null);});}}>{[['code','Mã trục'],['name','Tên trục'],['description','Mô tả']].map(([k,label])=><label key={k}>{label}<input required={k!=='description'} value={axis[k]} onChange={e=>setAxis({...axis,[k]:e.target.value})}/></label>)}<fieldset><legend>Minh chứng được phép</legend>{load.data.evidence_types.map(t=><label className="staff-inline" key={t}><input type="checkbox" checked={axis.allowed_evidence.includes(t)} onChange={e=>setAxis({...axis,allowed_evidence:e.target.checked?[...axis.allowed_evidence,t]:axis.allowed_evidence.filter(v=>v!==t)})}/>{t}</label>)}</fieldset><button className="btn" disabled={busy||!reason.trim()||!axis.allowed_evidence.length}>Lưu trục</button></form>}
 <label>Lý do thay đổi / công bố<input value={reason} onChange={e=>setReason(e.target.value)}/></label>{f.status==='DRAFT'&&<><label className="staff-inline"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>Đã rà soát nguồn, trục và loại minh chứng</label><button className="btn" disabled={busy||!confirmed||!reason.trim()} onClick={()=>run(()=>api.post(`/api/competency/frameworks/${f.id}/publish`,{revision:f.revision,reason,confirmed}))}>Công bố khung</button></>}
 <label>Mã phiên bản sao chép<input value={copyVersion} onChange={e=>setCopyVersion(e.target.value)}/></label><button className="btn" disabled={busy||!copyVersion.trim()} onClick={()=>run(async()=>{const n=await api.post(`/api/competency/frameworks/${f.id}/copy`,{version:copyVersion,title:f.title});setSelected(String(n.id));setAxis(null);setConfirmed(false);})}>Sao chép thành khung nháp</button>
 </>}
 </section>;
}
