import {useEffect,useState} from 'react';
import {api,uploadFile} from '../../api/client.js';
import Configuration from '../practice/Configuration.jsx';
import CompetencyManager from './CompetencyManager.jsx';
const base='/api/curriculum';
const names={domain:'Mã phân môn (giữ nguyên)',outcome_code:'Mã Outcome',outcome_title:'Nội dung Outcome',code:'Mã YCCĐ',text:'Nội dung YCCĐ',group:'Chủ đề / nhóm tạm',page:'Trang nguồn',order:'Thứ tự',notes:'Ghi chú'};
export default function CurriculumManager(){
 const [catalog,setCatalog]=useState([]),[versions,setVersions]=useState([]),[selected,setSelected]=useState(''),[data,setData]=useState(null),[tab,setTab]=useState('editor'),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const [version,setVersion]=useState({subject_id:'',grade:7,version_code:'',title:'',source_name:'',source_ref:''});
 const [form,setForm]=useState(null),[reason,setReason]=useState(''),[confirmed,setConfirmed]=useState(false),[copy,setCopy]=useState({version_code:'',title:''}),[compare,setCompare]=useState(''),[diff,setDiff]=useState(null),[impact,setImpact]=useState(null);
 const [jobs,setJobs]=useState([]),[job,setJob]=useState(null),[sheet,setSheet]=useState(''),[header,setHeader]=useState(1),[columns,setColumns]=useState({}),[topicAsOutcome,setTopicAsOutcome]=useState(false),[edits,setEdits]=useState({}),[bulk,setBulk]=useState({outcome_title:'',domain:''}),[checked,setChecked]=useState([]);
 const [sourceProfile,setSourceProfile]=useState(null),[acceptSourceWarnings,setAcceptSourceWarnings]=useState(false);
 async function refresh(id=selected){setVersions(await api.get(base+'/versions'));if(id)setData(await api.get(base+'/versions/'+id));}
 async function run(f){setBusy(true);setError('');setMessage('');try{await f();}catch(e){setError(e.message);}finally{setBusy(false);}}
 useEffect(()=>{run(async()=>{setCatalog((await api.get(base+'/catalog')).subjects);await refresh();});},[]);
 useEffect(()=>{setForm(null);setJob(null);setJobs([]);setDiff(null);setImpact(null);setConfirmed(false);if(selected)run(()=>refresh(selected));else setData(null);},[selected]);
 async function readJob(id=job?.job?.id){const result=await api.get(base+'/import/'+id+'/preview');setJob(result);
  // Bộ 4 workbook KHTN chính thức được nhận diện sẵn: tự điền sheet, dòng tiêu đề và ánh xạ cột,
  // ưu tiên sheet có khối khớp phiên bản đang mở. Người dùng không phải map cột lại mỗi lần.
  const auto=!result.job.mapping&&result.trusted?(result.trusted.sheets.find(s=>s.grade_matches_version)||result.trusted.sheets[0]):null;
  setSourceProfile(result.job.mapping?.source_profile||(auto?result.trusted.profile:null));
  setSheet(result.job.mapping?.sheet||auto?.sheet||result.sheets[0]?.name||'');
  setHeader(result.job.mapping?.header_row||auto?.header_row||1);
  setColumns(result.job.mapping?.columns||auto?.columns||{});
  setTopicAsOutcome(result.job.mapping?.topic_as_outcome??auto?.topic_as_outcome??false);
  setAcceptSourceWarnings(false);
  setEdits(Object.fromEntries(result.rows.map(r=>[r.id,r.mapped_payload])));setChecked([]);}
 const editable=data?.version.status==='DRAFT',currentSheet=job?.sheets.find(s=>s.name===sheet),headers=currentSheet?.rows[header-1]||[];
 const stagingDirty=job?.rows.some(r=>JSON.stringify(edits[r.id])!==JSON.stringify(r.mapped_payload));
 function newItem(type,row){setForm({type,id:row?.id,code:row?.code||'',text:row?.text||row?.title||'',domain_code:row?.domain_code||'',outcome_id:row?.outcome_id||null,source_page:row?.source_locator||'',order_index:row?.order_index||0});setImpact(null);}
 return <section className="staff-page curriculum-master"><header><h2>Môn học & Chương trình</h2><p>Bản nháp → rà soát → công bố. Bài học, Outcome và YCCĐ là ba đối tượng khác nhau; không tự suy diễn quan hệ.</p></header>
 {error&&<p className="staff-error" role="alert">{error}</p>}{message&&<p className="staff-success" role="status">{message}</p>}
 <details className="staff-card"><summary>Tạo phiên bản chương trình</summary><form onSubmit={e=>{e.preventDefault();run(async()=>{const v=await api.post(base+'/versions',{...version,subject_id:Number(version.subject_id),grade:Number(version.grade)});setSelected(String(v.id));setMessage('Đã tạo bản nháp.');});}}><div className="staff-fields"><label>Môn<select required value={version.subject_id} onChange={e=>setVersion({...version,subject_id:e.target.value})}><option value="">Chọn môn</option>{catalog.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Khối<select value={version.grade} onChange={e=>setVersion({...version,grade:Number(e.target.value)})}>{(catalog.find(s=>s.id===Number(version.subject_id))?.grades||[6,7,8,9]).map(n=><option key={n}>{n}</option>)}</select></label>{[['version_code','Mã phiên bản'],['title','Tên phiên bản'],['source_name','Tên nguồn'],['source_ref','Tham chiếu nguồn']].map(([k,n])=><label key={k}>{n}<input required={['version_code','title'].includes(k)} value={version[k]} onChange={e=>setVersion({...version,[k]:e.target.value})}/></label>)}</div><button className="btn btn-primary" disabled={busy}>Tạo bản nháp</button></form></details>
 <label>Phiên bản chương trình<select aria-label="Phiên bản chương trình" value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Chọn phiên bản</option>{versions.map(v=><option key={v.id} value={v.id}>{v.subject_name} · Khối {v.grade} · {v.title} · {v.status}</option>)}</select></label>
 <nav className="staff-tabs">{[['editor','Outcome & YCCĐ'],['mapping','Bài học ↔ YCCĐ'],['import','Import'],['history','Phiên bản & lịch sử'],['competency','Khung năng lực']].map(([k,n])=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k)}>{n}</button>)}</nav>
 {tab==='competency'?<CompetencyManager subjects={catalog}/>:tab==='mapping'?<Configuration section="curriculum"/>:!data?<p>Chọn hoặc tạo phiên bản để bắt đầu. Chương trình legacy và liên kết hiện hữu vẫn nằm ở mục Bài học ↔ YCCĐ.</p>:<>
 <p><strong>{data.version.title}</strong> · {data.version.status} · {data.outcomes.length} Outcome / {data.yccds.length} YCCĐ</p>
 {!editable&&<p className="staff-note">Bản công bố không sửa trực tiếp. Sang Phiên bản & lịch sử để sao chép thành bản nháp; bài làm cũ giữ nguyên.</p>}
 {tab==='editor'&&<><div className="staff-fields"><button className="btn" disabled={!editable||busy} onClick={()=>newItem('outcome')}>Thêm Outcome</button><button className="btn" disabled={!editable||busy} onClick={()=>newItem('yccd')}>Thêm YCCĐ</button></div>
 {form&&<form className="staff-card" onSubmit={e=>{e.preventDefault();run(async()=>{const {type,id,...values}=form;await api[id?'patch':'post'](base+'/'+type+'s'+(id?'/'+id:''),{...values,version_id:Number(selected),revision:data.version.revision,reason});setForm(null);await refresh();setMessage('Đã lưu bản nháp và ghi lịch sử.');});}}><h3>{form.id?'Sửa':'Thêm'} {form.type==='outcome'?'Outcome':'YCCĐ'}</h3><div className="staff-fields"><label>Mã hiển thị<input required value={form.code} onChange={e=>setForm({...form,code:e.target.value})}/></label><label>Trang nguồn<input value={form.source_page} onChange={e=>setForm({...form,source_page:e.target.value})}/></label><label>Thứ tự<input type="number" min="0" value={form.order_index} onChange={e=>setForm({...form,order_index:Number(e.target.value)})}/></label>{form.type==='outcome'?<label>Mã phân môn<input value={form.domain_code} onChange={e=>setForm({...form,domain_code:e.target.value})}/></label>:<label>Outcome cha<select required value={form.outcome_id||''} onChange={e=>setForm({...form,outcome_id:Number(e.target.value)})}><option value="">Chọn Outcome</option>{data.outcomes.filter(o=>o.status!=='RETIRED').map(o=><option key={o.id} value={o.id}>{o.code} · {o.title}</option>)}</select></label>}</div><label>Nội dung nguyên văn<textarea required value={form.text} onChange={e=>setForm({...form,text:e.target.value})}/></label><label>Lý do<input required minLength={3} value={reason} onChange={e=>setReason(e.target.value)}/></label><button className="btn btn-primary" disabled={busy}>Lưu chuẩn</button><button type="button" className="btn" onClick={()=>setForm(null)}>Hủy</button></form>}
 {data.outcomes.map(o=><article className="staff-card" key={o.id}><h3>{o.code} · {o.title}</h3><p>{o.domain_code||'Không phân môn'} · {o.status}</p><button className="btn" disabled={!editable} onClick={()=>newItem('outcome',o)}>Sửa Outcome</button><button className="btn" onClick={()=>run(async()=>setImpact({type:'outcome',id:o.id,...await api.get(base+'/outcomes/'+o.id+'/impact')}))}>Xem tác động Outcome</button>{data.yccds.filter(y=>y.outcome_id===o.id).map(y=><div className="staff-override" key={y.id}><strong>{y.code}</strong><p style={{whiteSpace:'pre-wrap'}}>{y.text}</p><small>Trang: {y.source_locator||'Chưa có'} · {y.status}</small><div><button className="btn" disabled={!editable} onClick={()=>newItem('yccd',y)}>Sửa YCCĐ</button><button className="btn" onClick={()=>run(async()=>setImpact({type:'yccd',id:y.id,...await api.get(base+'/yccds/'+y.id+'/impact')}))}>Xem tác động YCCĐ</button></div></div>)}</article>)}
 {impact&&<article className="staff-card"><h3>Tác động trước khi ngừng sử dụng</h3>{Object.entries(impact.counts).map(([k,v])=><p key={k}>{({questions:'Câu hỏi',versions:'Phiên bản câu hỏi',mappings:'Liên kết bài học',draft_matrices:'Ma trận nháp',approved_matrices:'Ma trận đã duyệt',assignments:'Bài giao',attempt_items:'Minh chứng bài làm'})[k]||k}: {v}</p>)}<label>Lý do<input value={reason} onChange={e=>setReason(e.target.value)}/></label>{editable&&<><button className="btn" disabled={busy||reason.trim().length<3} onClick={()=>run(async()=>{await api.post(base+'/'+impact.type+'s/'+impact.id+'/retire',{reason,revision:data.version.revision,retire:true});setImpact(null);await refresh();})}>Ngừng sử dụng trong bản nháp</button><button className="btn" disabled={busy||reason.trim().length<3||Object.values(impact.counts).some(n=>n>0)} onClick={()=>run(async()=>{await api.post(base+'/'+impact.type+'s/'+impact.id+'/retire',{reason,revision:data.version.revision,retire:false});setImpact(null);await refresh();})}>Xóa chuẩn nháp chưa dùng</button></>}<button className="btn" onClick={()=>setImpact(null)}>Đóng</button></article>}</>}
 {tab==='import'&&<article className="staff-card"><h3>Nạp Outcome / YCCĐ</h3><p>XLSX, XLS, CSV · tối đa 6 MB. Không tự sửa nguyên văn hoặc gán ý nghĩa H/L/S.</p><input aria-label="Tệp Outcome YCCĐ" type="file" accept=".xlsx,.xls,.csv" disabled={!editable||busy} onChange={e=>{const file=e.target.files[0];if(file)run(async()=>{const j=await uploadFile(base+'/import',file,{version_id:selected});await readJob(j.id);setSheet(j.sheets[0]?.name||'');setColumns({});await refresh();});}}/>
 <button className="btn" disabled={busy} onClick={()=>run(async()=>setJobs(await api.get(base+'/versions/'+selected+'/imports')))}>Mở phiên nhập đã lưu</button><ul>{jobs.map(j=><li key={j.id}><button className="btn" disabled={busy||stagingDirty} onClick={()=>run(()=>readJob(j.id))}>{j.filename} · {j.status}</button></li>)}</ul>{job&&<>{job.trusted&&(()=>{const s=job.trusted.sheets.find(x=>x.sheet===sheet)||job.trusted.sheets[0];const mismatch=s&&!s.grade_matches_version;return <div className={mismatch?'warn-box':'ok-box'} role="status">
 <p>{mismatch?'⚠':'✓'} Đã nhận diện bộ Outcome/YCCĐ KHTN chính thức — Khối {s?.grade}</p>
 <p>Môn → Phân môn · Chủ đề → Outcome · Yêu cầu cần đạt → YCCĐ · Trang nguồn → Nguồn</p>
 <p>Số thứ tự Outcome và YCCĐ lấy nguyên từ nguồn. Ô chứa nhiều YCCĐ sẽ được tách thành từng yêu cầu để rà soát trước khi nhập.</p>
 {mismatch&&<p>Sheet là khối {s?.grade} nhưng phiên bản đang mở là khối {data?.version.grade}. Chọn đúng phiên bản hoặc đúng sheet trước khi map.</p>}
 <label className="scope-v2-tick"><input type="checkbox" checked={sourceProfile===job.trusted.profile} onChange={e=>setSourceProfile(e.target.checked?job.trusted.profile:null)}/>Dùng hồ sơ nguồn chính thức cho lần nhập này</label>
</div>;})()}<div className="staff-fields"><label>Sheet<select value={sheet} onChange={e=>{setSheet(e.target.value);setColumns({});}}>{job.sheets.map(s=><option key={s.name}>{s.name}</option>)}</select></label><label>Dòng tiêu đề<input type="number" min="1" value={header} onChange={e=>setHeader(Number(e.target.value))}/></label></div><div className="staff-fields">{Object.entries(names).map(([key,label])=><label key={key}>{label}<select value={columns[key]??''} onChange={e=>setColumns({...columns,[key]:e.target.value===''?undefined:Number(e.target.value)})}><option value="">Bỏ qua / chưa có</option>{headers.map((h,i)=><option key={i} value={i}>{i+1}. {String(h)||'(trống)'}</option>)}</select></label>)}</div>
 <p className="staff-note">Nếu nguồn chỉ có Chủ đề + YCCĐ, giữ nhóm tạm và gán Outcome thủ công bên dưới. Chỉ đánh dấu lựa chọn sau khi anh xác nhận Chủ đề trong file chính là Outcome.</p><label className="staff-inline"><input type="checkbox" checked={topicAsOutcome} onChange={e=>setTopicAsOutcome(e.target.checked)}/>Tôi chủ động dùng cột Chủ đề làm Outcome nháp</label>
 <button className="btn" disabled={busy||job.job.status==='COMMITTED'} onClick={()=>run(async()=>{await api.put(base+'/import/'+job.job.id+'/map',{sheet,header_row:header,columns:Object.fromEntries(Object.entries(columns).filter(([,v])=>v!==undefined)),topic_as_outcome:topicAsOutcome,source_profile:sourceProfile,revision:job.job.revision});await readJob();await refresh();})}>Map cột & xem trước</button>
 {job.rows.length>0&&<><h3>Sửa dữ liệu staging</h3><p>{job.rows.length} dòng · Dòng BLOCKED/DUPLICATE phải sửa hoặc bỏ qua. Mã trống được cấp mã kỹ thuật, không lấy số hàng làm ID.</p><div className="staff-fields"><label>Outcome gán hàng loạt<input value={bulk.outcome_title} onChange={e=>setBulk({...bulk,outcome_title:e.target.value})}/></label><label>Phân môn gán hàng loạt<input value={bulk.domain} onChange={e=>setBulk({...bulk,domain:e.target.value})}/></label><button className="btn" onClick={()=>setEdits(previous=>({...previous,...Object.fromEntries(checked.map(id=>[id,{...previous[id],...(bulk.outcome_title?{outcome_title:bulk.outcome_title}:{}),...(bulk.domain?{domain:bulk.domain}:{})}]))}))}>Áp dụng cho dòng đã chọn</button></div>
 {job.rows.map(r=><details className="staff-card" key={r.id}><summary>Dòng {r.source_row} · {r.row_status} · {edits[r.id]?.text?.slice(0,80)}</summary><label className="staff-inline"><input type="checkbox" checked={checked.includes(r.id)} onChange={e=>setChecked(e.target.checked?[...checked,r.id]:checked.filter(id=>id!==r.id))}/>Chọn để gán hàng loạt</label>{r.validation_result.map((w,i)=><p className="staff-warning" key={i}>{w}</p>)}<div className="staff-fields">{Object.entries(names).filter(([k])=>k!=='order').map(([k,n])=><label key={k}>{n}<textarea value={edits[r.id]?.[k]||''} onChange={e=>setEdits({...edits,[r.id]:{...edits[r.id],[k]:e.target.value}})}/></label>)}</div><label className="staff-inline"><input type="checkbox" checked={edits[r.id]?.ignored||false} onChange={e=>setEdits({...edits,[r.id]:{...edits[r.id],ignored:e.target.checked}})}/>Bỏ qua dòng (giữ dữ liệu nguồn)</label></details>)}
 <button className="btn" disabled={busy||job.job.status==='COMMITTED'} onClick={()=>run(async()=>{await api.put(base+'/import/'+job.job.id+'/rows',{revision:job.job.revision,rows:Object.entries(edits).map(([id,values])=>({id:Number(id),values}))});await readJob();await refresh();})}>Lưu sửa & kiểm tra lại</button>
 {stagingDirty&&<p role="status">Có thay đổi chưa lưu. Bấm “Lưu sửa & kiểm tra lại” trước khi nhập.</p>}<label>Lý do nhập<textarea value={reason} onChange={e=>setReason(e.target.value)}/></label>
{job.rows.some(r=>r.row_status==='WARNING')&&<label className="scope-v2-tick"><input type="checkbox" checked={acceptSourceWarnings} onChange={e=>setAcceptSourceWarnings(e.target.checked)}/>Tôi đã rà soát các dòng có cảnh báo về số thứ tự nguồn và xác nhận nhập</label>}
<button className="btn btn-primary" disabled={busy||stagingDirty||job.job.status==='COMMITTED'||reason.trim().length<3||job.rows.some(r=>['BLOCKED','DUPLICATE'].includes(r.row_status))} onClick={()=>run(async()=>{await api.post(base+'/import/'+job.job.id+'/commit',{revision:job.job.revision,confirmed:true,reason,accept_source_warnings:acceptSourceWarnings});await readJob();await refresh();setMessage('Đã nhập vào DRAFT, chưa công bố.');})}>Xác nhận nhập vào bản nháp</button></>}</>}
 </article>}
 {tab==='history'&&<><article className="staff-card"><h3>Sao chép phiên bản để chỉnh sửa</h3><div className="staff-fields"><label>Mã mới<input value={copy.version_code} onChange={e=>setCopy({...copy,version_code:e.target.value})}/></label><label>Tên mới<input value={copy.title} onChange={e=>setCopy({...copy,title:e.target.value})}/></label></div><button className="btn" disabled={busy||!copy.version_code||!copy.title} onClick={()=>run(async()=>{const v=await api.post(base+'/versions/'+selected+'/copy',copy);setSelected(String(v.id));})}>Sao chép thành bản nháp</button>
 <label>So với phiên bản<select aria-label="So với phiên bản" value={compare} onChange={e=>setCompare(e.target.value)}><option value="">Chọn phiên bản</option>{versions.filter(v=>v.id!==Number(selected)&&v.subject_id===data.version.subject_id&&v.grade===data.version.grade).map(v=><option key={v.id} value={v.id}>{v.title}</option>)}</select></label><button className="btn" disabled={!compare||busy} onClick={()=>run(async()=>setDiff(await api.get(base+'/versions/'+compare+'/diff/'+selected)))}>Xem khác biệt</button>{diff&&<><p>{diff.note}</p>{diff.changes.length===0&&<p>Không có thay đổi nội dung.</p>}{diff.changes.map((c,i)=><article key={i}><h4>{c.code} · {({ADDED:'Thêm mới',REMOVED:'Đã bỏ',RETIRED:'Ngừng sử dụng',CHANGED:'Thay đổi'})[c.kind]}</h4><p>Trước: {c.before||'—'}</p><p>Sau: {c.after||'—'}</p><p>Trường đổi: {c.fields.map(k=>({code:'Mã',text:'Nội dung',title:'Tên',source_locator:'Nguồn',order_index:'Thứ tự',status:'Trạng thái',outcome:'Outcome cha'})[k]||k).join(', ')}</p></article>)}</>}
 </article>{editable&&<article className="staff-card"><h3>Công bố phiên bản</h3><label>Lý do / căn cứ<textarea value={reason} onChange={e=>setReason(e.target.value)}/></label><label className="staff-inline"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>Tôi đã kiểm tra nguồn và nội dung. Công bố không tự gán bài học hoặc đổi dữ liệu lịch sử.</label><button className="btn btn-primary" disabled={busy||!confirmed||reason.trim().length<3} onClick={()=>run(async()=>{await api.post(base+'/versions/'+selected+'/publish',{revision:data.version.revision,reason,confirmed});await refresh();setMessage('Đã công bố phiên bản.');})}>Công bố</button></article>}<article className="staff-card"><h3>Nhật ký</h3>{data.history.map((h,i)=><p key={i}>{new Date(h.created_at).toLocaleString('vi-VN')} · {h.action} · {h.reason}</p>)}</article></>}
 </>}
 </section>;
}
