ALTER TABLE users ADD COLUMN IF NOT EXISTS must_change_password boolean NOT NULL DEFAULT false;
ALTER TABLE users ADD COLUMN IF NOT EXISTS token_version integer NOT NULL DEFAULT 0;
CREATE TABLE IF NOT EXISTS school_years(id serial PRIMARY KEY,name text UNIQUE NOT NULL,start_date date,end_date date,active boolean DEFAULT false);
CREATE TABLE IF NOT EXISTS classes(id serial PRIMARY KEY,name text NOT NULL,grade integer NOT NULL CHECK(grade BETWEEN 1 AND 12),school_year_id integer NOT NULL REFERENCES school_years,UNIQUE(name,school_year_id));
CREATE TABLE IF NOT EXISTS student_profiles(user_id integer PRIMARY KEY REFERENCES users,student_code text UNIQUE NOT NULL);
CREATE TABLE IF NOT EXISTS class_memberships(id serial PRIMARY KEY,class_id integer NOT NULL REFERENCES classes,student_id integer NOT NULL REFERENCES student_profiles(user_id),valid_from date DEFAULT CURRENT_DATE,valid_to date,UNIQUE(class_id,student_id));
CREATE TABLE IF NOT EXISTS teacher_class_assignments(teacher_id integer REFERENCES users,class_id integer REFERENCES classes,subject_id integer REFERENCES subjects,PRIMARY KEY(teacher_id,class_id,subject_id));
CREATE TABLE IF NOT EXISTS subject_profiles(subject_id integer PRIMARY KEY REFERENCES subjects,config jsonb NOT NULL DEFAULT '{}');
CREATE TABLE IF NOT EXISTS taxonomy_versions(id serial PRIMARY KEY,subject_id integer REFERENCES subjects,name text NOT NULL,created_at timestamptz DEFAULT now(),UNIQUE(subject_id,name));
CREATE TABLE IF NOT EXISTS taxonomy_nodes(id serial PRIMARY KEY,version_id integer NOT NULL REFERENCES taxonomy_versions,parent_id integer REFERENCES taxonomy_nodes,node_type text NOT NULL DEFAULT 'specialty',name text NOT NULL,legacy_topic_id integer UNIQUE REFERENCES topics,metadata jsonb DEFAULT '{}');
INSERT INTO taxonomy_versions(subject_id,name) SELECT id,'V4 chuyển tiếp' FROM subjects ON CONFLICT DO NOTHING;
INSERT INTO taxonomy_nodes(version_id,name,legacy_topic_id,metadata) SELECT v.id,t.name,t.id,jsonb_build_object('grade',t.grade,'branch_id',t.branch_id) FROM topics t JOIN taxonomy_versions v ON v.subject_id=t.subject_id AND v.name='V4 chuyển tiếp' ON CONFLICT DO NOTHING;
INSERT INTO subject_profiles(subject_id,config) SELECT id,jsonb_build_object('required_fields',jsonb_build_array('subject_id','grade','topic_id','cognitive_level'),'allowed_types',jsonb_build_array('multiple_choice','true_false','short_answer','matching','essay'),'level_labels',jsonb_build_array('Nhận biết','Thông hiểu','Vận dụng','Vận dụng cao'),'display_code_template','{subject}.{level}.{sequence}') FROM subjects ON CONFLICT DO NOTHING;
CREATE TABLE IF NOT EXISTS banks(id serial PRIMARY KEY,name text NOT NULL,kind text NOT NULL CHECK(kind IN('personal','department','school')),owner_id integer REFERENCES users,department_id integer REFERENCES departments);
CREATE UNIQUE INDEX IF NOT EXISTS bank_personal_owner ON banks(owner_id) WHERE kind='personal';
CREATE TABLE IF NOT EXISTS bank_memberships(bank_id integer REFERENCES banks,user_id integer REFERENCES users,permission text NOT NULL CHECK(permission IN('read','write','review')),PRIMARY KEY(bank_id,user_id));
INSERT INTO banks(name,kind) SELECT 'Kho trường chuyển tiếp V4','school' WHERE NOT EXISTS(SELECT 1 FROM banks WHERE kind='school');
INSERT INTO banks(name,kind,owner_id) SELECT 'Kho cá nhân · '||full_name,'personal',id FROM users WHERE role::text NOT IN('student','viewer') ON CONFLICT DO NOTHING;
ALTER TABLE questions ADD COLUMN IF NOT EXISTS bank_id integer REFERENCES banks;
ALTER TABLE questions ADD COLUMN IF NOT EXISTS lifecycle text NOT NULL DEFAULT 'draft' CHECK(lifecycle IN('draft','pending_review','approved','active','archived'));
ALTER TABLE questions ADD COLUMN IF NOT EXISTS normalized_content jsonb;
ALTER TABLE questions ADD COLUMN IF NOT EXISTS current_version_id uuid;
UPDATE questions SET bank_id=(SELECT min(id) FROM banks WHERE kind='school'),lifecycle=CASE WHEN status::text IN('Đã rà soát','Đã duyệt','Đã sử dụng') THEN 'active' WHEN status::text='Tạm ẩn' THEN 'archived' ELSE 'draft' END WHERE bank_id IS NULL;
CREATE TABLE IF NOT EXISTS question_versions(id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),question_id integer NOT NULL REFERENCES questions,version_number integer NOT NULL,cognitive_level integer NOT NULL CHECK(cognitive_level BETWEEN 1 AND 4),taxonomy_node_id integer REFERENCES taxonomy_nodes,subject_id integer REFERENCES subjects,topic_id integer REFERENCES topics,grade integer NOT NULL,question_type text NOT NULL,auto_gradable boolean NOT NULL,content jsonb NOT NULL,created_by integer REFERENCES users,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(question_id,version_number));
CREATE TABLE IF NOT EXISTS question_sources(id bigserial PRIMARY KEY,question_version_id uuid REFERENCES question_versions,source_type text,source_path text,source_locator text,checksum text);
CREATE TABLE IF NOT EXISTS media_assets(id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),storage_key text UNIQUE NOT NULL,original_filename text,mime text NOT NULL,size_bytes bigint NOT NULL,checksum text UNIQUE NOT NULL,created_by integer REFERENCES users,created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS question_media_links(question_version_id uuid REFERENCES question_versions,media_id uuid REFERENCES media_assets,location text NOT NULL DEFAULT 'stem',order_index integer DEFAULT 0,PRIMARY KEY(question_version_id,media_id,location,order_index));
CREATE OR REPLACE FUNCTION practice_snapshot_question() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE v uuid; n integer; node integer; payload jsonb;
BEGIN
 IF TG_OP='UPDATE' AND ROW(NEW.stem_text,NEW.option_a,NEW.option_b,NEW.option_c,NEW.option_d,NEW.answer_key,NEW.explanation,NEW.image_url,NEW.cognitive_level,NEW.q_type,NEW.topic_id,NEW.subject_id,NEW.grade,NEW.normalized_content,NEW.question_code) IS NOT DISTINCT FROM ROW(OLD.stem_text,OLD.option_a,OLD.option_b,OLD.option_c,OLD.option_d,OLD.answer_key,OLD.explanation,OLD.image_url,OLD.cognitive_level,OLD.q_type,OLD.topic_id,OLD.subject_id,OLD.grade,OLD.normalized_content,OLD.question_code) AND NEW.current_version_id IS NOT NULL THEN RETURN NEW; END IF;
 SELECT COALESCE(max(version_number),0)+1 INTO n FROM question_versions WHERE question_id=NEW.id;
 SELECT id INTO node FROM taxonomy_nodes WHERE legacy_topic_id=NEW.topic_id;
 payload := COALESCE(NEW.normalized_content,to_jsonb(NEW)-'normalized_content'-'current_version_id');
 INSERT INTO question_versions(question_id,version_number,cognitive_level,taxonomy_node_id,subject_id,topic_id,grade,question_type,auto_gradable,content,created_by)
 VALUES(NEW.id,n,right(NEW.cognitive_level::text,1)::integer,node,NEW.subject_id,NEW.topic_id,NEW.grade,CASE NEW.q_type::text WHEN 'mcq4' THEN 'multiple_choice' WHEN 'short' THEN 'short_answer' ELSE NEW.q_type::text END,NEW.q_type::text<>'essay' AND COALESCE((payload->>'auto_gradable')::boolean,true),payload,NEW.creator_id) RETURNING id INTO v;
 UPDATE questions SET current_version_id=v WHERE id=NEW.id;
 RETURN NEW;
END $$;
DROP TRIGGER IF EXISTS practice_question_version ON questions;
CREATE TRIGGER practice_question_version AFTER INSERT OR UPDATE ON questions FOR EACH ROW EXECUTE FUNCTION practice_snapshot_question();
UPDATE questions SET current_version_id=NULL WHERE current_version_id IS NULL;
CREATE TABLE IF NOT EXISTS import_jobs(id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),created_by integer NOT NULL REFERENCES users,parser_type text NOT NULL,source_name text NOT NULL,source_path text,status text NOT NULL DEFAULT 'preview',created_at timestamptz DEFAULT now(),confirmed_at timestamptz);
CREATE TABLE IF NOT EXISTS import_items(id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),job_id uuid REFERENCES import_jobs,sequence integer NOT NULL,draft jsonb NOT NULL,validation jsonb NOT NULL DEFAULT '{}',duplicate_candidates jsonb DEFAULT '[]',decision text DEFAULT 'import',result_question_id integer REFERENCES questions);
CREATE TABLE IF NOT EXISTS assignments(id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),created_by integer NOT NULL REFERENCES users,title text NOT NULL,instructions text DEFAULT '',config jsonb NOT NULL,kind text NOT NULL CHECK(kind IN('fixed','dynamic')),fixed_versions uuid[] DEFAULT '{}',share_token text UNIQUE NOT NULL,opens_at timestamptz,closes_at timestamptz,max_attempts integer CHECK(max_attempts>0),allow_after_deadline boolean DEFAULT false,status text NOT NULL DEFAULT 'active',created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS assignment_targets(id bigserial PRIMARY KEY,assignment_id uuid REFERENCES assignments,class_id integer REFERENCES classes,student_id integer REFERENCES student_profiles(user_id),CHECK((class_id IS NULL)<>(student_id IS NULL)));
CREATE TABLE IF NOT EXISTS attempts(id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),student_id integer NOT NULL REFERENCES student_profiles(user_id),assignment_id uuid REFERENCES assignments,retry_of uuid REFERENCES attempts,source text NOT NULL CHECK(source IN('self_practice','teacher_assigned','retry')),mode text NOT NULL CHECK(mode IN('practice','challenge')),config jsonb NOT NULL,status text NOT NULL DEFAULT 'in_progress' CHECK(status IN('in_progress','completed','abandoned')),started_at timestamptz NOT NULL DEFAULT now(),completed_at timestamptz,score numeric,denominator integer,percentage numeric,duration_seconds integer,seed text NOT NULL);
CREATE TABLE IF NOT EXISTS attempt_items(id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),attempt_id uuid NOT NULL REFERENCES attempts,question_version_id uuid NOT NULL REFERENCES question_versions,question_id integer NOT NULL REFERENCES questions,sequence integer NOT NULL,selection_reason text NOT NULL,first_viewed_at timestamptz,response jsonb,first_response jsonb,is_final boolean NOT NULL DEFAULT false,uncertain boolean NOT NULL DEFAULT false,skipped boolean NOT NULL DEFAULT false,grade_result jsonb,saved_at timestamptz,UNIQUE(attempt_id,question_id),UNIQUE(attempt_id,sequence));
CREATE TABLE IF NOT EXISTS mastery_events(id bigserial PRIMARY KEY,student_id integer NOT NULL REFERENCES student_profiles(user_id),attempt_id uuid NOT NULL REFERENCES attempts,topic_id integer NOT NULL REFERENCES topics,cognitive_level integer NOT NULL CHECK(cognitive_level BETWEEN 1 AND 4),score numeric NOT NULL,question_ids integer[] NOT NULL,algorithm text NOT NULL DEFAULT 'decay-v1',occurred_at timestamptz NOT NULL DEFAULT now(),UNIQUE(attempt_id,topic_id,cognitive_level));
CREATE TABLE IF NOT EXISTS mastery_states(student_id integer REFERENCES student_profiles(user_id),topic_id integer REFERENCES topics,cognitive_level integer NOT NULL,mastery_score numeric NOT NULL,state jsonb NOT NULL,updated_at timestamptz DEFAULT now(),PRIMARY KEY(student_id,topic_id,cognitive_level));
CREATE TABLE IF NOT EXISTS system_settings(key text PRIMARY KEY,value jsonb NOT NULL,updated_by integer REFERENCES users,updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS practice_audit(id bigserial PRIMARY KEY,actor_id integer REFERENCES users,action text NOT NULL,entity_id text,details jsonb NOT NULL DEFAULT '{}',request_id text,created_at timestamptz DEFAULT now());
CREATE INDEX IF NOT EXISTS attempt_student_time ON attempts(student_id,started_at DESC);
CREATE INDEX IF NOT EXISTS attempt_assignment ON attempts(assignment_id,student_id);
CREATE INDEX IF NOT EXISTS item_attempt ON attempt_items(attempt_id,sequence);
CREATE INDEX IF NOT EXISTS version_selection ON question_versions(subject_id,grade,topic_id,cognitive_level);
CREATE INDEX IF NOT EXISTS events_replay ON mastery_events(student_id,occurred_at,id);
CREATE INDEX IF NOT EXISTS memberships_student ON class_memberships(student_id,class_id);
CREATE INDEX IF NOT EXISTS question_bank_lifecycle ON questions(bank_id,lifecycle);
