import {useEffect,useState} from 'react';
import {Link,useParams} from 'react-router-dom';
import {api} from '../api/client.js';
import {useAuth,hasAnyCapability} from '../hooks/useAuth.js';
import RosterImport from './practice/RosterImport.jsx';
import Configuration from './practice/Configuration.jsx';
import CurriculumManager from './curriculum/CurriculumManager.jsx';
import '../styles/staff.css';
const titles={school:'Năm học & lớp học',curriculum:'Môn học & cấu hình nội dung',banks:'Kho & chính sách',settings:'Cấu hình hệ thống',operations:'Vận hành & nhật ký'};
const settingLabels={metadata_auto_threshold:'Ngưỡng gợi ý metadata (%)',mastery_decay_rate:'Hệ số suy giảm bằng chứng',mastery_threshold:'Ngưỡng thành thạo',confidence_medium_min_effective_questions:'Số câu hiệu lực tối thiểu – tin cậy trung bình',confidence_medium_min_attempts:'Số lượt tối thiểu – tin cậy trung bình',confidence_high_min_effective_questions:'Số câu hiệu lực tối thiểu – tin cậy cao',confidence_high_min_attempts:'Số lượt tối thiểu – tin cậy cao',repeat_confidence_weight:'Trọng số bằng chứng lặp',repeat_credit_cap:'Giới hạn ghi nhận lặp',practice_min_questions:'Số câu luyện tối thiểu',practice_default_questions:'Số câu mặc định',practice_max_questions:'Số câu luyện tối đa',trend_window:'Cửa sổ xu hướng',trend_threshold:'Ngưỡng xu hướng'};
export default function AdminHub(){
 const {section='school'}=useParams(),{user}=useAuth(),[catalog,setCatalog]=useState(null),[settings,setSettings]=useState(null),[initial,setInitial]=useState(null),[ops,setOps]=useState(null),[audit,setAudit]=useState([]),[metrics,setMetrics]=useState(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[form,setForm]=useState({name:'',grade:7,year:''}),[json,setJson]=useState(''),[preview,setPreview]=useState(null);
 const capability={school:['class.manage'],curriculum:['curriculum.manage','curriculum.read','competency.read'],banks:['bank.manage'],settings:['system.config'],operations:['system.config']}[section];
 useEffect(()=>{setError('');if(!hasAnyCapability(user,capability||[])||(section==='operations'&&user.role!=='admin'))return;const load=async()=>{if(section==='school'){const c=await api.get('/api/staff/catalog');setCatalog(c);setForm(f=>({...f,year:c.years.find(y=>y.active)?.name||c.years.at(-1)?.name||''}));}if(section==='settings'){const s=await api.get('/api/practice/settings');setSettings(s);setInitial(s);setJson(JSON.stringify(s,null,2));}if(section==='operations'){const [o,a,m]=await Promise.all([api.get('/api/practice/operations'),api.get('/api/practice/audit'),api.get('/api/practice/metrics')]);setOps(o);setAudit(a);setMetrics(m);}};load().catch(e=>setError(e.message));},[section]);
 async function run(fn){setError('');setMessage('');try{await fn();setMessage('Đã lưu.');}catch(e){setError(e.message);}}
 if(!capability||!hasAnyCapability(user,capability)||(section==='operations'&&user.role!=='admin'))return <p role="alert">Không có quyền với mục quản trị này.</p>;
 return <section className="staff-page"><header className="staff-heading"><div><p className="staff-eyebrow">QUẢN TRỊ NHÀ TRƯỜNG</p><h1>{titles[section]}</h1><p>Phân công nhân sự tập trung tại <Link to="/admin/staff">Nhân sự & phân công</Link>.</p></div></header>{error&&<p className="staff-error" role="alert">{error}</p>}{message&&<p className="staff-success" role="status">{message}</p>}
 {section==='school'&&<><RosterImport/><article className="staff-card"><h2>Tạo lớp trong năm học</h2><form onSubmit={e=>{e.preventDefault();run(async()=>{await api.post('/api/practice/classes',form);setCatalog(await api.get('/api/staff/catalog'));setForm({...form,name:''});});}}><div className="staff-fields"><label>Tên lớp<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Khối<select value={form.grade} onChange={e=>setForm({...form,grade:Number(e.target.value)})}>{Array.from({length:12},(_,i)=>i+1).map(n=><option key={n}>{n}</option>)}</select></label><label>Năm học<input required list="school-years" value={form.year} onChange={e=>setForm({...form,year:e.target.value})}/><datalist id="school-years">{catalog?.years.map(y=><option key={y.id} value={y.name}/>)}</datalist></label></div><button className="btn btn-primary">Tạo lớp</button></form></article>{catalog?.years.map(y=><article className="staff-card" key={y.id}><h2>{y.name}</h2><div className="staff-chips">{catalog.classes.filter(c=>c.school_year_id===y.id).map(c=><span key={c.id}>{c.name} · Khối {c.grade}</span>)}</div></article>)}</>}
 {section==='curriculum'?<CurriculumManager/>:section==='banks'&&<Configuration section={section}/>}
 {section==='settings'&&settings&&<article className="staff-card"><h2>Tham số luyện tập & bằng chứng học tập</h2><p>Không thay đổi công thức chấm điểm hoặc chuẩn GDPT 2018. Thay đổi được máy chủ kiểm tra và ghi nhật ký.</p><div className="staff-fields">{Object.entries(settingLabels).filter(([key])=>key in settings).map(([key,title])=><label key={key}>{title}<input type="number" step="any" value={settings[key]} onChange={e=>{setSettings({...settings,[key]:Number(e.target.value)});setPreview(null);}}/></label>)}</div><h3>Tỉ lệ mức độ mặc định</h3>{Object.entries(settings.practice_presets||{}).map(([key,values])=><fieldset className="staff-fields" key={key}><legend>{({basic:'Cơ bản',balanced:'Cân bằng',advanced:'Nâng cao'})[key]||key}</legend>{values.map((v,i)=><label key={i}>{['Nhận biết','Thông hiểu','Vận dụng','Vận dụng cao'][i]} (%)<input type="number" min="0" max="100" value={v} onChange={e=>{setSettings({...settings,practice_presets:{...settings.practice_presets,[key]:values.map((x,n)=>n===i?Number(e.target.value):x)}});setPreview(null);}}/></label>)}</fieldset>)}<div className="staff-save"><button className="btn" onClick={()=>{setSettings(initial);setPreview(null);}}>Khôi phục giá trị đang lưu</button><button className="btn" onClick={()=>setPreview(Object.keys(settings).filter(k=>JSON.stringify(settings[k])!==JSON.stringify(initial[k])))}>Xem thay đổi</button><button className="btn btn-primary" onClick={()=>run(async()=>{await api.put('/api/practice/settings',settings);setInitial(settings);setPreview(null);})}>Lưu cấu hình</button></div>{preview&&<p>{preview.length?'Sẽ cập nhật: '+preview.map(k=>settingLabels[k]||k).join(', '):'Không có thay đổi.'}</p>}<details><summary>Nâng cao · Chỉnh JSON (quản trị hệ thống)</summary><p>Chỉ dùng khi cần đối chiếu toàn bộ cấu hình. Bấm áp dụng để kiểm cú pháp, sau đó xem thay đổi và lưu.</p><textarea rows={15} value={json} onChange={e=>setJson(e.target.value)}/><button className="btn" onClick={()=>run(async()=>{const parsed=JSON.parse(json);if(!parsed||typeof parsed!=='object'||Array.isArray(parsed))throw Error('Cấu hình phải là đối tượng.');setSettings(parsed);setPreview(Object.keys(parsed).filter(k=>JSON.stringify(parsed[k])!==JSON.stringify(initial[k])));})}>Áp dụng vào biểu mẫu</button></details></article>}
 {section==='operations'&&<>{ops&&<article className="staff-card"><h2>Vận hành Pilot</h2><p>Máy chủ hoạt động {Math.floor(ops.uptime_seconds/60)} phút · {ops.connections.total} kết nối DB</p><p>Sao lưu gần nhất: {ops.backup.last_success?new Date(ops.backup.last_success).toLocaleString('vi-VN'):'Chưa ghi nhận'}</p><p>Lỗi yêu cầu: {ops.http?.client_errors||0} lỗi 4xx · {ops.http?.server_errors||0} lỗi 5xx.</p></article>}{metrics&&<article className="staff-card"><h2>Sử dụng & tiến bộ</h2><p>{metrics.activated_students} học sinh kích hoạt · {metrics.students_with_attempts} học sinh đã luyện · {metrics.completed_attempts}/{metrics.started_attempts} lượt hoàn thành.</p><p>{metrics.improved_students} học sinh có bằng chứng tiến bộ đủ tin cậy. {metrics.retention_note}</p></article>}<article className="staff-card"><h2>Nhật ký gần đây</h2>{audit.map(a=><div className="staff-timeline" key={a.id}><time>{new Date(a.created_at).toLocaleString('vi-VN')}</time><p>{a.full_name} · {a.action}</p></div>)}</article></>}
 </section>;
}
