import {useEffect,useState} from 'react';
import {api} from '../api/client.js';
const names={READ_ONLY:'Chỉ đọc',AUTHOR:'Biên soạn',AUTHOR_REVIEWER:'Biên soạn & rà soát',PROFESSIONAL_MANAGER:'Quản lý chuyên môn',FULL_SCOPE:'Đầy đủ nghiệp vụ trong phạm vi'};
export function PermissionTools({catalog,rows,staffId,ScopeField,label,onSaved}){
 const [selected,setSelected]=useState(staffId?[Number(staffId)]:[]),[bundle,setBundle]=useState('READ_ONLY'),[keys,setKeys]=useState(null),[scope,setScope]=useState({scope_type:'SUBJECT',scope_payload:{}}),[effect,setEffect]=useState('ALLOW'),[reason,setReason]=useState(''),[confirmed,setConfirmed]=useState(false),[preview,setPreview]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const [templates,setTemplates]=useState([]),[templateName,setTemplateName]=useState(''),[validTo,setValidTo]=useState(null);
 useEffect(()=>{if(catalog?.can_manage_permissions)api.get('/api/staff/permission-templates').then(setTemplates).catch(e=>setError(e.message));},[catalog?.can_manage_permissions]);
 if(!catalog?.bundles)return null;
 const chosen=keys||catalog.bundles[bundle],change=fn=>{fn();setPreview(null);setConfirmed(false);setMessage('');};
 const payload={user_ids:selected,bundle,capabilities:chosen,...scope,effect,reason,confirmed,valid_to:validTo};
 async function run(fn){setBusy(true);setError('');try{await fn();}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <details className="staff-card"><summary>Sửa quyền chi tiết theo nhóm · Ngoại lệ tùy chọn</summary><p>Quyền theo vị trí đã có sẵn. Chỉ dùng phần này để bổ sung hoặc từ chối quyền trong phạm vi riêng. “Đầy đủ nghiệp vụ” bao gồm quyền đặc biệt nhạy cảm; chỉ Admin được cấp với lý do và xác nhận. Quản lý nhân sự dùng phạm vi tổ/toàn trường; cấu hình dùng toàn trường.</p>{error&&<p role="alert" className="staff-error">{error}</p>}{message&&<p role="status">{message}</p>}
 <label>Mẫu quyền đã lưu<select defaultValue="" onChange={e=>{const t=templates.find(t=>t.id===Number(e.target.value));if(t)change(()=>{setBundle(t.definition.bundle);setKeys(t.definition.capabilities);setScope({scope_type:t.definition.scope_type,scope_payload:t.definition.scope_payload});setEffect(t.definition.effect);setValidTo(t.definition.valid_to);});}}><option value="">Chọn mẫu (không tự cấp quyền)</option>{templates.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label>
 {!staffId&&<fieldset className="staff-checks"><legend>Nhân sự nhận ngoại lệ</legend>{rows.filter(r=>r.role!=='admin'&&r.is_active).map(r=><label key={r.id}><input type="checkbox" checked={selected.includes(r.id)} onChange={e=>change(()=>setSelected(e.target.checked?[...selected,r.id]:selected.filter(id=>id!==r.id)))}/>{r.full_name}</label>)}</fieldset>}
 <div className="staff-fields"><label>Nhóm quyền<select value={bundle} onChange={e=>change(()=>{setBundle(e.target.value);setKeys(null);})}>{Object.entries(names).map(([k,n])=><option key={k} value={k}>{n}</option>)}</select></label><label>Áp dụng<select value={effect} onChange={e=>change(()=>setEffect(e.target.value))}><option value="ALLOW">Cho phép bổ sung</option><option value="DENY">Từ chối rõ ràng</option></select></label></div>
 <details><summary>Tùy chỉnh các quyền trong nhóm ({chosen.length})</summary><div className="staff-checks">{catalog.capabilities.filter(k=>!catalog.non_delegable.includes(k)).map(k=><label key={k}><input type="checkbox" checked={chosen.includes(k)} onChange={e=>change(()=>setKeys(e.target.checked?[...chosen,k]:chosen.filter(x=>x!==k)))}/>{label(k)}</label>)}</div></details>
 <ScopeField value={scope} onChange={v=>change(()=>setScope(v))} catalog={catalog}/><label>Lý do ngoại lệ<textarea value={reason} onChange={e=>change(()=>setReason(e.target.value))}/></label>
 <label>Hết hiệu lực (tùy chọn)<input type="date" value={validTo||''} onChange={e=>change(()=>setValidTo(e.target.value||null))}/></label><details><summary>Lưu cấu hình thành mẫu quyền</summary><label>Tên mẫu<input value={templateName} onChange={e=>setTemplateName(e.target.value)}/></label><button className="btn" disabled={busy||templateName.trim().length<3||reason.trim().length<3} onClick={()=>run(async()=>{await api.post('/api/staff/permission-templates',{name:templateName,definition:{bundle,capabilities:chosen,...scope,effect,valid_to:validTo},reason});setTemplates(await api.get('/api/staff/permission-templates'));setMessage('Đã lưu mẫu; chưa cấp quyền cho ai.');})}>Lưu mẫu</button></details>
 <button className="btn" disabled={busy||!selected.length||!chosen.length||reason.trim().length<3} onClick={()=>run(async()=>setPreview(await api.post('/api/staff/bundle-preview',payload)))}>Xem trước tác động nhóm quyền</button>
 {preview&&<div><p>{preview.items.length} nhân sự · {preview.capabilities.length} quyền trong phạm vi đã chọn</p>{preview.items.map(i=><p key={i.user_id}>{rows?.find(r=>r.id===i.user_id)?.full_name||'Nhân sự hiện tại'}: thêm {i.gained.length}, thu hẹp {i.lost.length} quyền</p>)}{preview.high_risk.length>0&&<label><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>Tôi xác nhận cấp quyền nhạy cảm: {preview.high_risk.map(label).join('; ')}</label>}
 <button className="btn btn-primary" disabled={busy||preview.high_risk.length>0&&!confirmed} onClick={()=>run(async()=>{await api.put('/api/staff/bundle-apply',{...payload,versions:Object.fromEntries(preview.items.map(i=>[i.user_id,i.access_version]))});setPreview(null);setMessage('Đã áp dụng nguyên tử và ghi nhật ký từng nhân sự.');await onSaved();})}>Xác nhận áp dụng nhóm quyền</button></div>}
 </details>;
}
export function CopyStaff({staffId,year,onSaved}){
 const [rows,setRows]=useState([]),[source,setSource]=useState(''),[positions,setPositions]=useState(true),[overrides,setOverrides]=useState(false),[reason,setReason]=useState('Sao chép phân công cho nhân sự cùng nhiệm vụ'),[preview,setPreview]=useState(null),[confirmed,setConfirmed]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{api.get('/api/staff').then(setRows).catch(e=>setError(e.message));},[]);
 const payload={source_user_id:Number(source),school_year_id:year,include_positions:positions,include_overrides:overrides,reason,confirmed};
 async function run(fn){setBusy(true);setError('');try{await fn();}catch(e){setError(e.message);}finally{setBusy(false);}}
 const change=fn=>{fn();setPreview(null);setConfirmed(false);};
 return <details className="staff-card"><summary>Sao chép quyền từ nhân sự khác</summary><p>Giữ phân công hiện có ở đích. Không sao chép trạng thái quản trị, phân công hết hạn hoặc ngoại lệ tạm thời. Ngoại lệ không được chọn sẵn.</p>{error&&<p role="alert" className="staff-error">{error}</p>}<label>Nhân sự nguồn<select value={source} onChange={e=>change(()=>setSource(e.target.value))}><option value="">Chọn nhân sự</option>{rows.filter(r=>r.id!==Number(staffId)&&r.role!=='admin'&&r.is_active).map(r=><option key={r.id} value={r.id}>{r.full_name}</option>)}</select></label>
 <label><input type="checkbox" checked={positions} onChange={e=>change(()=>setPositions(e.target.checked))}/>Vị trí và môn × lớp trong năm học đang xem</label><label><input type="checkbox" checked={overrides} onChange={e=>change(()=>setOverrides(e.target.checked))}/>Ngoại lệ dài hạn (ALLOW / DENY)</label><label>Lý do<input value={reason} onChange={e=>change(()=>setReason(e.target.value))}/></label>
 <button className="btn" disabled={busy||!source||!positions&&!overrides} onClick={()=>run(async()=>setPreview(await api.post(`/api/staff/${staffId}/copy-staff-preview`,payload)))}>Xem trước sao chép</button>
 {preview&&<div><p>Phân công: thêm phạm vi {preview.preview.gained.length} quyền, thu hẹp {preview.preview.lost.length}. Sao chép {preview.overrides.length} ngoại lệ.</p>{preview.high_risk.length>0&&<label><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>Xác nhận sao chép ngoại lệ nhạy cảm</label>}<button className="btn btn-primary" disabled={busy||preview.high_risk.length>0&&!confirmed} onClick={()=>run(async()=>{await api.put(`/api/staff/${staffId}/copy-staff`,{...payload,source_version:preview.source_version,target_version:preview.target_version});setPreview(null);await onSaved();})}>Xác nhận sao chép</button></div>}</details>;
}
