import {BulkTeaching,CopyYear} from './StaffTools.jsx';
import {PermissionTools,CopyStaff} from './StaffPermissionTools.jsx';
import {useEffect,useState} from 'react';
import {Link,useNavigate,useParams} from 'react-router-dom';
import {api} from '../api/client.js';
import {useAuth,hasCapability} from '../hooks/useAuth.js';
import '../styles/staff.css';
const ROOT='/api/staff';
const domainLabels={student:'Tài khoản học sinh',learning:'Học tập & hồ sơ',content:'Ngân hàng nội dung',question_quality:'Chất lượng câu hỏi',coverage:'Độ phủ chương trình',assignment:'Giao bài',matrix:'Ma trận',exam:'Đề kiểm tra',bank:'Kho câu hỏi',curriculum:'Chương trình GDPT 2018',analytics:'Phân tích',staff:'Nhân sự',class:'Lớp học',audit:'Nhật ký',security:'Bảo mật',system:'Hệ thống'};
const actionLabels={read:'Xem',manage_basic:'Sửa thông tin cơ bản',reset_password:'Đặt lại mật khẩu',transfer:'Chuyển lớp',disable:'Khóa tài khoản',read_attempt:'Xem bài làm',read_all_subjects:'Xem học tập mọi môn',read_subject:'Xem học tập theo môn',write:'Biên soạn',create_version:'Tạo phiên bản',review:'Rà soát',approve:'Phê duyệt',export:'Xuất dữ liệu',export_answers:'Xuất đáp án',view_answer:'Xem đáp án',download_source:'Tải nguồn',create:'Tạo mới',manage:'Quản lý',lock:'Khóa ma trận',generate:'Sinh đề',manage_lessons:'Quản lý bài học',manage_standards:'Quản lý chuẩn',propose_mapping:'Đề xuất liên kết',publish:'Công bố',manage_membership:'Quản lý thành viên',config:'Cấu hình'};
const label=key=>{const [d,a]=key.split('.');return `${domainLabels[d]||d} · ${actionLabels[a]||a}`;};
const scopeLabels={WHOLE_SCHOOL:'Toàn trường',SCHOOL_LEVEL:'Theo cấp học',GRADE:'Theo khối',DEPARTMENT:'Theo tổ chuyên môn',SUBJECT:'Theo môn',CLASS:'Theo lớp',BANK:'Theo kho',CUSTOM:'Kết hợp phạm vi'};
const typeScope={HOMEROOM:'CLASS',DEPT_LEADER:'DEPARTMENT',GRADE_LEADER:'GRADE',BOARD:'WHOLE_SCHOOL',BOARD_PROFESSIONAL:'WHOLE_SCHOOL'};
function ErrorBox({error}){return error?<p role="alert" className="staff-error">{error}</p>:null;}
function Checks({title,options,values=[],onChange}){return <fieldset className="staff-checks"><legend>{title}</legend>{options.length?options.map(o=><label key={o.id}><input type="checkbox" checked={values.includes(o.id)} onChange={e=>onChange(e.target.checked?[...values,o.id]:values.filter(x=>x!==o.id))}/><span>{o.name}</span></label>):<p className="staff-muted">Chưa có dữ liệu trong năm học này.</p>}</fieldset>;}
function Scope({value,onChange,catalog,yearId,allowType=true}){
 const p=value.scope_payload||{},set=(key,v)=>{const next={...p};if(value.scope_type==='CUSTOM'&&Array.isArray(v)&&!v.length)delete next[key];else next[key]=v;onChange({...value,scope_payload:next});},type=value.scope_type;
 return <div className="staff-scope">{allowType&&<label>Phạm vi<select value={type} onChange={e=>onChange({...value,scope_type:e.target.value,scope_payload:{}})}>{Object.entries(scopeLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>}
 {['SCHOOL_LEVEL','CUSTOM'].includes(type)&&<label>Cấp học<select value={p.school_level||''} onChange={e=>{const next={...p};if(e.target.value)next.school_level=e.target.value;else delete next.school_level;onChange({...value,scope_payload:next});}}><option value="">Chọn cấp học</option><option value="THCS">THCS · Khối 6–9</option><option value="THPT">THPT · Khối 10–12</option></select></label>}
 {['GRADE','CUSTOM'].includes(type)&&<Checks title="Khối" options={Array.from({length:7},(_,i)=>({id:i+6,name:'Khối '+(i+6)}))} values={p.grade_ids} onChange={v=>set('grade_ids',v)}/>}
 {['DEPARTMENT','CUSTOM'].includes(type)&&<Checks title="Tổ chuyên môn" options={catalog.departments} values={p.department_ids} onChange={v=>set('department_ids',v)}/>}
 {['SUBJECT','CUSTOM'].includes(type)&&<Checks title="Môn học" options={catalog.subjects} values={p.subject_ids} onChange={v=>set('subject_ids',v)}/>}
 {['CLASS','CUSTOM'].includes(type)&&<Checks title="Lớp phụ trách" options={catalog.classes.filter(c=>!yearId||c.school_year_id===Number(yearId)).map(c=>({...c,name:c.name+' · Khối '+c.grade}))} values={p.class_ids} onChange={v=>set('class_ids',v)}/>}
 {type==='BANK'&&<Checks title="Kho" options={catalog.banks} values={p.bank_ids} onChange={v=>set('bank_ids',v)}/>}
 {type==='WHOLE_SCHOOL'&&<p className="staff-note">Phạm vi toàn trường. Chức danh vẫn quyết định được làm gì; BGH mặc định chỉ đọc, không tự có quyền duyệt.</p>}
 </div>;
}
function scopeText(p,c){const data=p.scope_payload||{},parts=[];if(p.scope_type==='WHOLE_SCHOOL')parts.push('Toàn trường');if(data.school_level)parts.push(data.school_level);for(const [key,rows] of [['class_ids',c.classes],['subject_ids',c.subjects],['department_ids',c.departments],['bank_ids',c.banks]])if(data[key]?.length)parts.push(data[key].map(id=>rows.find(r=>r.id===id)?.name||'Đã ngừng sử dụng').join(', '));if(data.grade_ids?.length)parts.push('Khối '+data.grade_ids.join(', '));return parts.join(' · ')||'Chưa chọn phạm vi';}
export default function Staff(){
 const {user}=useAuth(),nav=useNavigate(),[rows,setRows]=useState([]),[catalog,setCatalog]=useState(null),[error,setError]=useState(''),[search,setSearch]=useState(''),[department,setDepartment]=useState(''),[position,setPosition]=useState(''),[status,setStatus]=useState(''),[override,setOverride]=useState(false),[scopeFilter,setScopeFilter]=useState({subject:'',class:'',grade:''}),[newAccount,setNewAccount]=useState(false),[form,setForm]=useState({username:'',full_name:'',email:'',password:'',department_id:null});
 useEffect(()=>{if(hasCapability(user,'staff.manage'))Promise.all([api.get(ROOT),api.get(ROOT+'/catalog')]).then(([r,c])=>{setRows(r);setCatalog(c);}).catch(e=>setError(e.message));},[user]);
 if(!hasCapability(user,'staff.manage'))return <p role="alert">Bạn không có quyền quản lý nhân sự.</p>;
 const visible=rows.filter(r=>(r.full_name+' '+r.username).toLocaleLowerCase('vi').includes(search.toLocaleLowerCase('vi'))&&(!department||r.department_id===Number(department))&&(!position||r.position_labels.includes(position))&&(!status||r.is_active===(status==='active'))&&(!override||r.has_override)&&Object.entries(scopeFilter).every(([key,id])=>!id||(r.role==='admin'||r.scopes?.some(s=>{const p=s.scope_payload;if(s.scope_type==='WHOLE_SCHOOL')return true;if(key==='subject')return p.subject_ids?.includes(Number(id))||p.department_ids?.includes(catalog?.subjects.find(s=>s.id===Number(id))?.department_id);if(key==='class')return p.class_ids?.includes(Number(id))||p.grade_ids?.includes(catalog?.classes.find(c=>c.id===Number(id))?.grade);return p.grade_ids?.includes(Number(id))||p.class_ids?.some(cid=>catalog?.classes.find(c=>c.id===cid)?.grade===Number(id));}))));
 async function create(e){e.preventDefault();setError('');try{const row=await api.post(ROOT,form);nav('/admin/staff/'+row.id);}catch(e){setError(e.message);}}
 return <section className="staff-page"><header className="staff-heading"><div><p className="staff-eyebrow">QUẢN TRỊ NHÀ TRƯỜNG</p><h1>Nhân sự & phân công</h1><p>Mỗi người một hồ sơ. Chọn công việc và phạm vi phụ trách, hệ thống tổng hợp quyền.</p></div><button className="btn btn-primary" onClick={()=>setNewAccount(!newAccount)}>+ Thêm nhân sự</button></header><ErrorBox error={error}/>
 {newAccount&&<form className="staff-card" onSubmit={create}><h2>Tạo tài khoản nhân sự</h2><p className="staff-muted">Tài khoản mới chưa có quyền nghiệp vụ. Phân công vị trí sau khi tạo.</p><div className="staff-fields">{[['full_name','Họ và tên'],['username','Tên đăng nhập'],['email','Email'],['password','Mật khẩu tạm']].map(([k,l])=><label key={k}>{l}<input type={k==='password'?'password':k==='email'?'email':'text'} autoComplete="off" required={k!=='email'} minLength={k==='password'?12:undefined} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}<label>Tổ công tác chính<select value={form.department_id||''} onChange={e=>setForm({...form,department_id:Number(e.target.value)||null})}><option value="">Chưa xác định</option>{catalog?.departments.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label></div><p>Tổ công tác là thông tin hồ sơ, không tự cấp quyền.</p><button className="btn btn-primary">Tạo & phân công</button></form>}
 {catalog?.can_manage_permissions&&<><PermissionTools rows={rows} catalog={catalog} ScopeField={Scope} label={label} onSaved={async()=>setRows(await api.get(ROOT))}/><BulkTeaching ScopeField={Scope} rows={rows} catalog={catalog} onSaved={async()=>setRows(await api.get(ROOT))}/></>}<div className="staff-toolbar"><label>Tìm nhân sự<input placeholder="Tên hoặc tên đăng nhập…" value={search} onChange={e=>setSearch(e.target.value)}/></label><label>Tổ<select value={department} onChange={e=>setDepartment(e.target.value)}><option value="">Tất cả tổ</option>{catalog?.departments.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label>Vị trí<select value={position} onChange={e=>setPosition(e.target.value)}><option value="">Tất cả vị trí</option>{catalog&&Object.values(catalog.position_labels).map(l=><option key={l}>{l}</option>)}</select></label><label>Trạng thái<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Tất cả</option><option value="active">Đang hoạt động</option><option value="locked">Đã khóa</option></select></label><label className="staff-inline"><input type="checkbox" checked={override} onChange={e=>setOverride(e.target.checked)}/>Có ngoại lệ</label></div>
 <details className="staff-card"><summary>Lọc thêm theo phạm vi phụ trách</summary><div className="staff-fields">{[['subject','Môn',catalog?.subjects||[]],['class','Lớp',catalog?.classes||[]],['grade','Khối',[6,7,8,9,10,11,12].map(id=>({id,name:'Khối '+id}))]].map(([k,l,rows])=><label key={k}>{l}<select value={scopeFilter[k]} onChange={e=>setScopeFilter({...scopeFilter,[k]:e.target.value})}><option value="">Tất cả</option>{rows.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label>)}</div></details><p className="staff-muted">{visible.length} nhân sự · Quyền được kiểm lại trên máy chủ ở mỗi yêu cầu.</p><div className="staff-list">{visible.map(r=><Link className="staff-person" key={r.id} to={'/admin/staff/'+r.id}><span className="staff-avatar">{r.full_name.trim().split(' ').at(-1)?.slice(0,1)}</span><div><h2>{r.full_name}</h2><p>{r.username} · {r.department_name||'Chưa có tổ chính'}</p><div className="staff-chips">{(r.role==='admin'?['Quản trị hệ thống']:r.position_labels).map(p=><span key={p}>{p}</span>)}{r.has_override&&<span>Ngoại lệ</span>}</div>{r.warnings.map(w=><p className="staff-warning" key={w}>{w}</p>)}</div><span className={'staff-status '+(!r.is_active?'locked':'')}>{r.is_active?'Hoạt động':'Đã khóa'}</span><span aria-hidden="true">→</span></Link>)}</div></section>;
}
export function StaffDetail(){
 const {id}=useParams(),{user,refreshMe}=useAuth(),[catalog,setCatalog]=useState(null),[data,setData]=useState(null),[draft,setDraft]=useState(null),[tab,setTab]=useState('positions'),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[preview,setPreview]=useState(null),[explanation,setExplanation]=useState(null),[context,setContext]=useState({}),[override,setOverride]=useState({capability:'content.approve',effect:'PRESET',scope_type:'SUBJECT',scope_payload:{},reason:'',confirmed:false}),[profile,setProfile]=useState(null),[password,setPassword]=useState(''),[bankEdit,setBankEdit]=useState({bank_id:'',permission:'read',reason:'',valid_to:null,confirmed:false});
 async function load(year){const [c,d]=await Promise.all([api.get(ROOT+'/catalog'),api.get(`${ROOT}/${id}/access${year?'?school_year_id='+year:''}`)]);setCatalog(c);setData(d);if(!c.can_manage_permissions)setTab('profile');setDraft(d.editable);setProfile({full_name:d.user.full_name,email:d.user.email||'',department_id:d.user.department_id,is_active:d.user.is_active,reason:'Cập nhật hồ sơ nhân sự'});setPreview(null);}
 useEffect(()=>{if(hasCapability(user,'staff.manage'))load().catch(e=>setError(e.message));},[id]);
 async function run(fn){setBusy(true);setError('');setMessage('');try{await fn();}catch(e){setError(e.message);}finally{setBusy(false);}}
 function update(next){setDraft(next);setPreview(null);}
 const setPosition=(type,p,index=null)=>update({...draft,positions:index===null?[...draft.positions.filter(x=>x.type!==type),...(p?[p]:[])]:draft.positions.flatMap((x,i)=>i===index?(p?[p]:[]):[x])});
 if(!hasCapability(user,'staff.manage'))return <p role="alert">Bạn không có quyền quản lý nhân sự.</p>;
 if(!data||!catalog||!draft)return <section className="staff-page"><ErrorBox error={error}/><p>Đang mở hồ sơ…</p></section>;
 const tabs=[['profile','Hồ sơ'],['positions','Vị trí & phạm vi'],['effective','Quyền hiệu lực'],['banks','Kho'],['history','Lịch sử']].filter(([key])=>catalog.can_manage_permissions||['profile','history'].includes(key));
 return <section className="staff-page"><Link to="/admin/staff">← Danh sách nhân sự</Link><header className="staff-heading"><div><p className="staff-eyebrow">HỒ SƠ NHÂN SỰ</p><h1>{data.user.full_name}</h1><p>{data.user.username} · {data.user.is_active?'Đang hoạt động':'Đã khóa'}{!data.user.access_managed?' · Đang dùng quyền tương thích':''}</p></div><div className="staff-chips">{data.summary.position_labels.map(l=><span key={l}>{l}</span>)}</div></header><nav className="staff-tabs" aria-label="Hồ sơ nhân sự">{tabs.map(([k,l])=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k)}>{l}</button>)}</nav><ErrorBox error={error}/>{message&&<p className="staff-success" role="status">{message}</p>}
 {tab==='positions'&&<><div className="staff-card staff-year"><label>Năm học<select aria-label="Năm học" value={draft.school_year_id||''} onChange={e=>run(()=>load(e.target.value))}>{catalog.years.map(y=><option key={y.id} value={y.id}>{y.name}</option>)}</select></label><p>Vị trí + phạm vi = quyền hiệu lực. Gỡ một vị trí chỉ thu hồi quyền của vị trí đó; các vị trí khác vẫn giữ nguyên.</p></div>
 <CopyStaff staffId={id} year={draft.school_year_id} onSaved={()=>load(draft.school_year_id)}/><CopyYear key={id} staffId={id} catalog={catalog} currentYear={draft.school_year_id} onReady={r=>{setDraft(r.draft);setPreview(r.preview);setMessage('Đã tạo bản nháp cho năm đích; kiểm tra rồi bấm Lưu phân công.');}}/><article className="staff-card"><h2>Giáo viên bộ môn</h2><p>Chọn lớp riêng cho từng môn. Quyền mặc định tự áp dụng: biên soạn theo môn × khối của các lớp được phân công; xem học tập theo đúng môn × lớp. Chưa chọn lớp thì chưa có quyền. Không tự cấp xuất dữ liệu hoặc tải nguồn.</p>{draft.teaching.map((t,index)=><div className="staff-teaching" key={index}><label>Môn giảng dạy<select aria-label={'Môn giảng dạy '+(index+1)} value={t.subject_id} onChange={e=>update({...draft,teaching:draft.teaching.map((x,i)=>i===index?{...x,subject_id:Number(e.target.value)}:x)})}>{catalog.subjects.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><Checks title="Các lớp dạy môn này" options={catalog.classes.filter(c=>c.school_year_id===draft.school_year_id)} values={t.class_ids} onChange={v=>update({...draft,teaching:draft.teaching.map((x,i)=>i===index?{...x,class_ids:v}:x)})}/><details><summary>Thời hạn giảng dạy</summary><div className="staff-fields">{[['valid_from','Từ ngày'],['valid_to','Đến ngày']].map(([key,title])=><label key={key}>{title}<input type="date" value={t[key]||''} onChange={e=>update({...draft,teaching:draft.teaching.map((x,i)=>{if(i!==index)return x;const next={...x};if(e.target.value)next[key]=e.target.value;else delete next[key];return next;})})}/></label>)}</div></details><button className="btn" onClick={()=>update({...draft,teaching:draft.teaching.filter((_,i)=>i!==index)})}>Gỡ môn này</button></div>)}<button className="btn" onClick={()=>update({...draft,teaching:[...draft.teaching,{subject_id:catalog.subjects[0]?.id,class_ids:[]}]})}>+ Thêm môn giảng dạy</button></article>
 {Object.entries(typeScope).map(([type,scope_type])=>{const positions=draft.positions.map((p,index)=>({p,index})).filter(x=>x.p.type===type);return <article className="staff-card" key={type}><label className="staff-position-toggle"><input type="checkbox" checked={!!positions.length} onChange={e=>setPosition(type,e.target.checked?{type,scope_type,scope_payload:{}}:null)}/><span>{catalog.position_labels[type]}</span></label>{positions.map(({p,index})=><div className="staff-override" key={index}>{['DEPT_LEADER','BOARD','BOARD_PROFESSIONAL'].includes(type)&&<label><input type="checkbox" checked={!!(p.school_year_id||p.scope_payload?.school_year_id)} onChange={e=>{const payload={...p.scope_payload};delete payload.school_year_id;const next={...p,scope_payload:payload,school_year_id:e.target.checked?draft.school_year_id:null};delete next.valid_from;delete next.valid_to;setPosition(type,next,index);}}/>Giới hạn bổ nhiệm theo năm học đang chọn (không bắt buộc)</label>}<Scope value={p} onChange={v=>setPosition(type,v,index)} catalog={catalog} yearId={draft.school_year_id} allowType={['BOARD','BOARD_PROFESSIONAL'].includes(type)}/><details><summary>Thời hạn riêng (không bắt buộc)</summary><div className="staff-fields"><label>Từ ngày<input type="date" value={p.valid_from||''} onChange={e=>{const next={...p};if(e.target.value)next.valid_from=e.target.value;else delete next.valid_from;setPosition(type,next,index);}}/></label><label>Đến ngày<input type="date" value={p.valid_to||''} onChange={e=>setPosition(type,{...p,valid_to:e.target.value||null},index)}/></label></div></details>{positions.length>1&&<button className="btn" onClick={()=>setPosition(type,null,index)}>Gỡ phạm vi này</button>}</div>)}{positions.length>0&&<button className="btn" onClick={()=>update({...draft,positions:[...draft.positions,{type,scope_type,scope_payload:{}}]})}>+ Thêm phạm vi / thời hạn riêng</button>}{type==='HOMEROOM'&&<p className="staff-muted">Được quản lý thông tin cơ bản, đặt lại mật khẩu và xem học tập mọi môn trong lớp. Không có quyền sửa nội dung mọi môn hay chuyển lớp.</p>}</article>;})}
 {draft.positions.some(p=>p.type==='VIEWER')&&<article className="staff-card"><h3>Quyền xem tương thích từ bản cũ</h3><p>Chỉ đọc, không mặc định xem đáp án. Không dùng vị trí này cho phân công mới; chọn đúng chức danh ở trên.</p>{draft.positions.map((p,index)=>p.type==='VIEWER'?<p key={index}>{scopeText(p,catalog)} <button className="btn" onClick={()=>setPosition('VIEWER',null,index)}>Gỡ quyền xem cũ</button></p>:null)}</article>}
 <div className="staff-save"><button className="btn" disabled={busy} onClick={()=>run(async()=>setPreview(await api.post(`${ROOT}/${id}/access-preview`,draft)))}>Xem tác động trước khi lưu</button><button className="btn btn-primary" disabled={busy} onClick={()=>run(async()=>{await api.put(`${ROOT}/${id}/assignments`,draft);await load(draft.school_year_id);await refreshMe();setMessage('Đã lưu phân công. Quyền mới có hiệu lực từ yêu cầu tiếp theo.');})}>Lưu phân công</button></div>
 {preview&&<article className="staff-card"><h2>Tác động thay đổi</h2>{preview.warnings.map(w=><p className="staff-warning" key={w}>{w}</p>)}<div className="staff-columns"><div><h3>Được thêm phạm vi</h3>{preview.gained.map(x=><p key={x.capability}>+ {label(x.capability)}</p>)}</div><div><h3>Bị thu hẹp phạm vi</h3>{preview.lost.map(x=><p key={x.capability}>− {label(x.capability)}</p>)}</div></div><p>Những quyền vẫn được cấp từ vị trí khác không bị thu hồi.</p></article>}</>}
 {tab==='effective'&&<><PermissionTools key={id} staffId={id} catalog={catalog} ScopeField={Scope} label={label} onSaved={()=>load(draft.school_year_id)}/><div className="staff-note">Tổng hợp quyền có ít nhất một phạm vi được phép. Bấm giải thích để kiểm tra tài nguyên cụ thể; quyền tổng hợp không có nghĩa là được phép ở mọi lớp/môn.</div><div className="staff-fields staff-card"><label>Môn để kiểm tra<select value={context.subjectId||''} onChange={e=>setContext({...context,subjectId:Number(e.target.value)||undefined})}><option value="">Chọn môn</option>{catalog.subjects.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Lớp để kiểm tra<select value={context.classId||''} onChange={e=>setContext({...context,classId:Number(e.target.value)||undefined})}><option value="">Chọn lớp</option>{catalog.classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Khối nội dung<select value={context.grade||''} onChange={e=>setContext({...context,grade:Number(e.target.value)||undefined})}><option value="">Chọn khối</option>{[6,7,8,9,10,11,12].map(g=><option key={g}>{g}</option>)}</select></label></div>
 {Object.entries(domainLabels).map(([domain,title])=><details className="staff-card" key={domain}><summary>{title} · {Object.entries(data.summary.capabilities).filter(([k,v])=>k.startsWith(domain+'.')&&v).length} quyền</summary>{catalog.capabilities.filter(k=>k.startsWith(domain+'.')).map(k=><div className="staff-capability" key={k}><span>{data.summary.capabilities[k]?'✓':'—'} {label(k)}</span><button className="btn" onClick={()=>run(async()=>setExplanation(await api.post('/api/access/explain',{user_id:Number(id),capability:k,context})))}>Vì sao?</button></div>)}</details>)}
 {explanation&&<article className="staff-card" role="status"><h3>{label(explanation.capability)}: {explanation.allowed?'Được phép':'Không được phép'}</h3><p>{explanation.reason}</p>{explanation.sources.map((s,i)=><p key={i}>{s.type==='ADMIN'?'Quản trị hệ thống':catalog.position_labels[s.position]||s.type}{s.scope?' · '+scopeText(s.scope,catalog):''}</p>)}{explanation.overrides.map((o,i)=><p key={i}>{o.effect} · {o.reason}</p>)}</article>}
 <details className="staff-card"><summary>Sửa quyền chi tiết · Chỉ khi có ngoại lệ</summary><p>DENY ưu tiên hơn ALLOW và vị trí. Ngoại lệ luôn cần lý do; quyền nhạy cảm cần xác nhận.</p><label>Lý do thêm / thu hồi ngoại lệ<input value={override.reason} onChange={e=>setOverride({...override,reason:e.target.value})}/></label><div className="staff-fields"><label>Quyền<select value={override.capability} onChange={e=>setOverride({...override,capability:e.target.value})}>{catalog.capabilities.filter(k=>!catalog.non_delegable?.includes(k)).map(k=><option key={k} value={k}>{label(k)}</option>)}</select></label><label>Thiết lập<select value={override.effect} onChange={e=>setOverride({...override,effect:e.target.value})}><option value="PRESET">Theo vị trí (không thêm ngoại lệ)</option><option value="ALLOW">Cho phép bổ sung</option><option value="DENY">Từ chối rõ ràng</option></select></label></div>{override.effect!=='PRESET'&&<><Scope value={override} onChange={setOverride} catalog={catalog}/><label>Lý do<textarea value={override.reason} onChange={e=>setOverride({...override,reason:e.target.value})}/></label><label>Hết hiệu lực<input type="date" value={override.valid_to||''} onChange={e=>setOverride({...override,valid_to:e.target.value||null})}/></label>{catalog.high_risk.includes(override.capability)&&override.effect==='ALLOW'&&<label className="staff-inline"><input type="checkbox" checked={override.confirmed} onChange={e=>setOverride({...override,confirmed:e.target.checked})}/>Tôi xác nhận việc cấp quyền nhạy cảm trong phạm vi đã chọn.</label>}<button className="btn" disabled={busy} onClick={()=>run(async()=>{await api.post(`${ROOT}/${id}/capability-overrides`,override);await load(draft.school_year_id);setMessage('Đã thêm ngoại lệ và ghi nhật ký.');})}>Lưu ngoại lệ</button></>}
 {data.overrides.map(o=><div className="staff-override" key={o.id}><p><strong>{o.effect}</strong> · {label(o.capability)} · {scopeText(o,catalog)}</p><p>{o.reason} {o.revoked_at?'· Đã thu hồi':''}</p>{!o.revoked_at&&<button className="btn" onClick={()=>run(async()=>{if(!override.reason.trim())throw Error('Nhập lý do thu hồi trong ô lý do ngoại lệ.');await api.del(`${ROOT}/${id}/capability-overrides/${o.id}`,{reason:override.reason});await load(draft.school_year_id);})}>Thu hồi (trở về theo vị trí)</button>}</div>)}</details></>}
 {tab==='profile'&&<article className="staff-card"><h2>Thông tin tài khoản</h2><div className="staff-fields"><label>Họ và tên<input value={profile.full_name} onChange={e=>setProfile({...profile,full_name:e.target.value})}/></label><label>Email<input type="email" value={profile.email} onChange={e=>setProfile({...profile,email:e.target.value})}/></label><label>Tổ chính<select value={profile.department_id||''} onChange={e=>setProfile({...profile,department_id:Number(e.target.value)||null})}><option value="">Chưa xác định</option>{catalog.departments.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label>Trạng thái<select value={profile.is_active?'active':'locked'} onChange={e=>setProfile({...profile,is_active:e.target.value==='active'})}><option value="active">Hoạt động</option><option value="locked">Khóa</option></select></label></div><label>Lý do thay đổi<input value={profile.reason} onChange={e=>setProfile({...profile,reason:e.target.value})}/></label><button className="btn btn-primary" disabled={busy} onClick={()=>run(async()=>{await api.put(`${ROOT}/${id}/profile`,profile);await load(draft.school_year_id);setMessage('Đã cập nhật hồ sơ.');})}>Lưu hồ sơ</button><hr/><h3>Đặt lại mật khẩu</h3><p>Phiên cũ sẽ hết hiệu lực. Nhân sự phải đổi mật khẩu ở lần đăng nhập tiếp theo.</p><label>Mật khẩu tạm (ít nhất 12 ký tự)<input type="password" autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="btn" disabled={busy||password.length<12} onClick={()=>run(async()=>{await api.post(`${ROOT}/${id}/reset-password`,{password,reason:profile.reason});setPassword('');setMessage('Đã đặt lại mật khẩu và thu hồi phiên cũ.');})}>Đặt lại mật khẩu</button></article>}
 {tab==='banks'&&<><article className="staff-card"><h2>Quyền kho hiệu lực</h2>{data.banks.filter(b=>Object.values(b.permissions).some(p=>p.allowed)).map(b=><div className="staff-override" key={b.id}><h3>{b.name}</h3><p>{Object.entries(b.permissions).filter(([,v])=>v.allowed).map(([k])=>actionLabels[k]).join(' · ')}</p><p className="staff-muted">{b.membership&&!b.membership.revoked_at?'Có ACL cấp riêng':'Suy ra từ vị trí, chủ kho hoặc chính sách đọc kho trường'}</p></div>)}</article><article className="staff-card"><h2>Cấp / thu hồi ACL kho riêng</h2><div className="staff-fields"><label>Kho<select value={bankEdit.bank_id} onChange={e=>setBankEdit({...bankEdit,bank_id:Number(e.target.value)})}><option value="">Chọn kho</option>{catalog.banks.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label>Quyền<select value={bankEdit.permission||'revoke'} onChange={e=>setBankEdit({...bankEdit,permission:e.target.value==='revoke'?null:e.target.value})}><option value="read">Đọc</option><option value="write">Biên soạn</option><option value="review">Rà soát kho (không biên soạn)</option><option value="manage">Quản lý kho (nhạy cảm)</option><option value="revoke">Thu hồi ACL riêng</option></select></label><label>Đến ngày<input type="date" value={bankEdit.valid_to||''} onChange={e=>setBankEdit({...bankEdit,valid_to:e.target.value||null})}/></label></div><label>Lý do<textarea value={bankEdit.reason} onChange={e=>setBankEdit({...bankEdit,reason:e.target.value})}/></label>{bankEdit.permission==='manage'&&<label><input type="checkbox" checked={bankEdit.confirmed} onChange={e=>setBankEdit({...bankEdit,confirmed:e.target.checked})}/>Xác nhận cấp quản lý kho trong phạm vi đã chọn</label>}<button className="btn" disabled={busy||!bankEdit.bank_id} onClick={()=>run(async()=>{const {bank_id,...body}=bankEdit;await api.put(`${ROOT}/${id}/banks/${bank_id}`,body);await load(draft.school_year_id);setMessage('Đã cập nhật ACL kho.');})}>Lưu quyền kho</button></article></>}
 {tab==='history'&&<article className="staff-card"><h2>Lịch sử phân công & quyền</h2><p>Phân công đã thu hồi được giữ lại, không xóa dấu vết.</p>{data.history.length?data.history.map(h=><div className="staff-timeline" key={h.id}><time>{new Date(h.created_at).toLocaleString('vi-VN')}</time><h3>{({POSITION_ASSIGNED:'Giao vị trí',POSITION_REVOKED:'Thu hồi vị trí',TEACHING_ADDED:'Thêm lớp giảng dạy',TEACHING_REMOVED:'Gỡ lớp giảng dạy',STAFF_ASSIGNMENTS_UPDATED:'Cập nhật phân công',CAPABILITY_OVERRIDE_ADDED:'Thêm ngoại lệ',CAPABILITY_OVERRIDE_REMOVED:'Thu hồi ngoại lệ',STAFF_PROFILE_UPDATED:'Sửa hồ sơ',STAFF_PASSWORD_RESET:'Đặt lại mật khẩu',BANK_ACCESS_GRANTED:'Cấp quyền kho',BANK_ACCESS_REVOKED:'Thu hồi quyền kho',STAFF_CREATED:'Tạo tài khoản'})[h.action]||h.action}</h3><p>{h.actor_name} · {h.details?.reason||h.details?.after?.reason||'Thay đổi được ghi nhận'}</p></div>):<p>Chưa có thay đổi được ghi nhận.</p>}</article>}
 </section>;
}
