import {useEffect,useState} from 'react';
import {useSearchParams} from 'react-router-dom';
import {useLoad,base} from '../shared.jsx';
import {usePortfolio,LoadState,AttemptLink,date,duration,result,sourceLabels,statusLabels} from './common.jsx';
export default function AttemptHistory({id,self}){
 const [limit,setLimit]=useState(()=>window.matchMedia('(max-width: 680px)').matches?10:20);useEffect(()=>{const m=window.matchMedia('(max-width: 680px)');const change=()=>setLimit(m.matches?10:20);m.addEventListener('change',change);return()=>m.removeEventListener('change',change);},[]);
 const [params,setParams]=useSearchParams(),catalog=useLoad(base+'/catalog'),assignments=usePortfolio(base+'/students/'+id+'/assignments');
 const keys=['subject_id','topic_id','source','status','from','to','mode','assignment_id','offset'];const q=Object.fromEntries(keys.filter(k=>params.has(k)).map(k=>[k,params.get(k)]));
 const load=usePortfolio(base+'/students/'+id+'/attempts?'+new URLSearchParams({...q,limit,offset:Math.floor(Math.max(0,Number(q.offset)||0)/limit)*limit}));
 function update(k,v){const next=new URLSearchParams(params);next.set('tab','history');next.delete('offset');if(v)next.set(k,v);else next.delete(k);if(k==='subject_id')next.delete('topic_id');setParams(next);}
 const select=(key,label,options)=><label>{label}<select aria-label={label} value={q[key]||''} onChange={e=>update(key,e.target.value)}><option value="">Tất cả</option>{options.map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>;
 return <section><h2>Lịch sử làm bài</h2><div className="portfolio-filters">{select('subject_id','Môn học',catalog.data?.subjects.map(s=>[s.id,s.name])||[])}{select('source','Nguồn lượt luyện',Object.entries(sourceLabels))}{select('status','Trạng thái lượt luyện',Object.entries(statusLabels))}</div><details className="portfolio-advanced"><summary>Bộ lọc nâng cao</summary><div className="portfolio-filters">{select('topic_id','Bài / chuyên đề',catalog.data?.topics.filter(t=>!q.subject_id||t.subject_id===Number(q.subject_id)).map(t=>[t.id,t.name])||[])}{select('assignment_id','Bài được giao',assignments.data?.assignments.map(a=>[a.id,a.title])||[])}{select('mode','Chế độ',[['practice','Luyện tập'],['challenge','Thử sức']])}{['from','to'].map(k=><label key={k}>{k==='from'?'Từ ngày':'Đến ngày'}<input aria-label={k==='from'?'Từ ngày':'Đến ngày'} type="date" value={q[k]||''} onChange={e=>update(k,e.target.value)}/></label>)}</div><div className="practice-actions">{[7,30].map(n=><button className="btn" key={n} onClick={()=>update('from',new Date(Date.now()-(n-1)*86400000).toLocaleDateString('en-CA'))}>{n} ngày gần đây</button>)}<button className="btn" onClick={()=>setParams({tab:'history'})}>Xóa bộ lọc</button></div></details>
 {!load.data?<LoadState load={load}/>:<><p role="status">{load.data.total} lượt phù hợp · trang {Math.floor(load.data.offset/limit)+1}</p>{!load.data.items.length?<div className="learning-empty">Không có lượt luyện phù hợp. Thử đổi bộ lọc hoặc bắt đầu luyện tập.</div>:<><div className="portfolio-history-table"><table><thead><tr><th>Thời gian</th><th>Nội dung</th><th>Nguồn</th><th>Kết quả luyện tập</th><th>Mức</th><th>Thời lượng</th><th/></tr></thead><tbody>{load.data.items.map(a=><tr key={a.id}><td>{date(a.started_at)}<small>{statusLabels[a.status]}</small></td><td><strong>{a.subject_name}</strong><small>{a.topics.map(t=>t.name).join(' · ')}</small>{a.question_count} câu</td><td>{sourceLabels[a.source]}<small>{a.assignment_title}</small>{a.retry_of&&<small>Có lượt gốc liên kết</small>}</td><td>{result(a)}<small>{a.answered_count} đã trả lời · {a.uncertain_count} chưa chắc · {a.skipped_count} bỏ qua</small></td><td>{a.levels.map(n=>'M'+n).join(' · ')}</td><td>{duration(a.duration_seconds)}</td><td><AttemptLink id={id} a={a} self={self}/></td></tr>)}</tbody></table></div><div className="portfolio-history-cards">{load.data.items.map(a=><article className="practice-card" key={a.id}><small>{date(a.started_at)}</small><h3>{a.subject_name}</h3><p>{a.topics.map(t=>t.name).join(' · ')}</p><p>{sourceLabels[a.source]} · {a.mode==='practice'?'Luyện tập':'Thử sức'}</p><strong>{result(a)}</strong><p>{a.question_count} câu · {duration(a.duration_seconds)} · {a.uncertain_count} câu chưa chắc</p><AttemptLink id={id} a={a} self={self}/></article>)}</div></>}
 <div className="practice-actions"><button className="btn" disabled={!load.data.offset} onClick={()=>{const next=new URLSearchParams(params);next.set('offset',Math.max(0,load.data.offset-limit));setParams(next);}}>Trang trước</button><button className="btn" disabled={load.data.offset+limit>=load.data.total} onClick={()=>{const next=new URLSearchParams(params);next.set('offset',load.data.offset+limit);setParams(next);}}>Trang sau</button></div></>}
 </section>;
}
