import {useState} from 'react';
import {Link,useParams} from 'react-router-dom';
import {useAuth} from '../../../hooks/useAuth.js';
import {base,types} from '../shared.jsx';
import {usePortfolio,LoadState,date,duration,result,sourceLabels,portfolioUrl,reviewUrl} from './common.jsx';
const answerText=v=>v==null?'Chưa trả lời':typeof v==='boolean'?(v?'Đúng':'Sai'):typeof v==='object'?Object.entries(v).map(([k,x])=>k+': '+answerText(x)).join('; '):String(v);
const correctText=q=>q.answer?.correct??q.answer?.numeric??q.answer?.reference??q.answer?.aliases?.join(' / ')??answerText(q.answer?.values||q.answer?.pairs);
export default function AttemptReview(){const {user}=useAuth(),{studentId,attemptId}=useParams(),id=studentId||user.id,self=user.role==='student',load=usePortfolio(base+'/students/'+id+'/attempts/'+attemptId),[filter,setFilter]=useState('all'),[expandAll,setExpandAll]=useState(false);if(!load.data)return <section className="practice-page portfolio-page"><h1>Chi tiết lượt luyện</h1><LoadState load={load}/></section>;const a=load.data,items=a.items.filter(i=>filter==='all'||filter==='uncertain'&&i.uncertain||filter==='skipped'&&i.skipped||filter==='incorrect'&&i.result?.score!=null&&i.result.score<1||filter==='M'+i.question.cognitive_level);
 return <section className="practice-page portfolio-page"><Link className="back-link" to={portfolioUrl(id,self)+'?tab=history'}>← Lịch sử của {a.student.full_name}</Link><header className="learning-header"><div><span className="eyebrow">Hồ sơ học tập · Chỉ đọc</span><h1>Chi tiết lượt luyện</h1><p>{a.subject_name} · {date(a.started_at)}</p><p>{a.topics.map(t=>t.name).join(' · ')}</p><p>{sourceLabels[a.source]} · {a.mode==='practice'?'Luyện tập':'Thử sức'} · {a.question_count} câu · {duration(a.duration_seconds)}</p>{a.assignment_title&&<p>Bài giao: {a.assignment_title}</p>}</div><strong className="portfolio-result">{result(a)}</strong></header>
 {a.retry_parent&&<p>Luyện lại từ <Link to={reviewUrl(id,a.retry_parent,self)}>{date(a.retry_parent.started_at)} · {result(a.retry_parent)}</Link></p>}
 {a.status!=='completed'&&<p className="scope-empty">Lượt này chưa hoàn thành. Chưa có kết quả tổng kết hoặc cập nhật thành thạo. Đáp án chưa công bố vẫn được giữ kín.</p>}
 <div className="portfolio-stats">{Object.entries({correct:'Đúng hoàn toàn',partial:'Đúng một phần',incorrect:'Chưa đạt',skipped:'Bỏ qua',uncertain:'Chưa chắc',essay:'Tự luận'}).map(([k,v])=><article key={k}><strong>{a.summary[k]}</strong><span>{v}</span></article>)}</div>
 <button className="btn" aria-pressed={expandAll} onClick={()=>setExpandAll(v=>!v)}>{expandAll?'Chỉ mở câu cần xem lại':'Xem tất cả'}</button><label>Lọc câu trong lượt luyện<select value={filter} onChange={e=>setFilter(e.target.value)}>{Object.entries({all:'Tất cả',incorrect:'Sai / chưa đạt',uncertain:'Chưa chắc',skipped:'Bỏ qua',M1:'M1',M2:'M2',M3:'M3',M4:'M4'}).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>
 {!items.length&&<p>Không có câu phù hợp bộ lọc.</p>}{items.map(i=><details className="practice-card review-question" key={i.id+':'+expandAll} open={expandAll||i.skipped||i.uncertain||(i.result?.score!=null&&i.result.score<1)}><summary>Câu {i.sequence} · {types[i.question.type]} · M{i.question.cognitive_level} · {i.topic_name}{i.skipped?' · Bỏ qua':''}{i.uncertain?' · Chưa chắc':''}{i.result?.score!=null?' · '+Math.round(i.result.score*100)+'%':''}</summary><Rich text={i.question.stem}/>{i.question.image_url&&<img className="question-image" src={i.question.image_url} alt="Hình câu hỏi"/>}{(i.question.options||i.question.statements||[]).map(o=><div key={o.id}><Rich text={o.id+'. '+o.text}/></div>)}{i.question.type==='matching'&&<div className="workspace-grid">{[i.question.left,i.question.right].map((side,k)=><div key={k}>{side?.map(o=><Rich key={o.id} text={o.id+'. '+o.text}/>)}</div>)}</div>}
 <h3>{self?'Bài làm của em':'Bài làm của học sinh'}</h3><Rich text={answerText(i.response)}/>{i.question.answer&&<><h3>Đáp án / tham khảo</h3><Rich text={String(correctText(i.question))}/></>}{!i.question.auto_gradable&&<p>Không tính điểm tự chấm / thành thạo.</p>}{i.result?.details?.length>0&&<><p>{i.result.details.filter(d=>d.correct).length}/{i.result.details.length} ý đúng.</p>{i.result.details.map(d=><p key={d.id}>{d.id}: {d.correct?'Đúng':'Chưa đúng'} · Bài làm {answerText(d.actual)} · Đáp án {answerText(d.expected)}</p>)}</>}{i.question.explanation&&<><h3>Lời giải</h3><Rich text={i.question.explanation}/></>}{!self&&<details className="review-metadata"><summary>Thông tin kỹ thuật</summary><p>Mã câu: {i.question.display_code||i.question_id} · Phiên bản {i.version_number}</p><small>Lý do chọn câu: {{new:'Chưa gặp',repeat:'Luyện lại',assigned:'Bài được giao'}[i.selection_reason]||'Theo cấu hình lượt luyện'} · Lưu gần nhất: {date(i.saved_at)}</small></details>}</details>)}
 </section>;
}
import {Rich} from '../Rich.jsx';
