import {Link} from 'react-router-dom';
import {ProgressChart,confidence,trends,masteryLabel} from '../shared.jsx';
import {AttemptLink,date,result,sourceLabels,duration} from './common.jsx';
export function FocusTopics({states,self,id}){return <div className="workspace-grid">{states.map(s=><article key={s.topic_id+':'+s.cognitive_level} className="portfolio-signal"><h3>{s.topic_name} · M{s.cognitive_level}</h3><strong>{masteryLabel(s)}{s.confidence!=='LOW'&&` · ${Math.round(s.mastery_score)}%`}</strong><p>{s.unique_question_count} câu khác nhau · {s.completed_attempt_count} lượt hoàn thành</p><p>Độ tin cậy: {confidence[s.confidence]} · {trends[s.trend]}</p><Link to={self?`/practice/new?subject=${s.subject_id}&topic=${s.topic_id}&level=${s.cognitive_level}`:`/practice/assignments?student=${id}`}>{self?'Luyện nội dung này':'Tạo bài cho học sinh'} →</Link></article>)}</div>;}
export default function PortfolioOverview({data,id,self}){const s=data.summary;return <div className="portfolio-overview">
 <p className="portfolio-period">Hoạt động tích lũy đến {date(new Date())}. Không phải điểm trung bình hay xếp hạng.</p>
 <div className="portfolio-stats">{[[s.completed_attempts,'Lượt hoàn thành'],[s.answered_questions,'Câu đã trả lời'],[s.unique_questions,'Câu khác nhau'],[duration(s.duration_seconds),'Thời gian luyện']].map(([v,label])=><article key={label}><strong>{v}</strong><span>{label}</span></article>)}</div>
 <details className="portfolio-extra"><summary>Xem thêm chỉ số</summary><p>{s.questions_attempted} câu trong các lượt luyện · {s.active_days} ngày hoạt động · {data.assignment_summary.completed}/{data.assignment_summary.total} bài giao đã hoàn thành</p></details>
 {!s.started_attempts&&<div className="learning-empty"><h2>Chưa có dữ liệu luyện tập</h2><p>{self?'Bắt đầu lượt luyện đầu tiên để xây dựng hồ sơ của em.':'Giao bài hoặc chờ học sinh tự luyện.'}</p>{self&&<Link className="btn primary" to="/practice/new">Bắt đầu tự luyện</Link>}</div>}
 <section className="practice-card"><h2>Điểm nổi bật</h2><p>{data.signals.improving?'Có '+data.signals.improving+' nội dung đang tiến bộ.':'Mỗi lượt hoàn thành bổ sung bằng chứng về quá trình học.'}</p>{data.signals.low_confidence>0&&<p>{data.signals.low_confidence} nội dung cần thêm dữ liệu để xác nhận mức thành thạo.</p>}{(!s.last_practice||Date.now()-new Date(s.last_practice)>7*86400000)&&<p>Chưa có lượt hoàn thành trong 7 ngày gần đây.</p>}<h3>Tiến bộ gần đây</h3><ProgressChart attempts={data.recent_completed_attempts}/></section>
 <section className="portfolio-focus"><h2>Nội dung cần củng cố</h2>{data.signals.focus.length?<FocusTopics states={data.signals.focus} id={id} self={self}/>:<p>Chưa có đủ bằng chứng để xác định nội dung cần củng cố.</p>}</section>
 {data.signals.strong.length>0&&<details className="practice-card"><summary>Thành thạo nổi bật</summary><section><h2>Thành thạo nổi bật</h2><FocusTopics states={data.signals.strong} id={id} self={self}/></section></details>}
 <details className="practice-card"><summary>Mức thành thạo hiện tại</summary><p>Thành thạo ước tính mức nắm vững; độ tin cậy phản ánh bằng chứng; xu hướng cần nhiều lần đo. Không phải điểm kiểm tra.</p>{data.mastery_overview.length?data.mastery_overview.map(t=><p key={t.topic_id}><strong>{t.levels[0]?.topic_name}</strong>: {t.levels.some(s=>s.confidence==='LOW')?'Chưa đủ dữ liệu':Math.round(t.mastery_score)+'%'} {t.provisional?'· tạm tính, chưa đủ M1–M4':''}<br/>{t.levels.map(s=>`M${s.cognitive_level}: ${masteryLabel(s)} · ${s.unique_question_count} câu khác nhau · ${s.completed_attempt_count} lượt`).join(' | ')}</p>):<p>Chưa có dữ liệu thành thạo.</p>}</details>
 <section className="practice-card"><h2>Hoạt động gần đây</h2><ol className="membership-timeline portfolio-activity">{data.recent_activity.map((e,i)=><li key={i}>{date(e.at)}{e.kind==='class'?<p>Lớp {e.membership.class_name} · {e.membership.school_year}{e.membership.current?' · Đang học':' · Lịch sử lớp'}</p>:<><p>{sourceLabels[e.attempt.source]} · {e.attempt.subject_name} · {result(e.attempt)}</p><p>{e.attempt.topics.map(t=>t.name).join(' · ')}</p><AttemptLink id={id} a={e.attempt} self={self}/></>}</li>)}</ol></section>
 </div>;}
