import {useEffect,useState} from 'react';
import {Link,useParams,useSearchParams} from 'react-router-dom';
import {useAuth} from '../../../hooks/useAuth.js';
import {base} from '../shared.jsx';
import {usePortfolio,LoadState,date} from './common.jsx';
import PortfolioOverview from './PortfolioOverview.jsx';
import AttemptHistory from './AttemptHistory.jsx';
import MasteryPortfolio from './MasteryPortfolio.jsx';
import OutcomeMap from './OutcomeMap.jsx';
import CompetencyPortfolio from './CompetencyPortfolio.jsx';
import {AssignmentPortfolio,ClassTimeline} from './PortfolioTabs.jsx';
const tabs={overview:'Tổng quan',history:'Lịch sử làm bài',mastery:'Thành thạo',outcomes:'Outcome / YCCĐ',competency:'Năng lực',knowledge:'Bản đồ kiến thức',habits:'Thói quen học tập',assignments:'Bài được giao',classes:'Lớp học'};
export default function StudentPortfolio(){const {user}=useAuth(),{studentId}=useParams(),id=studentId||user.id,self=user.role==='student',[params,setParams]=useSearchParams(),tab=tabs[params.get('tab')]?params.get('tab'):'overview';const [printing,setPrinting]=useState(false);useEffect(()=>{if(printing&&tab==='overview'){const frame=requestAnimationFrame(()=>{const nodes=[...document.querySelectorAll('.portfolio-overview details')],previous=nodes.map(n=>n.open);nodes.forEach(n=>{n.open=true;});try{window.print();}finally{nodes.forEach((n,i)=>{n.open=previous[i];});setPrinting(false);}});return()=>cancelAnimationFrame(frame);}},[printing,tab]);const load=usePortfolio(base+'/students/'+id+'/portfolio');if(!load.data)return <section className="practice-page portfolio-page"><h1>Hồ sơ học tập</h1><LoadState load={load}/></section>;const d=load.data;return <section className="practice-page portfolio-page">
 <nav className="portfolio-breadcrumb" aria-label="Đường dẫn">{self?<Link to="/practice">← Trang học tập</Link>:<><Link to="/practice">Học sinh & Học tập</Link> / <Link to="/practice/students">Quản lý học sinh</Link> / {d.student.full_name}</>}</nav>
 <header className="learning-header"><div><span className="eyebrow">Hồ sơ học tập</span><h1>{d.student.full_name}</h1><p>{d.student.student_code} · {d.current_memberships.map(m=>`${m.class_name} · Khối ${m.grade} · ${m.school_year}`).join(' | ')||'Chưa có lớp hiện tại'}</p><p>{d.student.is_active?'Tài khoản hoạt động':'Tài khoản đã khóa'} · Đăng nhập gần nhất: {date(d.student.last_login)}</p></div><div className="portfolio-actions"><button className="btn" onClick={()=>{setParams({tab:'overview'});setPrinting(true);}}>In / Lưu PDF</button>{!self&&user.capabilities?.['assignment.create']&&<details><summary>Tác vụ học sinh</summary><Link to={'/practice/assignments?student='+id}>Giao bài cho học sinh</Link>{user.capabilities?.['student.reset_password']&&<Link to={'/practice/students?student='+id+'&action=password'}>Đặt lại mật khẩu</Link>}{user.capabilities?.['student.transfer']&&<Link to={'/practice/students?student='+id+'&action=transfer'}>Chuyển lớp</Link>}</details>}</div></header>
 <label className="portfolio-tab-select">Phần hồ sơ<select aria-label="Phần hồ sơ" value={tab} onChange={e=>{const next=new URLSearchParams(params);next.set('tab',e.target.value);next.delete('offset');setParams(next);}}>{Object.entries(tabs).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><nav className="portfolio-tabs" aria-label="Các phần hồ sơ">{Object.entries(tabs).map(([key,label])=><Link key={key} to={'?'+new URLSearchParams({...Object.fromEntries(params),tab:key})} aria-current={tab===key?'page':undefined}>{label}</Link>)}</nav>
 <div key={id+':'+tab}>{['competency','knowledge','habits'].includes(tab)?<CompetencyPortfolio id={id} self={self} memberships={d.current_memberships} mode={tab}/>:tab==='overview'?<PortfolioOverview data={d} id={id} self={self}/>:tab==='history'?<AttemptHistory id={id} self={self}/>:tab==='mastery'?<MasteryPortfolio id={id}/>:tab==='outcomes'?<OutcomeMap id={id} self={self}/>:tab==='assignments'?<AssignmentPortfolio id={id}/>:<ClassTimeline id={id}/>}</div>
 </section>;}
